import type { ConfidenceLevel, LinkedInsight, RoomObject } from "./house-types";

const lab = "https://agencythings-gen-alpha.vercel.app";

function insight(
  id: string,
  title: string,
  thesis: string,
  confidence: ConfidenceLevel,
  scope: string,
  sources: [string, string],
): LinkedInsight {
  return {
    id,
    title,
    thesis,
    confidence,
    evidenceCount: 2,
    scope,
    sources,
    labUrl: `${lab}/insights/${id}`,
  };
}

export const roomObjects: RoomObject[] = [
  {
    id: "phone",
    label: "Open phone insights",
    object: "Phone + charger",
    title: "A personal screen before personal independence",
    thesis: "The phone concentrates creators, friendship, discovery, and private access inside a household-governed device.",
    context: "A phone on the bedside table represents a media life that can feel private while permissions, payment, safety, and access still depend on adults.",
    accent: "#ff6b92",
    position: { x: 10, y: 67 },
    mobileFocus: { x: 10, y: 64 },
    insights: [
      insight("time-device-access", "Personal access arrives before independence", "Device access begins inside family rules and developmental context.", "high", "Children 0-17; U.S. and U.K.", ["Common Sense Media", "Pew Research Center"]),
      insight("time-private-day", "Portable access changes the private media day", "Personal devices change where media can be used and who can see the moment.", "high", "Older children and teens; U.S.", ["Pew Research Center", "PwC"]),
      insight("media-creators-templates", "Creators turn culture into familiar formats", "Creators connect entertainment, identity, products, and participation.", "medium", "Children and young audiences; multi-market", ["Associated Press", "PwC"]),
      insight("media-discovery-commerce", "Discovery and commerce share a surface", "Interest, recommendation, and household purchase can happen in one feed.", "medium", "Gen Alpha industry studies", ["PwC", "EMARKETER"]),
    ],
  },
  {
    id: "television",
    label: "Open television insights",
    object: "Television",
    title: "The everything screen",
    thesis: "The television is no longer one channel: it can be video, search, sport, creator media, music, and a shared household ritual.",
    context: "The largest screen in the room holds the most visible overlap between personal taste and family context, making it the clearest home for media and influence insights.",
    accent: "#ff806b",
    position: { x: 73, y: 43 },
    mobileFocus: { x: 73, y: 43 },
    insights: [
      insight("media-video-default", "Video is a primary route through the media day", "Video sits beside gaming and streaming as a regular part of children's media use.", "high", "Children 0-16; U.S. and multi-market", ["Common Sense Media", "PwC"]),
      insight("time-youtube-rhythm", "YouTube is embedded in the household rhythm", "Video is a recurring part of young children's and teens' daily environments.", "high", "Children 0-17; U.S.", ["Common Sense Media", "Pew Research Center"]),
      insight("media-coviewing", "Shared viewing still shapes influence", "Children's media interests move through family routines and adult review.", "medium", "Children and households; U.S. and multi-market", ["Common Sense Media", "PwC"]),
      insight("media-properties-travel", "Entertainment properties travel across routes", "Creators, clips, games, and streaming give the same property several paths into attention.", "medium", "Young audiences; multi-market", ["Associated Press", "PwC"]),
    ],
  },
  {
    id: "homework-desk",
    label: "Open homework desk insights",
    object: "Laptop + homework desk",
    title: "AI has joined the homework routine",
    thesis: "The desk now combines explanation, search, making, recommendations, and the need to verify fluent answers.",
    context: "A half-finished notebook beside an open laptop makes AI concrete: it is already used in learning moments, even while guidance and source literacy are catching up.",
    accent: "#6ef2ff",
    position: { x: 61, y: 49 },
    mobileFocus: { x: 61, y: 49 },
    insights: [
      insight("learning-ai-homework", "AI is already part of homework and explanation", "AI has joined the practical toolkit children use for school tasks and explanations.", "medium", "Youth AI users; recent U.S. studies", ["Common Sense Media", "Common Sense Media"]),
      insight("learning-ai-discovery", "AI use extends beyond schoolwork", "Children also use AI for discovery, creativity, recommendations, and everyday support.", "medium", "Children and young people; recent industry studies", ["Razorfish", "Nielsen"]),
      insight("learning-verification", "Verification is becoming a core literacy", "Knowing when and how to check an answer matters as much as knowing how to ask.", "medium", "Youth AI users; U.S.", ["Nielsen", "Common Sense Media"]),
      insight("learning-safety-guidance", "Guidance is lagging behind adoption", "Family guidance, privacy safeguards, and visible limits remain necessary around youth AI use.", "medium", "Children and families; U.S.", ["Common Sense Media", "Federal Trade Commission"]),
    ],
  },
  {
    id: "game-console",
    label: "Open game console insights",
    object: "Game console + headset",
    title: "The console is a friendship place",
    thesis: "Games give small crews a repeatable place to talk, collaborate, compete, perform identity, and stay connected.",
    context: "The controller and headset represent the same relationship moving through game sessions, voice chat, clips, school, and offline time—not a child disappearing into a machine.",
    accent: "#a78bfa",
    position: { x: 80, y: 69 },
    mobileFocus: { x: 80, y: 64 },
    insights: [
      insight("play-social-infrastructure", "Play is social infrastructure", "Shared activity gives friendship a durable place to happen.", "high", "Teen players 13-17 and children in creation games", ["Pew Research Center", "Walton Family Foundation"]),
      insight("play-friendship-travels", "Friendship travels between settings", "Relationships move between games, chat, video, school, and real life.", "high", "Children and teens 8-17; U.S. and U.K.", ["Pew Research Center", "Ofcom"]),
      insight("play-small-crews", "Small crews sustain recurring connection", "Repeated shared activity gives friend groups a dependable place to meet.", "high", "Teen players and longitudinal child cases", ["Pew Research Center", "Ofcom"]),
      insight("play-safety-boundaries", "Safety boundaries are part of play", "Youth participation requires privacy, consent, reporting, and safety by design.", "high", "Children in online games; global policy context", ["UNICEF", "Federal Trade Commission"]),
    ],
  },
  {
    id: "backpack",
    label: "Open backpack insights",
    object: "Backpack + notebook",
    title: "Learning crosses the bell schedule",
    thesis: "School is one node in a learning system that also includes video, games, search, family help, and conversational tools.",
    context: "The backpack roots abstract learning claims in the child's next real transition: packing schoolwork, a device, social context, and unfinished questions into the same day.",
    accent: "#9be15d",
    position: { x: 35, y: 86 },
    mobileFocus: { x: 35, y: 78 },
    insights: [
      insight("learning-assembled", "Learning is assembled on demand", "A child can combine school, video, games, search, and another person to answer one need.", "medium", "Children and school-age youth; multi-study", ["Systematic education review", "Ofcom"]),
      insight("learning-enablement", "Technology matters for what it enables", "Educational value comes from the activity and support around a tool, not hardware novelty.", "high", "School-age learners; international review", ["Systematic education review", "Digital wellbeing review"]),
      insight("time-age-change", "Digital routines change quickly with age", "Device ownership, autonomy, platforms, and social context shift sharply across childhood.", "high", "Children 0-17; U.S.", ["Common Sense Media", "Pew Research Center"]),
      insight("learning-multimodal", "Learning moves among multiple modes", "Touch, typing, voice, video, play, and making can all sit inside one learning environment.", "medium", "Children and young people; multi-market", ["PwC", "Walton Family Foundation"]),
    ],
  },
  {
    id: "toy-shelf",
    label: "Open toy shelf insights",
    object: "Toy + story shelf",
    title: "Physical play and digital identity feed each other",
    thesis: "Action figures, stories, avatar style, games, and self-made media are connected ways to rehearse worlds and identity.",
    context: "The toy shelf replaces vague decorative hotspots with a real bridge between analog play, fandom, imaginative making, avatar expression, and properties that travel across formats.",
    accent: "#ffd27a",
    position: { x: 67, y: 29 },
    mobileFocus: { x: 67, y: 33 },
    insights: [
      insight("play-offline-rebound", "Offline play is rebounding, not disappearing", "Digital and physical activity should be studied together rather than as opposites.", "medium", "U.S. youth 6-17", ["Aspen Institute Project Play", "Outdoor Foundation"]),
      insight("play-avatars-identity", "Avatar style is an identity signal", "Digital expression lets young people try aesthetics and affiliations.", "medium", "Roblox users and Gen Alpha industry samples", ["Roblox", "Razorfish"]),
      insight("learning-remix", "Young people move from consuming to creating", "Game building and self-made media show active production across interests.", "medium", "Children and young people; U.S. studies", ["Walton Family Foundation", "Razorfish"]),
      insight("media-properties-travel", "Stories travel between shelves and screens", "Entertainment can enter through toys, games, clips, creators, and streaming.", "medium", "Young audiences; multi-market", ["Associated Press", "PwC"]),
    ],
  },
  {
    id: "parent-door",
    label: "Open parent and household insights",
    object: "Open door + parent cue",
    title: "Adults manage context, not only minutes",
    thesis: "Permission, privacy, payments, bedtime, content, and conversation make media a child-and-caregiver system.",
    context: "The open door makes adult involvement visible without turning the room into surveillance: independence grows inside household rules, resources, trust, and negotiation.",
    accent: "#fff0bd",
    position: { x: 91, y: 38 },
    mobileFocus: { x: 88, y: 40 },
    insights: [
      insight("time-parent-context", "Parents manage context and rules", "Household management includes content, privacy, timing, permission, and conversation.", "high", "Children and families; U.S. and global guidance", ["Common Sense Media", "UNICEF"]),
      insight("play-family-coplay", "Households set the conditions around play", "Access, permission, and payment keep play embedded in family systems.", "high", "Children 0-16 and households", ["Common Sense Media", "PwC"]),
      insight("media-household-negotiation", "Influence is negotiated inside the household", "Interest, permission, and purchase often involve adults.", "medium", "Gen Alpha and family industry studies", ["PwC", "GWI"]),
      insight("time-household-context", "Household resources shape access and use", "Quality of access, autonomy, subscriptions, and support are not uniform.", "medium", "U.S. children and households", ["Annie E. Casey Foundation", "Common Sense Media"]),
    ],
  },
  {
    id: "bike-window",
    label: "Open bike and outside insights",
    object: "Window + bike",
    title: "Outside is part of the same social map",
    thesis: "Bikes, sport, neighborhood crews, and school do not compete with digital life; they connect to the same friends, stories, and identities.",
    context: "The window keeps the room from becoming a screen-time terrarium. It shows that play, movement, local friendship, and digital coordination coexist in one child's day.",
    accent: "#c7ff75",
    position: { x: 40, y: 34 },
    mobileFocus: { x: 40, y: 36 },
    insights: [
      insight("play-offline-rebound", "Offline play is rebounding, not disappearing", "Sport and outdoor participation remain meaningful youth infrastructure.", "medium", "U.S. youth 6-17", ["Aspen Institute Project Play", "Outdoor Foundation"]),
      insight("time-coexistence", "Online time does not erase offline demand", "Digital activity needs to be considered with physical preference and context.", "medium", "Children and adolescents; mixed methods", ["Longitudinal wellbeing review", "Razorfish"]),
      insight("play-friendship-travels", "Friendship travels between games and real life", "The same relationships move through online and physical settings.", "high", "Children and teens 8-17; U.S. and U.K.", ["Pew Research Center", "Ofcom"]),
      insight("learning-assembled", "Learning moves through places", "School, video, play, search, and other people can combine around one question.", "medium", "School-age children; international review", ["Systematic education review", "Ofcom"]),
    ],
  },
];
