export type InfluencerIndicator = {
  label: string;
  value: string;
};

export type InfluencerProfile = {
  id: string;
  name: string;
  pronouns: "he" | "she" | "they";
  role: string;
  category: string;
  summary: string;
  influenceReason: string;
  audience: string;
  platforms: string[];
  moments: [string, string, string];
  indicators: InfluencerIndicator[];
  portrait: string;
  profileUrl: string;
  sourceUrl: string;
  featured: boolean;
  featuredVideo?: {
    youtubeId: string;
    title: string;
  };
};

type ProfileSeed = Omit<InfluencerProfile, "portrait" | "sourceUrl" | "indicators"> & {
  signals: [string, string, string, string];
};

function profile(seed: ProfileSeed): InfluencerProfile {
  return {
    ...seed,
    portrait: `/creators/${seed.id}.jpg`,
    sourceUrl: seed.profileUrl,
    indicators: [
      { label: "Reach", value: seed.signals[0] },
      { label: "Participation", value: seed.signals[1] },
      { label: "Commercial pull", value: seed.signals[2] },
      { label: "Audience center", value: seed.signals[3] }
    ]
  };
}

export const influencers: InfluencerProfile[] = [
  profile({ id: "mrbeast", name: "MrBeast", pronouns: "he", role: "Architect of scale", category: "Challenges and philanthropy", summary: "High-production challenges turn scale, suspense, generosity, and products into stories designed to be retold.", influenceReason: "He sets the benchmark for spectacle and teaches audiences to expect a clear premise, escalating stakes, and a reward they can explain in one sentence.", audience: "Core audience: ages 9-17, with broad household recognition", platforms: ["YouTube", "Shorts", "Consumer products"], moments: ["Massive endurance and elimination challenges", "Philanthropy built into entertainment", "Feastables and Beast Games extending the format"], signals: ["Category-defining", "Very high", "Very high", "9-17"], profileUrl: "https://www.youtube.com/@MrBeast", featured: true, featuredVideo: { youtubeId: "iYlODtkyw_I", title: "Survive 30 Days Chained To A Stranger, Win $250,000" } }),
  profile({ id: "ishowspeed", name: "IShowSpeed", pronouns: "he", role: "Live energy multiplier", category: "Livestreaming, sports, and music", summary: "Gaming, football, travel, music, and extreme reaction collapse into a live performance the audience helps steer.", influenceReason: "His volatility creates clip-ready moments and a sense that anything can happen while the audience is present.", audience: "Core audience: ages 13-18, especially sports and gaming fans", platforms: ["YouTube Live", "Shorts", "Music"], moments: ["Football and Cristiano Ronaldo fandom", "Global travel livestreams", "World Cup music and meme culture"], signals: ["Global mass", "Very high", "High", "13-18"], profileUrl: "https://www.youtube.com/@IShowSpeed", featured: true, featuredVideo: { youtubeId: "vrY1THC_NQE", title: "World Cup (Champions)" } }),
  profile({ id: "kai-cenat", name: "Kai Cenat", pronouns: "he", role: "Community orchestrator", category: "Livestreaming and comedy", summary: "Long-form streams feel like shared events where chat, guests, games, and escalating bits all shape the show.", influenceReason: "He turns duration into belonging: viewers are not only watching a personality, they are joining a recurring room with its own language and rituals.", audience: "Core audience: ages 13-18, with strong gaming and music overlap", platforms: ["Twitch", "YouTube", "AMP"], moments: ["Celebrity and musician livestream collaborations", "Subathon and marathon viewing events", "AMP ensemble comedy"], signals: ["Culture-leading", "Very high", "High", "13-18"], profileUrl: "https://www.youtube.com/@KaiCenat", featured: true, featuredVideo: { youtubeId: "Hhl74xWssbU", title: "Streamer University Los Angeles" } }),
  profile({ id: "aphmau", name: "Aphmau", pronouns: "she", role: "Story-world builder", category: "Minecraft roleplay", summary: "Recurring characters, humor, friendship, and fantasy turn Minecraft into an episodic story universe.", influenceReason: "She demonstrates that games can be narrative stages, not only competitions, and gives younger viewers characters and plots to carry into their own play.", audience: "Core audience: ages 7-14, with a strong girl and family audience", platforms: ["YouTube", "Minecraft", "Merchandise"], moments: ["Minecraft roleplay series", "Recurring character ensemble", "Toy and merchandise extensions"], signals: ["Category-leading", "High", "High", "7-14"], profileUrl: "https://www.youtube.com/@Aphmau", featured: true, featuredVideo: { youtubeId: "0HdrzSmjHwk", title: "You Cannot Be Contained" } }),
  profile({ id: "ms-rachel", name: "Ms. Rachel", pronouns: "she", role: "Early-learning guide", category: "Preschool education", summary: "Songs, repetition, direct address, and speech-development techniques create a trusted learning ritual for young children and caregivers.", influenceReason: "Her influence is co-viewed and adult-endorsed, showing how a creator can become part of a household routine rather than a private fandom.", audience: "Core audience: ages 1-6 plus parents and caregivers", platforms: ["YouTube", "Streaming", "Books and toys"], moments: ["Songs for Littles", "Speech and language development lessons", "Caregiver-facing learning guidance"], signals: ["Household-scale", "High", "High", "1-6"], profileUrl: "https://www.youtube.com/@MsRachel", featured: true, featuredVideo: { youtubeId: "2dDpryw3z5w", title: "Friendship and Social Skills for Kids" } }),
  profile({ id: "salish-matter", name: "Salish Matter", pronouns: "she", role: "Peer aspiration engine", category: "Family and lifestyle", summary: "Friendship, challenges, beauty, gymnastics, and family dynamics model an unusually visible version of early teen life.", influenceReason: "She feels close enough to copy while remaining aspirational, especially for viewers navigating the shift from child content to teen identity.", audience: "Core audience: ages 8-14, especially girls", platforms: ["YouTube", "Shorts", "Instagram"], moments: ["Father-daughter challenges", "Gymnastics and lifestyle routines", "Friendship and makeover videos"], signals: ["Fast-rising", "High", "High", "8-14"], profileUrl: "https://www.youtube.com/@SalishMatter", featured: false }),
  profile({ id: "ryans-world", name: "Ryan's World", pronouns: "he", role: "Play-to-product pioneer", category: "Kids, toys, and experiments", summary: "Toy play, experiments, animation, and a vast product ecosystem make the channel a gateway between viewing and shopping.", influenceReason: "Ryan's World established the modern blueprint for turning a child's play format into a multi-category consumer franchise.", audience: "Core audience: ages 3-9 plus parents", platforms: ["YouTube", "Streaming", "Retail"], moments: ["Mystery egg and toy play", "Science experiments", "Large licensed product ecosystem"], signals: ["Household-scale", "Medium", "Very high", "3-9"], profileUrl: "https://www.youtube.com/@RyansWorld", featured: false }),
  profile({ id: "like-nastya", name: "Like Nastya", pronouns: "she", role: "Global pretend-play lead", category: "Kids and family", summary: "Bright family adventures and pretend play travel across languages and markets with minimal cultural friction.", influenceReason: "The format proves that visual storytelling, repetition, and family relationships can scale more globally than dialogue-heavy content.", audience: "Core audience: ages 3-9 across global family markets", platforms: ["YouTube", "Streaming", "Licensing"], moments: ["Pretend-play stories", "Family travel adventures", "Multilingual channel network"], signals: ["Global mass", "Medium", "High", "3-9"], profileUrl: "https://www.youtube.com/@LikeNastyaOfficial", featured: false }),
  profile({ id: "kids-diana", name: "Kids Diana Show", pronouns: "she", role: "Visual story franchise", category: "Kids roleplay", summary: "Dress-up, sibling play, and simple moral stories create bright, accessible narratives for younger global viewers.", influenceReason: "Diana shows how a recognizable child character and repeatable visual grammar can become a global entertainment brand.", audience: "Core audience: ages 3-9 across global family markets", platforms: ["YouTube", "Streaming", "Licensing"], moments: ["Dress-up roleplay", "Sibling stories", "Love, Diana franchise extensions"], signals: ["Global mass", "Medium", "High", "3-9"], profileUrl: "https://www.youtube.com/@KidsDianaShow", featured: false }),
  profile({ id: "vlad-and-niki", name: "Vlad and Niki", pronouns: "they", role: "Sibling-play franchise", category: "Kids and family", summary: "Sibling challenges, toys, and family adventures use physical comedy and visual storytelling that travel easily.", influenceReason: "Their content turns ordinary sibling play into a repeatable spectacle and gives families a recognizable co-viewing format.", audience: "Core audience: ages 3-8 plus parents", platforms: ["YouTube", "Streaming", "Licensing"], moments: ["Toy adventures", "Sibling challenges", "Family travel and learning stories"], signals: ["Global mass", "Medium", "Very high", "3-8"], profileUrl: "https://www.youtube.com/@VladandNiki", featured: false }),
  profile({ id: "cocomelon", name: "CoComelon", pronouns: "they", role: "Routine soundtrack", category: "Preschool animation", summary: "Songs about everyday routines, emotions, and early learning create highly repeatable viewing for young children.", influenceReason: "The franchise demonstrates the power of familiarity, repetition, music, and routine in the earliest segment of Gen Alpha.", audience: "Core audience: ages 1-5 plus caregivers", platforms: ["YouTube", "Netflix", "Consumer products"], moments: ["Nursery-rhyme loops", "Bedtime and family routines", "Streaming and live-show extensions"], signals: ["Global mass", "Medium", "Very high", "1-5"], profileUrl: "https://www.youtube.com/@CoComelon", featured: false }),
  profile({ id: "alan-chikin-chow", name: "Alan Chikin Chow", pronouns: "he", role: "Short-form story machine", category: "Comedy and serial drama", summary: "Fast moral stories, school dynamics, and recurring characters translate short-form pacing into a connected universe.", influenceReason: "He packages emotion and resolution into instantly legible episodes built for mobile discovery and continuous watching.", audience: "Core audience: ages 10-17 with global short-form reach", platforms: ["YouTube Shorts", "TikTok", "Long-form series"], moments: ["School-life shorts", "Recurring character arcs", "Alan's Universe serial storytelling"], signals: ["Global mass", "High", "Medium", "10-17"], profileUrl: "https://www.youtube.com/@AlanChikinChow", featured: false }),
  profile({ id: "stokes-twins", name: "Stokes Twins", pronouns: "they", role: "Challenge duo", category: "Pranks and challenges", summary: "Twin chemistry, visual comedy, escalating challenges, and surprise create highly shareable global entertainment.", influenceReason: "Their simple premises and duo structure make the format easy to understand, repeat, and localize.", audience: "Core audience: ages 10-17", platforms: ["YouTube", "Shorts", "TikTok"], moments: ["Twin-switch comedy", "Social experiments", "Large-scale surprise challenges"], signals: ["Global mass", "High", "High", "10-17"], profileUrl: "https://www.youtube.com/@StokesTwins", featured: false }),
  profile({ id: "lankybox", name: "LankyBox", pronouns: "they", role: "Meme-to-merch engine", category: "Gaming and comedy", summary: "Roblox gameplay, loud reactions, songs, and mascot characters connect meme culture directly to products.", influenceReason: "LankyBox makes the channel itself feel like a toy universe, with recognizable characters that move between screen, play, and retail.", audience: "Core audience: ages 6-13", platforms: ["YouTube", "Roblox", "Retail"], moments: ["Roblox gameplay", "Justin and Adam reaction sketches", "Plush mascot and toy line"], signals: ["Category-leading", "High", "Very high", "6-13"], profileUrl: "https://www.youtube.com/@LankyBox", featured: false }),
  profile({ id: "danny-go", name: "Danny Go!", pronouns: "he", role: "Movement activator", category: "Kids music and movement", summary: "Dance-alongs, imaginative adventures, and movement prompts turn the screen into an invitation to physically participate.", influenceReason: "The format converts passive viewing into embodied play and is trusted by families, teachers, and caregivers.", audience: "Core audience: ages 2-8 plus families and classrooms", platforms: ["YouTube", "Music", "Live shows"], moments: ["Dance-along adventures", "The Floor Is Lava", "Classroom and family movement breaks"], signals: ["Fast-rising", "Very high", "Medium", "2-8"], profileUrl: "https://www.youtube.com/@DannyGo", featured: false }),
  profile({ id: "dude-perfect", name: "Dude Perfect", pronouns: "they", role: "Safe spectacle team", category: "Sports and stunts", summary: "Trick shots, friendly competition, stereotypes, and big builds deliver broad, family-safe spectacle.", influenceReason: "The group bridges children, teens, and parents with competition that feels aspirational without requiring controversy.", audience: "Core audience: ages 8-16 with strong family co-viewing", platforms: ["YouTube", "Live events", "Consumer products"], moments: ["Trick-shot videos", "Stereotypes series", "Overtime competitions"], signals: ["Household-scale", "High", "High", "8-16"], profileUrl: "https://www.youtube.com/@DudePerfect", featured: false }),
  profile({ id: "unspeakable", name: "Unspeakable", pronouns: "he", role: "Minecraft spectacle lead", category: "Gaming and challenges", summary: "Minecraft, oversized builds, physical stunts, and loud challenge pacing blend digital play with real-world spectacle.", influenceReason: "He translates game logic into physical experiences, making the fantasy of Minecraft feel tangible and participatory.", audience: "Core audience: ages 7-14", platforms: ["YouTube", "Minecraft", "Merchandise"], moments: ["Minecraft builds", "Extreme real-world challenges", "House and vehicle spectacles"], signals: ["Category-leading", "High", "High", "7-14"], profileUrl: "https://www.youtube.com/@Unspeakable", featured: false }),
  profile({ id: "kreekcraft", name: "KreekCraft", pronouns: "he", role: "Roblox news desk", category: "Roblox gaming", summary: "Livestreams, updates, lore, and community reactions make him a guide to Roblox as a living culture.", influenceReason: "He turns platform change into a shared event and gives players language for understanding what is happening across Roblox.", audience: "Core audience: ages 8-15 and Roblox power users", platforms: ["YouTube Live", "Roblox", "Shorts"], moments: ["Roblox update livestreams", "Game lore and reaction videos", "Community events"], signals: ["Platform-leading", "Very high", "Medium", "8-15"], profileUrl: "https://www.youtube.com/@KreekCraft", featured: false }),
  profile({ id: "preston", name: "Preston", pronouns: "he", role: "Competitive play host", category: "Minecraft and challenges", summary: "Competitive Minecraft, pranks, and team challenges create familiar stakes and a durable cast of collaborators.", influenceReason: "He keeps game content legible through simple goals, competition, and recurring relationships viewers can follow.", audience: "Core audience: ages 7-15", platforms: ["YouTube", "Minecraft", "Merchandise"], moments: ["Minecraft competitions", "PrestonPlayz challenge formats", "Creator and family collaborations"], signals: ["Category-leading", "High", "High", "7-15"], profileUrl: "https://www.youtube.com/@PrestonGame", featured: false }),
  profile({ id: "itsfunneh", name: "ItsFunneh", pronouns: "she", role: "Gaming ensemble lead", category: "Gaming and family comedy", summary: "The KREW turns Roblox and multiplayer games into a long-running social universe built around sibling chemistry.", influenceReason: "Fans return for the relationships as much as the games, making the ensemble a model for durable community storytelling.", audience: "Core audience: ages 8-15, with strong girl-gamer representation", platforms: ["YouTube", "Roblox", "KREW merchandise"], moments: ["KREW multiplayer gameplay", "Roblox roleplay", "Sibling travel and challenge content"], signals: ["Category-leading", "High", "High", "8-15"], profileUrl: "https://www.youtube.com/@ItsFunneh", featured: false }),
  profile({ id: "moriah-elizabeth", name: "Moriah Elizabeth", pronouns: "she", role: "Calm creativity anchor", category: "Art and DIY", summary: "Colorful makeovers, recurring characters, and satisfying craft processes offer a calmer form of creator attachment.", influenceReason: "She turns making into serial entertainment and proves that process, imperfection, and a distinctive visual world can hold attention.", audience: "Core audience: ages 8-16, especially creative girls", platforms: ["YouTube", "Books", "Art products"], moments: ["Squishy makeovers", "Create This Book", "Recurring original characters"], signals: ["Category-leading", "High", "High", "8-16"], profileUrl: "https://www.youtube.com/@MoriahElizabeth", featured: false }),
  profile({ id: "sssniperwolf", name: "SSSniperWolf", pronouns: "she", role: "Reaction narrator", category: "Reactions and gaming", summary: "Fast commentary and reaction formats offer an easy entry point to viral clips, games, and online conversation.", influenceReason: "She acts as a personality layer over internet culture, showing how reaction itself can become the product.", audience: "Core audience: ages 12-18", platforms: ["YouTube", "Shorts", "Gaming"], moments: ["Try-not-to-laugh reactions", "Viral clip commentary", "Gaming-era fan base"], signals: ["Mass reach", "Medium", "High", "12-18"], profileUrl: "https://www.youtube.com/@sssniperwolf", featured: false }),
  profile({ id: "rebecca-zamolo", name: "Rebecca Zamolo", pronouns: "she", role: "Serialized challenge host", category: "Mysteries and family challenges", summary: "Mysteries, escape rooms, family stories, and recurring characters reward viewers for following a continuing narrative.", influenceReason: "She uses cliffhangers and connected episodes to make family-friendly challenge content feel like a participatory series.", audience: "Core audience: ages 8-15", platforms: ["YouTube", "Shorts", "Consumer products"], moments: ["Game Master Network", "Escape-room challenges", "Family mystery storylines"], signals: ["Category-leading", "High", "High", "8-15"], profileUrl: "https://www.youtube.com/@rebeccazamolo", featured: false }),
  profile({ id: "charli-damelio", name: "Charli D'Amelio", pronouns: "she", role: "Cross-platform dance icon", category: "Dance and lifestyle", summary: "Dance, style, family, and celebrity turn a social-native identity into a broader entertainment and product brand.", influenceReason: "She remains a reference point for how an accessible peer performance can scale into mainstream youth celebrity.", audience: "Core audience: ages 10-18, especially girls", platforms: ["TikTok", "YouTube", "Instagram"], moments: ["Viral dance formats", "D'Amelio family series", "Beauty and fashion partnerships"], signals: ["Global mass", "High", "Very high", "10-18"], profileUrl: "https://www.youtube.com/@charlidamelio", featured: false }),
  profile({ id: "nicole-laeno", name: "Nicole Laeno", pronouns: "she", role: "Teen routine model", category: "Dance and lifestyle", summary: "School, dance, wellness, and week-in-my-life videos make teen routines visible and aspirational.", influenceReason: "She gives older Gen Alpha a detailed model of how identity is organized through habits, aesthetics, friendships, and milestones.", audience: "Core audience: ages 11-18, especially girls", platforms: ["YouTube", "TikTok", "Instagram"], moments: ["Week-in-my-life vlogs", "Dance videos", "School and wellness routines"], signals: ["Fast-rising", "Medium", "High", "11-18"], profileUrl: "https://www.youtube.com/@NicoleLaeno", featured: false }),
  profile({ id: "jules-leblanc", name: "Jules LeBlanc", pronouns: "she", role: "Youth-entertainment bridge", category: "Lifestyle, music, and acting", summary: "A long-running online career connects family vlogging, acting, music, and teen lifestyle content.", influenceReason: "Her trajectory shows how a childhood creator identity can mature with the audience and move into traditional entertainment.", audience: "Core audience: ages 10-17, especially girls", platforms: ["YouTube", "Instagram", "Streaming series"], moments: ["Bratayley-era family content", "Acting roles", "Music and lifestyle videos"], signals: ["Established", "Medium", "Medium", "10-17"], profileUrl: "https://www.youtube.com/@julesleblanc", featured: false }),
  profile({ id: "piper-rockelle", name: "Piper Rockelle", pronouns: "she", role: "Peer-drama producer", category: "Teen comedy and lifestyle", summary: "Friendship groups, challenges, music, and relationship storylines create an intensely peer-focused entertainment world.", influenceReason: "The appeal comes from social access: viewers watch a visible friend group perform the belonging, conflict, and milestones they are beginning to navigate.", audience: "Core audience: ages 8-15, especially girls", platforms: ["YouTube", "Music", "Instagram"], moments: ["Squad challenges", "Friendship and relationship storylines", "Music-video releases"], signals: ["Large", "High", "High", "8-15"], profileUrl: "https://www.youtube.com/@PiperRockelle", featured: false }),
  profile({ id: "brent-rivera", name: "Brent Rivera", pronouns: "he", role: "Mobile comedy lead", category: "Comedy and challenges", summary: "Short comedic scenarios, friend-group challenges, and collaborations translate social situations into fast entertainment.", influenceReason: "He packages familiar school, dating, friendship, and family dynamics into formats designed for immediate recognition.", audience: "Core audience: ages 10-18", platforms: ["YouTube", "Shorts", "TikTok"], moments: ["Friend-group challenges", "Relatable social skits", "Amp World collaborations"], signals: ["Mass reach", "High", "High", "10-18"], profileUrl: "https://www.youtube.com/@BrentRivera", featured: false }),
  profile({ id: "ben-azelart", name: "Ben Azelart", pronouns: "he", role: "Stunt challenge lead", category: "Stunts and challenges", summary: "Physical challenges, travel, hidden builds, and creator collaborations use high stakes with a peer-group tone.", influenceReason: "He combines the scale of spectacle with the accessibility of a visible friend group, making each video feel both large and socially close.", audience: "Core audience: ages 10-17", platforms: ["YouTube", "Shorts", "TikTok"], moments: ["Extreme physical challenges", "Hidden-room and build videos", "Creator travel stunts"], signals: ["Mass reach", "High", "High", "10-17"], profileUrl: "https://www.youtube.com/@BenAzelart", featured: false }),
  profile({ id: "jesser", name: "Jesser", pronouns: "he", role: "Creator-sports connector", category: "Basketball entertainment", summary: "Basketball challenges, NBA access, and creator competition blend sports fandom with internet personality culture.", influenceReason: "He gives younger sports fans a participatory bridge between professional leagues and the creator formats they already understand.", audience: "Core audience: ages 10-18, especially basketball fans", platforms: ["YouTube", "Shorts", "2HYPE"], moments: ["Basketball challenges", "NBA player collaborations", "2HYPE competitions"], signals: ["Sports-leading", "High", "High", "10-18"], profileUrl: "https://www.youtube.com/@Jesser", featured: false })
];

export function getInfluencerById(id: string): InfluencerProfile | undefined {
  return influencers.find((influencer) => influencer.id === id);
}

export const featuredInfluencers = influencers.filter((influencer) => influencer.featured);
