import type { ResearchRecord, ReviewStatus } from "./types";

export const seedRecords: ResearchRecord[] = [
  {
    id: "pwc-alpha-2026",
    kind: "report",
    sourceClass: "primary research",
    title: "Generation Alpha Survey 2026",
    source: "PwC",
    url: "https://www.pwc.com/us/en/industries/consumer-markets/library/gen-alpha-survey-report.html",
    summary: "U.S. survey of 7- to 14-year-olds on technology, household shopping, and influence.",
    tags: ["influence", "family", "commerce", "ai"],
    useModes: ["think", "learn"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2026-03-11",
    createdAt: "2026-07-12T14:00:00.000Z"
  },
  {
    id: "nielsen-ai-discovery-2026",
    kind: "report",
    sourceClass: "primary research",
    title: "Gen Alpha Leads Shift to AI-Powered Entertainment Search, Discovery and Recommendations",
    source: "Nielsen / Gracenote",
    url: "https://www.nielsen.com/news-center/2026/gen-alpha-leads-shift-to-ai-powered-entertainment-search-discovery-and-recommendations/",
    summary: "A Gracenote study on entertainment search, recommendations, chatbot use, and trust.",
    tags: ["ai", "media", "discovery", "trust"],
    useModes: ["think", "learn"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2026-04-08",
    createdAt: "2026-07-12T14:01:00.000Z"
  },
  {
    id: "common-sense-census-2025",
    kind: "report",
    sourceClass: "primary research",
    title: "The 2025 Common Sense Census: Media Use by Kids Zero to Eight",
    source: "Common Sense Media",
    url: "https://www.commonsensemedia.org/research/the-2025-common-sense-census-media-use-by-kids-zero-to-eight",
    summary: "National baseline on young children’s media use, device access, video, and household context.",
    tags: ["media", "time", "family", "connect"],
    useModes: ["learn", "think"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2025-01-01",
    createdAt: "2026-07-12T14:02:00.000Z"
  },
  {
    id: "pew-kids-screens-2025",
    kind: "report",
    sourceClass: "primary research",
    title: "How Parents Manage Screen Time for Kids",
    source: "Pew Research Center",
    url: "https://www.pewresearch.org/internet/2025/10/08/how-parents-manage-screen-time-for-kids/",
    summary: "Parent survey on rules, screen-time management, and children’s platform use.",
    tags: ["time", "family", "media"],
    useModes: ["learn"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2025-10-08",
    createdAt: "2026-07-12T14:03:00.000Z"
  },
  {
    id: "pew-teens-video-games-2024",
    kind: "report",
    sourceClass: "primary research",
    title: "Teens, Video Games and Civics",
    source: "Pew Research Center",
    url: "https://www.pewresearch.org/internet/2024/05/09/teens-and-video-games-today/",
    summary: "A teen study that provides adjacent context for gaming as a social experience.",
    tags: ["gaming", "connect", "play-create"],
    useModes: ["learn", "think"],
    status: "reviewed",
    confidence: "medium",
    publishedAt: "2024-05-09",
    createdAt: "2026-07-12T14:04:00.000Z"
  },
  {
    id: "walton-creation-gaming-2024",
    kind: "report",
    sourceClass: "primary research",
    title: "The Creation Generation: Creation Gaming for Learning and Development",
    source: "Walton Family Foundation / Bodacious",
    url: "https://www.waltonfamilyfoundation.org/bodacious-and-walton-family-foundation-unveil-new-report-on-generation-alphas-use-of-creation-gaming-for-learning-and-development",
    summary: "A nationally representative survey of 5- to 13-year-olds plus qualitative interviews on Roblox and Minecraft.",
    tags: ["gaming", "learn", "play-create", "connect"],
    useModes: ["make", "learn", "think"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2024-04-16",
    createdAt: "2026-07-12T14:05:00.000Z"
  },
  {
    id: "generation-alpha-education-review-2024",
    kind: "article",
    sourceClass: "peer reviewed",
    title: "A Systematic Literature Review of Education for Generation Alpha",
    source: "Discover Education",
    url: "https://link.springer.com/article/10.1007/s44217-024-00218-3",
    summary: "PRISMA-based review of 83 studies covering teaching, tools, and blended learning for Generation Alpha.",
    tags: ["learn", "education", "systematic-review"],
    useModes: ["learn"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2024-08-09",
    createdAt: "2026-07-12T14:06:00.000Z"
  },
  {
    id: "digital-wellbeing-review-2025",
    kind: "article",
    sourceClass: "peer reviewed",
    title: "Digital Technology Use and Well-being in Young Children: A Systematic Review and Meta-analysis",
    source: "Computers in Human Behavior",
    url: "https://doi.org/10.1016/j.chb.2025.108660",
    summary: "Systematic review and meta-analysis of digital technology use and psychosocial well-being among children aged four to six.",
    tags: ["time", "wellbeing", "systematic-review"],
    useModes: ["learn"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2025-07-01",
    createdAt: "2026-07-12T14:07:00.000Z"
  },
  {
    id: "screen-socioemotional-review-2025",
    kind: "article",
    sourceClass: "peer reviewed",
    title: "Electronic Screen Use and Children's Socioemotional Problems: A Systematic Review and Meta-analysis of Longitudinal Studies",
    source: "Psychological Bulletin",
    url: "https://pubmed.ncbi.nlm.nih.gov/40489178/",
    summary: "Longitudinal evidence review that cautions against simple one-directional stories about screens and socioemotional outcomes.",
    tags: ["time", "wellbeing", "systematic-review"],
    useModes: ["learn"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2025-05-01",
    createdAt: "2026-07-12T14:08:00.000Z"
  },
  {
    id: "ap-sports-alpha-2026",
    kind: "article",
    sourceClass: "journalism",
    title: "Sports Leagues Race to Capture Gen Z and Gen Alpha with AI, Influencers and Italian Brainrot",
    source: "Associated Press",
    url: "https://apnews.com/article/62f54a8cd7748850e94470a814f8082e",
    summary: "Reported view of how sports organizations are adapting to creator-led and participatory youth culture.",
    tags: ["influence", "media", "creators"],
    useModes: ["think", "make"],
    status: "reviewed",
    confidence: "medium",
    publishedAt: "2026-02-10",
    createdAt: "2026-07-12T14:09:00.000Z"
  },
  {
    id: "common-sense-chatgpt-video",
    kind: "article",
    sourceClass: "video",
    title: "What Is ChatGPT?",
    source: "Common Sense Media",
    url: "https://www.commonsensemedia.org/videos/what-is-chatgpt",
    summary: "A short family-facing video on what ChatGPT does and how kids can use it responsibly.",
    tags: ["ai", "learn", "safety"],
    useModes: ["learn"],
    status: "reviewed",
    confidence: "medium",
    createdAt: "2026-07-12T14:10:00.000Z"
  },
  {
    id: "common-sense-media-youtube-2025",
    kind: "youtube",
    sourceClass: "youtube",
    title: "Media and Young Kids: New Research, Real Tips for Parents",
    source: "Common Sense Media",
    url: "https://www.youtube.com/watch?v=3mnan0zpxAo",
    summary: "Video briefing connected to Common Sense Media's 2025 census on young children's media use.",
    tags: ["youtube", "media", "family", "time"],
    useModes: ["learn"],
    status: "reviewed",
    confidence: "medium",
    publishedAt: "2025-04-01",
    createdAt: "2026-07-12T14:10:30.000Z"
  },
  {
    id: "reddit-genalpha-community-2024",
    kind: "field-note",
    sourceClass: "community",
    title: "Community discussion: differences Gen Alpha notices in its own online culture",
    source: "Reddit r/GenAlpha",
    url: "https://www.reddit.com/r/GenAlpha/comments/1at72w1/yes_im_gen_alpha/",
    summary: "Qualitative community material only; useful for vocabulary and hypotheses, never as representative evidence.",
    tags: ["community", "media", "language"],
    useModes: ["think"],
    status: "queued",
    confidence: "low",
    createdAt: "2026-07-12T14:11:00.000Z"
  },
  {
    id: "owned-podcast-093",
    kind: "podcast",
    sourceClass: "owned",
    title: "#093 Gen Alpha: AI, Gaming, and the First Fully Digital Childhood",
    source: "Eclectic Polymath",
    url: "https://open.spotify.com/episode/7l1peATWasIYA07RvqKgwn?si=XGKqiaAJRAKCs2F4X3wn_g",
    summary: "A podcast conversation exploring how AI, gaming, and always-on media shape the first fully digital childhood.",
    synthesisStatus: "Featured synthesis",
    tags: ["owned", "ai", "gaming", "digital-childhood"],
    useModes: ["think"],
    status: "queued",
    confidence: "low",
    createdAt: "2026-07-12T14:12:00.000Z"
  },
  {
    id: "future-report-alpha-mccrindle-2025",
    kind: "podcast",
    sourceClass: "podcast",
    title: "Inside the mind of Gen Alpha with Ashley Fell and Luke Davies",
    source: "The Future Report",
    url: "https://open.spotify.com/episode/5WPGgs3LmLOAkxww8NwsKS",
    summary: "McCrindle conversation useful for contrasting practitioner language with the lab's evidence-led findings.",
    tags: ["podcast", "mccrindle", "culture", "gen-alpha"],
    useModes: ["think"],
    status: "queued",
    confidence: "medium",
    publishedAt: "2025-09-01",
    createdAt: "2026-07-12T14:12:30.000Z"
  },
  {
    id: "mccrindle-generation-alpha-book",
    kind: "book",
    sourceClass: "book",
    title: "Generation Alpha",
    source: "McCrindle",
    author: "Mark McCrindle and Ashley Fell",
    url: "https://mccrindle.com.au/resource/book/generation-alpha-book/",
    summary: "Book-length framing of Generation Alpha for parents, teachers, and leaders, including technology, education, consumer habits, and wellbeing.",
    tags: ["book", "generation-alpha", "education", "consumer-behavior"],
    useModes: ["think", "learn"],
    status: "queued",
    confidence: "medium",
    publishedAt: "2021-04-01",
    createdAt: "2026-07-12T14:12:45.000Z"
  },
  {
    id: "mccrindle-alpha-defined",
    kind: "article",
    sourceClass: "industry research",
    title: "Understanding Generation Alpha",
    source: "McCrindle",
    url: "https://mccrindle.com.au/article/topic/generation-alpha/generation-alpha-defined/",
    summary: "A foundational practitioner definition of the cohort, its formative conditions, and the generational frame used across much of the public conversation.",
    tags: ["generation-alpha", "demographics", "culture"],
    useModes: ["think", "learn"],
    status: "reviewed",
    confidence: "medium",
    createdAt: "2026-07-15T14:00:00.000Z"
  },
  {
    id: "emarketer-alpha-habits-2026",
    kind: "report",
    sourceClass: "industry research",
    title: "Gen Alpha Digital Habits 2026",
    source: "EMARKETER",
    url: "https://www.emarketer.com/content/gen-alpha-digital-habits-2026/",
    summary: "Forecast-led analysis of Gen Alpha's media use, gaming, platform adoption, and digital attention in 2026.",
    tags: ["media", "time", "gaming", "platforms"],
    useModes: ["think", "make"],
    status: "reviewed",
    confidence: "medium",
    publishedAt: "2026-02-01",
    createdAt: "2026-07-15T14:01:00.000Z"
  },
  {
    id: "emarketer-alpha-faq-2026",
    kind: "article",
    sourceClass: "industry research",
    title: "FAQ on Gen Alpha: How Marketers Can Reach This Generation in 2026",
    source: "EMARKETER",
    url: "https://www.emarketer.com/content/faq-on-gen-alpha--how-marketers-reach-this-generation-2026/",
    summary: "A practical briefing on household influence, creator partnerships, gaming spaces, privacy constraints, and participatory formats.",
    tags: ["influence", "media", "commerce", "privacy"],
    useModes: ["make"],
    status: "reviewed",
    confidence: "medium",
    publishedAt: "2026-02-26",
    createdAt: "2026-07-15T14:02:00.000Z"
  },
  {
    id: "gwi-alpha-unfiltered",
    kind: "report",
    sourceClass: "industry research",
    title: "Gen Alpha Unfiltered",
    source: "GWI",
    url: "https://www.gwi.com/reports/gen-alpha",
    summary: "Consumer research on Gen Alpha's interests, media behaviors, family influence, and expectations of brands.",
    tags: ["culture", "media", "influence", "commerce"],
    useModes: ["think", "learn", "make"],
    status: "reviewed",
    confidence: "medium",
    createdAt: "2026-07-15T14:03:00.000Z"
  },
  {
    id: "razorfish-alpha-ai",
    kind: "report",
    sourceClass: "industry research",
    title: "Gen Alpha's Relationship With AI",
    source: "Razorfish",
    url: "https://www.razorfish.com/articles/news/razorfish-explores-gen-alpha-relationship-with-ai-in-new-study/",
    summary: "Study of how Gen Alpha understands, trusts, and imagines AI across school, creativity, relationships, and brands.",
    tags: ["ai", "trust", "learn", "influence"],
    useModes: ["think", "make", "learn"],
    status: "reviewed",
    confidence: "medium",
    createdAt: "2026-07-15T14:04:00.000Z"
  },
  {
    id: "razorfish-alpha-industries",
    kind: "report",
    sourceClass: "industry research",
    title: "Generation Alpha's Perceptions of Five Key Industries",
    source: "Razorfish",
    url: "https://www.razorfish.com/articles/news/razorfishs-new-gen-alpha-research-spotlights-the-generations-perceptions-of-five-key-industries/",
    summary: "Research into Gen Alpha's expectations of technology, retail, finance, travel, and health brands.",
    tags: ["influence", "commerce", "brands", "culture"],
    useModes: ["think", "make"],
    status: "reviewed",
    confidence: "medium",
    createdAt: "2026-07-15T14:05:00.000Z"
  },
  {
    id: "ftc-coppa-2025",
    kind: "article",
    sourceClass: "policy",
    title: "FTC Finalizes Changes to the Children's Privacy Rule",
    source: "U.S. Federal Trade Commission",
    url: "https://www.ftc.gov/news-events/news/press-releases/2025/01/ftc-finalizes-changes-childrens-privacy-rule-limiting-companies-ability-monetize-kids-data",
    summary: "The official COPPA rule update limiting how companies collect, retain, and monetize children's data.",
    tags: ["privacy", "safety", "policy", "platforms"],
    useModes: ["learn", "make"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2025-01-16",
    createdAt: "2026-07-15T14:06:00.000Z"
  },
  {
    id: "roblox-search-style-trends-2025",
    kind: "article",
    sourceClass: "industry research",
    title: "Roblox Releases New Data Decoding Search and Style Trends in Digital Experiences",
    source: "Roblox",
    url: "https://ir.roblox.com/news/news-details/2025/Roblox-Releases-New-Data-Decoding-Search-and-Style-Trends-in-Digital-Experiences/default.aspx",
    summary: "Platform data on what users search for and how avatar style, identity, and culture move through digital worlds.",
    tags: ["play-create", "media", "identity", "gaming"],
    useModes: ["make"],
    status: "reviewed",
    confidence: "medium",
    createdAt: "2026-07-15T14:07:00.000Z"
  },
  {
    id: "arxiv-young-user-safety-2025",
    kind: "article",
    sourceClass: "preprint",
    title: "Protecting Young Users on Social Media",
    source: "arXiv",
    url: "https://arxiv.org/abs/2505.11160",
    summary: "An experimental audit of 3,000 videos evaluating content moderation and harmful recommendations for younger accounts across major video platforms.",
    tags: ["media", "safety", "algorithms", "platforms"],
    useModes: ["learn"],
    status: "reviewed",
    confidence: "medium",
    publishedAt: "2025-05-16",
    createdAt: "2026-07-15T14:08:00.000Z"
  },
  {
    id: "esafety-social-minimum-age",
    kind: "article",
    sourceClass: "policy",
    title: "Social Media Age Restrictions",
    source: "Australian eSafety Commissioner",
    url: "https://www.esafety.gov.au/about-us/industry-regulation/social-media-age-restrictions",
    summary: "Official guidance on Australia's social media minimum-age law, platform obligations, and children's rights considerations.",
    tags: ["policy", "safety", "privacy", "connect"],
    useModes: ["learn", "make"],
    status: "reviewed",
    confidence: "high",
    createdAt: "2026-07-15T14:09:00.000Z"
  },
  {
    id: "aecf-generation-alpha",
    kind: "article",
    sourceClass: "industry research",
    title: "What Is Generation Alpha?",
    source: "Annie E. Casey Foundation",
    url: "https://www.aecf.org/blog/what-is-generation-alpha",
    summary: "A child-wellbeing overview of the cohort's demographics, family context, technology exposure, and developmental environment.",
    tags: ["demographics", "family", "wellbeing", "culture"],
    useModes: ["learn", "think"],
    status: "reviewed",
    confidence: "medium",
    createdAt: "2026-07-15T14:10:00.000Z"
  },
  {
    id: "common-sense-ai-2026",
    kind: "report",
    sourceClass: "primary research",
    title: "AI Use by Tweens and Teens 2026",
    source: "Common Sense Media",
    url: "https://www.commonsensemedia.org/press-releases/common-sense-media-releases-inaugural-annual-study-on-ai-use-by-tweens-and-teens",
    summary: "A national study of how young people use AI, what they trust, what they hide, and where adult guidance is lagging.",
    tags: ["ai", "learn", "trust", "family"],
    useModes: ["learn", "think"],
    status: "reviewed",
    confidence: "high",
    createdAt: "2026-07-15T14:11:00.000Z"
  },
  {
    id: "oxford-brain-rot-2024",
    kind: "article",
    sourceClass: "journalism",
    title: "Brain Rot Named Oxford Word of the Year 2024",
    source: "Oxford University Press",
    url: "https://corp.oup.com/news/brain-rot-named-oxford-word-of-the-year-2024/",
    summary: "A cultural-language reference for understanding how concern about low-value online media entered mainstream conversation.",
    tags: ["culture", "language", "media", "time"],
    useModes: ["think", "make"],
    status: "reviewed",
    confidence: "medium",
    publishedAt: "2024-12-02",
    createdAt: "2026-07-15T14:12:00.000Z"
  },
  {
    id: "pew-teens-social-2024",
    kind: "report",
    sourceClass: "primary research",
    title: "Teens, Social Media and Technology 2024",
    source: "Pew Research Center",
    author: "Michelle Faverio and Olivia Sidoti",
    url: "https://www.pewresearch.org/internet/2024/12/12/teens-social-media-and-technology-2024/",
    summary: "Representative U.S. teen survey covering platform use, frequency, demographic differences, device access, and near-constant internet use.",
    tags: ["spaces", "youtube", "tiktok", "instagram", "snapchat"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2024-12-12",
    createdAt: "2026-07-16T00:01:00.000Z"
  },
  {
    id: "pew-platform-experiences-2026",
    kind: "report",
    sourceClass: "primary research",
    title: "Teens' Experiences on TikTok, Instagram and Snapchat",
    source: "Pew Research Center",
    url: "https://www.pewresearch.org/internet/2026/04/15/teens-experiences-on-tiktok-instagram-and-snapchat/",
    summary: "Survey of teens and parents on connection, messaging, time, friendship, and well-being across three major social platforms.",
    tags: ["spaces", "connection", "tiktok", "instagram", "snapchat"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2026-04-15",
    createdAt: "2026-07-16T00:02:00.000Z"
  },
  {
    id: "ofcom-children-media-lives-2025",
    kind: "report",
    sourceClass: "primary research",
    title: "Children's Media Lives 2025",
    source: "Ofcom",
    url: "https://www.ofcom.org.uk/siteassets/resources/documents/research-and-data/media-literacy-research/children/childrens-media-lives-2025/childrens-media-lives-2025-summary-report.pdf?v=396299",
    summary: "Longitudinal qualitative research showing how young people move among games, video, chat, family rules, and friend groups in everyday life.",
    tags: ["spaces", "roblox", "discord", "youtube", "routines"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2025-05-01",
    createdAt: "2026-07-16T00:03:00.000Z"
  },
  {
    id: "unicef-online-gaming",
    kind: "report",
    sourceClass: "policy",
    title: "Protecting Children in Online Gaming",
    source: "UNICEF Innocenti",
    url: "https://www.unicef.org/innocenti/reports/protecting-children-online-gaming",
    summary: "Child-rights framework for understanding the opportunities, design responsibilities, and safety risks inside online games.",
    tags: ["gaming", "safety", "roblox", "minecraft", "fortnite"],
    status: "reviewed",
    confidence: "high",
    createdAt: "2026-07-16T00:04:00.000Z"
  },
  {
    id: "anxious-generation-book",
    kind: "book",
    sourceClass: "book",
    title: "The Anxious Generation",
    source: "Penguin Press",
    author: "Jonathan Haidt",
    url: "https://www.penguinrandomhouse.com/books/729231/the-anxious-generation-by-jonathan-haidt/",
    summary: "Influential argument about childhood, smartphones, play, and mental health, included as a frame to compare with longitudinal and dissenting evidence.",
    tags: ["wellbeing", "phones", "play", "debate"],
    status: "queued",
    confidence: "medium",
    publishedAt: "2024-03-26",
    createdAt: "2026-07-16T00:05:00.000Z"
  },
  {
    id: "field-cousin-placeholder",
    kind: "interview",
    sourceClass: "owned",
    title: "Interview slot: cousin media diary",
    source: "Field interview",
    summary: "Reserved place for a private interview about daily screens, games, AI, and household influence.",
    tags: ["interview", "media-diary", "family"],
    status: "new",
    confidence: "medium",
    createdAt: "2026-07-12T14:13:00.000Z"
  }
];

export const statusLabels: Record<ReviewStatus, string> = {
  new: "New",
  queued: "Queued",
  reviewed: "Reviewed"
};
