import type { ResearchRecord, ReviewStatus } from "./types";

export const seedRecords: ResearchRecord[] = [
  {
    id: "pwc-alpha-2026",
    kind: "report",
    sourceClass: "primary research",
    title: "Generation Alpha Survey 2026",
    source: "PwC",
    url: "https://www.pwc.com/us/en/industries/consumer-markets/library/gen-alpha-survey-report.html",
    summary: "U.S. survey of 7- to 14-year-olds on technology, household shopping, and influence.",
    tags: ["influence", "family", "commerce", "ai"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2026-03-11",
    createdAt: "2026-07-12T14:00:00.000Z"
  },
  {
    id: "nielsen-ai-discovery-2026",
    kind: "report",
    sourceClass: "primary research",
    title: "Gen Alpha Leads Shift to AI-Powered Entertainment Search, Discovery and Recommendations",
    source: "Nielsen / Gracenote",
    url: "https://www.nielsen.com/news-center/2026/gen-alpha-leads-shift-to-ai-powered-entertainment-search-discovery-and-recommendations/",
    summary: "A Gracenote study on entertainment search, recommendations, chatbot use, and trust.",
    tags: ["ai", "media", "discovery", "trust"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2026-04-08",
    createdAt: "2026-07-12T14:01:00.000Z"
  },
  {
    id: "common-sense-census-2025",
    kind: "report",
    sourceClass: "primary research",
    title: "The 2025 Common Sense Census: Media Use by Kids Zero to Eight",
    source: "Common Sense Media",
    url: "https://www.commonsensemedia.org/research/the-2025-common-sense-census-media-use-by-kids-zero-to-eight",
    summary: "National baseline on young children’s media use, device access, video, and household context.",
    tags: ["media", "time", "family", "connect"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2025-01-01",
    createdAt: "2026-07-12T14:02:00.000Z"
  },
  {
    id: "pew-kids-screens-2025",
    kind: "report",
    sourceClass: "primary research",
    title: "How Parents Manage Screen Time for Kids",
    source: "Pew Research Center",
    url: "https://www.pewresearch.org/internet/2025/10/08/how-parents-manage-screen-time-for-kids/",
    summary: "Parent survey on rules, screen-time management, and children’s platform use.",
    tags: ["time", "family", "media"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2025-10-08",
    createdAt: "2026-07-12T14:03:00.000Z"
  },
  {
    id: "pew-teens-video-games-2024",
    kind: "report",
    sourceClass: "primary research",
    title: "Teens, Video Games and Civics",
    source: "Pew Research Center",
    url: "https://www.pewresearch.org/internet/2024/05/09/teens-and-video-games-today/",
    summary: "A teen study that provides adjacent context for gaming as a social experience.",
    tags: ["gaming", "connect", "play-create"],
    status: "reviewed",
    confidence: "medium",
    publishedAt: "2024-05-09",
    createdAt: "2026-07-12T14:04:00.000Z"
  },
  {
    id: "walton-creation-gaming-2024",
    kind: "report",
    sourceClass: "primary research",
    title: "The Creation Generation: Creation Gaming for Learning and Development",
    source: "Walton Family Foundation / Bodacious",
    url: "https://www.waltonfamilyfoundation.org/bodacious-and-walton-family-foundation-unveil-new-report-on-generation-alphas-use-of-creation-gaming-for-learning-and-development",
    summary: "A nationally representative survey of 5- to 13-year-olds plus qualitative interviews on Roblox and Minecraft.",
    tags: ["gaming", "learn", "play-create", "connect"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2024-04-16",
    createdAt: "2026-07-12T14:05:00.000Z"
  },
  {
    id: "generation-alpha-education-review-2024",
    kind: "article",
    sourceClass: "peer reviewed",
    title: "A Systematic Literature Review of Education for Generation Alpha",
    source: "Discover Education",
    url: "https://link.springer.com/article/10.1007/s44217-024-00218-3",
    summary: "PRISMA-based review of 83 studies covering teaching, tools, and blended learning for Generation Alpha.",
    tags: ["learn", "education", "systematic-review"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2024-08-09",
    createdAt: "2026-07-12T14:06:00.000Z"
  },
  {
    id: "digital-wellbeing-review-2025",
    kind: "article",
    sourceClass: "peer reviewed",
    title: "Digital Technology Use and Well-being in Young Children: A Systematic Review and Meta-analysis",
    source: "Computers in Human Behavior",
    url: "https://doi.org/10.1016/j.chb.2025.108660",
    summary: "Systematic review and meta-analysis of digital technology use and psychosocial well-being among children aged four to six.",
    tags: ["time", "wellbeing", "systematic-review"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2025-07-01",
    createdAt: "2026-07-12T14:07:00.000Z"
  },
  {
    id: "screen-socioemotional-review-2025",
    kind: "article",
    sourceClass: "peer reviewed",
    title: "Electronic Screen Use and Children's Socioemotional Problems: A Systematic Review and Meta-analysis of Longitudinal Studies",
    source: "Psychological Bulletin",
    url: "https://pubmed.ncbi.nlm.nih.gov/40489178/",
    summary: "Longitudinal evidence review that cautions against simple one-directional stories about screens and socioemotional outcomes.",
    tags: ["time", "wellbeing", "systematic-review"],
    status: "reviewed",
    confidence: "high",
    publishedAt: "2025-05-01",
    createdAt: "2026-07-12T14:08:00.000Z"
  },
  {
    id: "ap-sports-alpha-2026",
    kind: "article",
    sourceClass: "journalism",
    title: "Sports Leagues Race to Capture Gen Z and Gen Alpha with AI, Influencers and Italian Brainrot",
    source: "Associated Press",
    url: "https://apnews.com/article/62f54a8cd7748850e94470a814f8082e",
    summary: "Reported view of how sports organizations are adapting to creator-led and participatory youth culture.",
    tags: ["influence", "media", "creators"],
    status: "reviewed",
    confidence: "medium",
    publishedAt: "2026-02-10",
    createdAt: "2026-07-12T14:09:00.000Z"
  },
  {
    id: "common-sense-chatgpt-video",
    kind: "article",
    sourceClass: "video",
    title: "What Is ChatGPT?",
    source: "Common Sense Media",
    url: "https://www.commonsensemedia.org/videos/what-is-chatgpt",
    summary: "A short family-facing video on what ChatGPT does and how kids can use it responsibly.",
    tags: ["ai", "learn", "safety"],
    status: "reviewed",
    confidence: "medium",
    createdAt: "2026-07-12T14:10:00.000Z"
  },
  {
    id: "common-sense-media-youtube-2025",
    kind: "youtube",
    sourceClass: "youtube",
    title: "Media and Young Kids: New Research, Real Tips for Parents",
    source: "Common Sense Media",
    url: "https://www.youtube.com/watch?v=3mnan0zpxAo",
    summary: "Video briefing connected to Common Sense Media's 2025 census on young children's media use.",
    tags: ["youtube", "media", "family", "time"],
    status: "reviewed",
    confidence: "medium",
    publishedAt: "2025-04-01",
    createdAt: "2026-07-12T14:10:30.000Z"
  },
  {
    id: "reddit-genalpha-community-2024",
    kind: "field-note",
    sourceClass: "community",
    title: "Community discussion: differences Gen Alpha notices in its own online culture",
    source: "Reddit r/GenAlpha",
    url: "https://www.reddit.com/r/GenAlpha/comments/1at72w1/yes_im_gen_alpha/",
    summary: "Qualitative community material only; useful for vocabulary and hypotheses, never as representative evidence.",
    tags: ["community", "media", "language"],
    status: "queued",
    confidence: "low",
    createdAt: "2026-07-12T14:11:00.000Z"
  },
  {
    id: "owned-podcast-093",
    kind: "podcast",
    sourceClass: "owned",
    title: "#093 Gen Alpha: AI, Gaming, and the First Fully Digital Childhood",
    source: "Eclectic Polymath",
    url: "https://open.spotify.com/episode/7l1peATWasIYA07RvqKgwn?si=XGKqiaAJRAKCs2F4X3wn_g",
    summary: "Joshua's owned synthesis on how AI, gaming, and always-on media shape the first fully digital childhood.",
    synthesisStatus: "Featured synthesis",
    tags: ["owned", "ai", "gaming", "digital-childhood"],
    status: "queued",
    confidence: "low",
    createdAt: "2026-07-12T14:12:00.000Z"
  },
  {
    id: "future-report-alpha-mccrindle-2025",
    kind: "podcast",
    sourceClass: "podcast",
    title: "Inside the mind of Gen Alpha with Ashley Fell and Luke Davies",
    source: "The Future Report",
    url: "https://open.spotify.com/episode/5WPGgs3LmLOAkxww8NwsKS",
    summary: "McCrindle conversation useful for contrasting practitioner language with the lab's evidence-led findings.",
    tags: ["podcast", "mccrindle", "culture", "gen-alpha"],
    status: "queued",
    confidence: "medium",
    publishedAt: "2025-09-01",
    createdAt: "2026-07-12T14:12:30.000Z"
  },
  {
    id: "mccrindle-generation-alpha-book",
    kind: "book",
    sourceClass: "book",
    title: "Generation Alpha",
    source: "McCrindle",
    author: "Mark McCrindle and Ashley Fell",
    url: "https://mccrindle.com.au/resource/book/generation-alpha-book/",
    summary: "Book-length framing of Generation Alpha for parents, teachers, and leaders, including technology, education, consumer habits, and wellbeing.",
    tags: ["book", "generation-alpha", "education", "consumer-behavior"],
    status: "queued",
    confidence: "medium",
    publishedAt: "2021-04-01",
    createdAt: "2026-07-12T14:12:45.000Z"
  },
  {
    id: "field-cousin-placeholder",
    kind: "interview",
    sourceClass: "owned",
    title: "Interview slot: cousin media diary",
    source: "Field interview",
    summary: "Reserved place for a private interview about daily screens, games, AI, and household influence.",
    tags: ["interview", "media-diary", "family"],
    status: "new",
    confidence: "medium",
    createdAt: "2026-07-12T14:13:00.000Z"
  }
];

export const statusLabels: Record<ReviewStatus, string> = {
  new: "New",
  queued: "Queued",
  reviewed: "Reviewed"
};
