export type SpaceProfile = {
  id: string;
  name: string;
  category: string;
  audience: string;
  whatItIs: string;
  howTheyUseIt: string;
  behavior: string;
  implication: string;
  tone: "acid" | "cyan" | "coral" | "violet";
  sources: { label: string; url: string }[];
};

export const spaces: SpaceProfile[] = [
  { id: "roblox", name: "Roblox", category: "Participatory worlds", audience: "Core: 7-14", whatItIs: "A platform of user-created multiplayer games, social spaces, and persistent avatar identity.", howTheyUseIt: "They play with friends, customize avatars, follow trends, explore creator-built worlds, and increasingly treat the platform as a place rather than a single game.", behavior: "Play, make, socialize, collect", implication: "Participation is the value exchange. Give them something to do, shape, earn, or return to instead of only something to see.", tone: "acid", sources: [{ label: "Ofcom 2025", url: "https://www.ofcom.org.uk/media-use-and-attitudes/media-habits-children/children-and-parents-media-use-and-attitudes-report-2025--interactive-data?language=en" }, { label: "Roblox newsroom", url: "https://about.roblox.com/newsroom" }] },
  { id: "youtube", name: "YouTube", category: "Culture and utility", audience: "Core: 3-18", whatItIs: "A video ecosystem spanning long-form shows, Shorts, livestreams, music, tutorials, and creator fandom.", howTheyUseIt: "It is television, search engine, classroom, soundtrack, fandom hub, and the source of references that travel into games and friend groups.", behavior: "Watch, search, learn, follow", implication: "Utility and personality travel together. A useful repeatable format can carry more cultural weight than a conventional campaign message.", tone: "coral", sources: [{ label: "Pew 2024", url: "https://www.pewresearch.org/internet/2024/12/12/teens-social-media-and-technology-2024/" }, { label: "Common Sense 2025", url: "https://www.commonsensemedia.org/research/the-2025-common-sense-census-media-use-by-kids-zero-to-eight" }] },
  { id: "discord", name: "Discord", category: "Crew infrastructure", audience: "Core: older Alpha", whatItIs: "A server-based network for text, voice, video, and interest communities.", howTheyUseIt: "Older Gen Alpha coordinates game sessions, maintains smaller friend groups, follows community updates, and keeps conversation running after play ends.", behavior: "Coordinate, talk, belong", implication: "Meaningful social behavior is often crew-based and semi-private. Design for contribution and belonging, not reach alone.", tone: "violet", sources: [{ label: "Ofcom media lives", url: "https://www.ofcom.org.uk/siteassets/resources/documents/research-and-data/media-literacy-research/children/childrens-media-lives-2025/childrens-media-lives-2025-summary-report.pdf?v=396299" }, { label: "Discord Safety", url: "https://discord.com/safety" }] },
  { id: "tiktok", name: "TikTok", category: "Trend discovery", audience: "Core: older Alpha", whatItIs: "An algorithmic short-form video platform organized around sounds, creators, interests, and remixable formats.", howTheyUseIt: "Older members follow humor, music, products, creator formats, niche interests, and trends that quickly migrate into other spaces.", behavior: "Discover, remix, imitate", implication: "Culture arrives as a template to remake. Strong ideas invite a response, variation, or recognizable behavior.", tone: "cyan", sources: [{ label: "Pew 2026", url: "https://www.pewresearch.org/internet/2026/04/15/teens-experiences-on-tiktok-instagram-and-snapchat/" }] },
  { id: "minecraft", name: "Minecraft", category: "Open-ended creation", audience: "Core: 7-14", whatItIs: "A sandbox game and creative system centered on building, exploration, survival, and multiplayer worlds.", howTheyUseIt: "They build with friends, watch tutorials, use mods, collaborate on self-directed projects, and turn worlds into storytelling stages.", behavior: "Build, solve, collaborate", implication: "Creation is a social language. Tools and prompts that enable making can resonate more than a finished branded world.", tone: "acid", sources: [{ label: "UNICEF gaming", url: "https://www.unicef.org/innocenti/reports/protecting-children-online-gaming" }] },
  { id: "fortnite", name: "Fortnite", category: "Live social play", audience: "Core: 10-17", whatItIs: "A multiplayer game, creator ecosystem, and live-event platform with a persistent culture around play.", howTheyUseIt: "Friends meet for synchronized sessions, play user-made modes, attend events, and use the game as a recurring social rendezvous.", behavior: "Compete, gather, attend", implication: "Social time is ritualized and synchronous. Shared missions, timed drops, and live moments fit better than static placement.", tone: "coral", sources: [{ label: "Pew gaming 2024", url: "https://www.pewresearch.org/internet/2024/05/09/teens-and-video-games-today/" }] },
  { id: "snapchat", name: "Snapchat", category: "Friend maintenance", audience: "Core: older Alpha", whatItIs: "A private visual messaging network built around direct exchange, group chat, and lightweight posting.", howTheyUseIt: "They maintain frequent low-polish contact through photos, messages, streaks, group chat, and quick updates between close friends.", behavior: "Message, maintain, signal", implication: "This is relationship maintenance, not a broadcast stage. Any brand behavior must respect the friends-first context.", tone: "cyan", sources: [{ label: "Pew 2026", url: "https://www.pewresearch.org/internet/2026/04/15/teens-experiences-on-tiktok-instagram-and-snapchat/" }] },
  { id: "instagram", name: "Instagram", category: "Identity and aspiration", audience: "Core: older Alpha", whatItIs: "A visual social network spanning Reels, creators, DMs, profiles, and interest communities.", howTheyUseIt: "As identity becomes more salient, older Gen Alpha follows creators, curates a public self, shares in DMs, and tracks style and aspiration.", behavior: "Curate, follow, affiliate", implication: "Visual identity systems matter. Collectability, affiliation, and social proof are stronger than one isolated post.", tone: "violet", sources: [{ label: "Pew 2024", url: "https://www.pewresearch.org/internet/2024/12/12/teens-social-media-and-technology-2024/" }] },
  { id: "twitch", name: "Twitch", category: "Participatory viewing", audience: "Core: 12-18", whatItIs: "A livestreaming platform centered on gaming, creators, events, and real-time chat.", howTheyUseIt: "They watch play, commentary, esports, and creator communities while chat turns viewing into a shared live experience.", behavior: "Watch, react, co-create", implication: "Watching together is participatory when chat, recognition, and collective reaction are part of the format.", tone: "coral", sources: [{ label: "Pew gaming 2024", url: "https://www.pewresearch.org/internet/2024/05/09/teens-and-video-games-today/" }] },
  { id: "whatsapp", name: "WhatsApp", category: "Private networks", audience: "Varies by household", whatItIs: "A private messaging and calling service that anchors family, school, community, and friend groups.", howTheyUseIt: "Its role varies by culture and household, but it often carries family communication, coordination, group calls, and peer conversation.", behavior: "Coordinate, call, share", implication: "Youth behavior does not live in one universal social graph. Family-linked private networks can be culturally central.", tone: "acid", sources: [{ label: "Pew platform chart", url: "https://www.pewresearch.org/chart/most-common-online-platforms-among-teens/" }] },
  { id: "reddit", name: "Reddit", category: "Niche sense-making", audience: "Watchlist: older Alpha", whatItIs: "A topic-led community network organized around questions, fandoms, interests, and candid discussion.", howTheyUseIt: "For the older edge of the cohort it can surface niche language, peer advice, fandom debates, and problem-solving outside polished feeds.", behavior: "Ask, compare, investigate", implication: "Treat it as a watchlist, not a core under-13 channel. It reveals where candid language and niche needs take shape.", tone: "violet", sources: [{ label: "Pew social facts", url: "https://www.pewresearch.org/short-reads/2025/07/10/10-facts-about-teens-and-social-media/" }] },
  { id: "capcut", name: "CapCut", category: "Remix toolkit", audience: "Core: older Alpha", whatItIs: "A mobile-first video editor built around templates, sounds, effects, captions, and social publishing workflows.", howTheyUseIt: "It turns trend consumption into making through reusable edits, templates, sounds, transitions, and shareable short-form video.", behavior: "Edit, remix, publish", implication: "The line between audience and maker is thin. Creative templates and remix permissions are strategic product features.", tone: "cyan", sources: [{ label: "Ofcom Online Nation", url: "https://www.ofcom.org.uk/__data/assets/pdf_file/0029/272288/online-nation-2023-report.pdf" }] }
];
