import { sources } from "./sources";
import type { EvidenceClaimKind, EvidenceItem, EvidenceType, Insight, Theme } from "./types";

export const themes: Theme[] = [
  { id: "play-belonging", title: "Play & Belonging", description: "Social play, identity, family participation, and safety." },
  { id: "media-influence", title: "Media & Influence", description: "Video, creators, culture, household influence, and discovery." },
  { id: "time-routines", title: "Time & Routines", description: "Daily media rhythms, device access, and household context." },
  { id: "learning-becoming", title: "Learning & Becoming", description: "Learning, creativity, AI, literacy, and self-directed growth." },
];

type InsightSeed = Pick<Insight, "id" | "themeId" | "sequence" | "title" | "thesis" | "tags"> & {
  sourceIds: [string, string];
};

const insightSeeds: InsightSeed[] = [
  { id: "play-social-infrastructure", themeId: "play-belonging", sequence: 1, title: "Play is social infrastructure.", thesis: "Shared activity gives friendship a durable place to happen.", tags: ["play", "belonging"], sourceIds: ["walton-creation-gaming-2024", "ofcom-children-media-lives-2025"] },
  { id: "play-making-interface", themeId: "play-belonging", sequence: 2, title: "Playing and making increasingly share the same interface.", thesis: "Creation tools make participation part of play.", tags: ["play", "creation"], sourceIds: ["walton-creation-gaming-2024", "roblox-search-style-trends-2025"] },
  { id: "play-friendship-travels", themeId: "play-belonging", sequence: 3, title: "Friendship travels between games, chat, video, and real life.", thesis: "Relationships move across connected activities.", tags: ["friendship", "spaces"], sourceIds: ["ofcom-children-media-lives-2025", "pew-teens-video-games-2024"] },
  { id: "play-avatars-identity", themeId: "play-belonging", sequence: 4, title: "Avatars are rehearsal spaces for identity.", thesis: "Digital expression lets young people try style and social signals.", tags: ["identity", "avatars"], sourceIds: ["roblox-search-style-trends-2025", "ofcom-children-media-lives-2025"] },
  { id: "play-small-crews", themeId: "play-belonging", sequence: 5, title: "Small crews matter more than public follower counts.", thesis: "Repeated shared activity can matter more than broadcast reach.", tags: ["friendship", "groups"], sourceIds: ["ofcom-children-media-lives-2025", "pew-teens-video-games-2024"] },
  { id: "play-competition-performance", themeId: "play-belonging", sequence: 6, title: "Competition is also performance and storytelling.", thesis: "Games can be watched, narrated, and shared alongside being played.", tags: ["competition", "media"], sourceIds: ["pew-teens-video-games-2024", "ap-sports-alpha-2026"] },
  { id: "play-status-contribution", themeId: "play-belonging", sequence: 7, title: "Digital status is built through fluency, objects, and contribution.", thesis: "Contribution and cultural fluency can signal belonging in shared worlds.", tags: ["identity", "participation"], sourceIds: ["roblox-search-style-trends-2025", "walton-creation-gaming-2024"] },
  { id: "play-family-coplay", themeId: "play-belonging", sequence: 8, title: "Households set the conditions around play.", thesis: "Access, permission, and payment keep play embedded in family systems.", tags: ["family", "play"], sourceIds: ["common-sense-census-2025", "pwc-alpha-2026"] },
  { id: "play-offline-rebound", themeId: "play-belonging", sequence: 9, title: "Offline play is rebounding rather than disappearing.", thesis: "Digital and offline activity should be studied together.", tags: ["offline", "play"], sourceIds: ["project-play-state-of-play-2025", "outdoor-participation-trends-2026"] },
  { id: "play-safety-boundaries", themeId: "play-belonging", sequence: 10, title: "Safety boundaries are part of the play experience.", thesis: "Child-centered game participation requires safety by design.", tags: ["safety", "play"], sourceIds: ["unicef-online-gaming", "ftc-coppa-2025"] },
  { id: "media-video-default", themeId: "media-influence", sequence: 1, title: "Video is the default entertainment and explanation layer.", thesis: "Video is used for entertainment and everyday explanation.", tags: ["video", "media"], sourceIds: ["common-sense-census-2025", "ofcom-children-media-lives-2025"] },
  { id: "media-short-form-shape", themeId: "media-influence", sequence: 2, title: "Short-form changes the shape of attention, not only its duration.", thesis: "Format and context matter alongside time spent.", tags: ["short-form", "attention"], sourceIds: ["common-sense-census-2025", "pew-teens-social-2024"] },
  { id: "media-creators-templates", themeId: "media-influence", sequence: 3, title: "Creators act as behavioral templates.", thesis: "Creators can make formats and behavior visible for imitation.", tags: ["creators", "influence"], sourceIds: ["ap-sports-alpha-2026", "emarketer-alpha-faq-2026"] },
  { id: "media-household-negotiation", themeId: "media-influence", sequence: 4, title: "Influence is negotiated inside the household.", thesis: "Interest, permission, and purchase often involve adults.", tags: ["family", "commerce"], sourceIds: ["pwc-alpha-2026", "gwi-alpha-unfiltered"] },
  { id: "media-discovery-commerce", themeId: "media-influence", sequence: 5, title: "Discovery and commerce increasingly share the same surface.", thesis: "Discovery formats can connect interest with household decisions.", tags: ["discovery", "commerce"], sourceIds: ["pwc-alpha-2026", "emarketer-alpha-faq-2026"] },
  { id: "media-repeatable-formats", themeId: "media-influence", sequence: 6, title: "Culture moves through repeatable formats more than fixed channels.", thesis: "Cultural participation can travel across platforms and formats.", tags: ["culture", "formats"], sourceIds: ["ap-sports-alpha-2026", "ofcom-children-media-lives-2025"] },
  { id: "media-properties-travel", themeId: "media-influence", sequence: 7, title: "Entertainment properties travel through music, games, products, and memes.", thesis: "Youth culture crosses media, play, and commercial environments.", tags: ["culture", "franchises"], sourceIds: ["ap-sports-alpha-2026", "emarketer-alpha-habits-2026"] },
  { id: "media-coviewing", themeId: "media-influence", sequence: 8, title: "Media influence is negotiated at household scale.", thesis: "Children's media interests move through family routines and adult review.", tags: ["family", "video"], sourceIds: ["common-sense-census-2025", "pwc-alpha-2026"] },
  { id: "media-ai-recommendation", themeId: "media-influence", sequence: 9, title: "AI is entering entertainment search and recommendation.", thesis: "Conversational discovery changes how entertainment can be found and evaluated.", tags: ["ai", "discovery"], sourceIds: ["nielsen-ai-discovery-2026", "razorfish-alpha-ai"] },
  { id: "media-reach-risk", themeId: "media-influence", sequence: 10, title: "Reach, persuasion, and safety risk coexist in the same feeds.", thesis: "Participation environments need responsible safeguards alongside reach planning.", tags: ["safety", "media"], sourceIds: ["arxiv-young-user-safety-2025", "ftc-coppa-2025"] },
  { id: "time-screen-purpose", themeId: "time-routines", sequence: 1, title: "Total screen time hides a major shift in what screens are for.", thesis: "Context and activity matter alongside duration.", tags: ["time", "context"], sourceIds: ["digital-wellbeing-review-2025", "common-sense-census-2025"] },
  { id: "time-device-access", themeId: "time-routines", sequence: 2, title: "Personal device access begins before personal independence.", thesis: "Device access occurs inside family rules and developmental context.", tags: ["devices", "family"], sourceIds: ["common-sense-census-2025", "pew-teens-social-2024"] },
  { id: "time-youtube-rhythm", themeId: "time-routines", sequence: 3, title: "YouTube is embedded in the daily household rhythm.", thesis: "Video is a recurring part of young children's media environments.", tags: ["youtube", "routines"], sourceIds: ["common-sense-census-2025", "pew-teens-social-2024"] },
  { id: "time-parent-context", themeId: "time-routines", sequence: 4, title: "Parents manage context and rules, not only minutes.", thesis: "Household management includes content, setting, and permission.", tags: ["parents", "safety"], sourceIds: ["common-sense-census-2025", "unicef-online-gaming"] },
  { id: "time-family-needs", themeId: "time-routines", sequence: 5, title: "Screens fill practical family needs as well as entertainment needs.", thesis: "Media can be woven into routines, care, and learning.", tags: ["family", "media"], sourceIds: ["common-sense-census-2025", "aecf-generation-alpha"] },
  { id: "time-age-change", themeId: "time-routines", sequence: 6, title: "Digital routines change quickly with age.", thesis: "Age should remain explicit when interpreting media patterns.", tags: ["age", "routines"], sourceIds: ["common-sense-census-2025", "pew-teens-social-2024"] },
  { id: "time-nighttime-use", themeId: "time-routines", sequence: 7, title: "Nighttime use is part of the real media day.", thesis: "The daily media environment extends beyond a single daytime measure.", tags: ["routines", "time"], sourceIds: ["bedtime-screen-early-adolescents-2024", "prebed-screen-young-children-2021"] },
  { id: "time-coexistence", themeId: "time-routines", sequence: 8, title: "Online and offline activities coexist rather than cancel each other out.", thesis: "Digital activity needs to be considered with, not apart from, offline life.", tags: ["offline", "context"], sourceIds: ["screen-socioemotional-review-2025", "ofcom-children-media-lives-2025"] },
  { id: "time-private-day", themeId: "time-routines", sequence: 9, title: "Personal devices widen the private media day.", thesis: "Personal access changes where and how media can be used.", tags: ["devices", "privacy"], sourceIds: ["pew-teens-social-2024", "common-sense-census-2025"] },
  { id: "time-household-context", themeId: "time-routines", sequence: 10, title: "Income and household context shape access and use.", thesis: "Access and use should not be treated as uniform across families.", tags: ["equity", "family"], sourceIds: ["aecf-generation-alpha", "common-sense-census-2025"] },
  { id: "learning-assembled", themeId: "learning-becoming", sequence: 1, title: "Learning is assembled on demand across multiple environments.", thesis: "Learning can span school, video, play, search, and family support.", tags: ["learning", "spaces"], sourceIds: ["generation-alpha-education-review-2024", "ofcom-children-media-lives-2025"] },
  { id: "learning-creation-skills", themeId: "learning-becoming", sequence: 2, title: "Creation games are perceived as places to learn real skills.", thesis: "Creation-gaming environments can support making and social learning.", tags: ["learning", "games"], sourceIds: ["walton-creation-gaming-2024", "generation-alpha-education-review-2024"] },
  { id: "learning-ai-homework", themeId: "learning-becoming", sequence: 3, title: "AI is already part of homework and explanation.", thesis: "AI is appearing in youth learning and explanation contexts.", tags: ["ai", "learning"], sourceIds: ["common-sense-ai-2026", "common-sense-chatgpt-video"] },
  { id: "learning-ai-discovery", themeId: "learning-becoming", sequence: 4, title: "AI use extends beyond schoolwork into discovery, creativity, and support.", thesis: "AI use spans discovery, creativity, and everyday support contexts.", tags: ["ai", "creativity"], sourceIds: ["razorfish-alpha-ai", "nielsen-ai-discovery-2026"] },
  { id: "learning-safety-guidance", themeId: "learning-becoming", sequence: 5, title: "Safety guidance is lagging behind AI adoption.", thesis: "Family guidance and privacy safeguards remain necessary around AI use.", tags: ["ai", "safety"], sourceIds: ["common-sense-ai-2026", "ftc-coppa-2025"] },
  { id: "learning-verification", themeId: "learning-becoming", sequence: 6, title: "Verification is becoming a core literacy.", thesis: "Trust and checking matter when systems recommend and answer.", tags: ["ai", "literacy"], sourceIds: ["nielsen-ai-discovery-2026", "common-sense-chatgpt-video"] },
  { id: "learning-enablement", themeId: "learning-becoming", sequence: 7, title: "Technology matters for what it enables, not for the hardware itself.", thesis: "The learning value of technology depends on activity and setting.", tags: ["learning", "technology"], sourceIds: ["generation-alpha-education-review-2024", "digital-wellbeing-review-2025"] },
  { id: "learning-remix", themeId: "learning-becoming", sequence: 8, title: "Creative identity grows through iteration and remix.", thesis: "Creation environments give young people opportunities to make and revise.", tags: ["creation", "identity"], sourceIds: ["walton-creation-gaming-2024", "roblox-search-style-trends-2025"] },
  { id: "learning-commercial-fluency", themeId: "learning-becoming", sequence: 9, title: "Commercial fluency begins as a form of practical learning.", thesis: "Household influence and brands are part of young people's practical media environment.", tags: ["commerce", "learning"], sourceIds: ["pwc-alpha-2026", "razorfish-alpha-industries"] },
  { id: "learning-multimodal", themeId: "learning-becoming", sequence: 10, title: "Becoming is multimodal, self-directed, and socially coached.", thesis: "Learning and identity develop across social, creative, and educational contexts.", tags: ["learning", "identity"], sourceIds: ["generation-alpha-education-review-2024", "walton-creation-gaming-2024"] },
];

const sourceById = new Map(sources.map((item) => [item.id, item]));

type ExtractedFact = {
  insightId: string;
  slot: 1 | 2;
  sourceId: string;
  claim: string;
  locator: string;
  evidenceType: EvidenceType;
};

const fact = (
  insightId: string,
  slot: 1 | 2,
  sourceId: string,
  claim: string,
  locator: string,
  evidenceType: EvidenceType,
): ExtractedFact => ({ insightId, slot, sourceId, claim, locator, evidenceType });

const extractedFacts: ExtractedFact[] = [
  fact("play-social-infrastructure", 1, "pew-teens-video-games-2024", "Forty-seven percent of teen video-game players said gaming helped their friendships, and 47% had made an online friend through a game.", "Socializing over video games section, findings paragraphs.", "self-reported"),
  fact("play-social-infrastructure", 2, "walton-creation-gaming-2024", "Children said Roblox and Minecraft help them practice creativity and problem-solving, while expert interviews emphasized team-based social learning.", "Key Findings section, cognitive development finding and expert interview paragraph.", "self-reported"),
  fact("play-making-interface", 1, "walton-creation-gaming-2024", "At least seven in ten children wanted to learn subjects such as coding, art, or design inside Roblox or Minecraft.", "Key Findings section, formal education finding.", "self-reported"),
  fact("play-making-interface", 2, "roblox-search-style-trends-2025", "Roblox's first-party trend data linked what users searched for with the avatar styles they adopted inside experiences, making discovery part of creation and play.", "Search and style trends section, platform findings.", "editorial inference"),
  fact("play-friendship-travels", 1, "pew-teens-video-games-2024", "Most teen players gamed with other people, and 40% of all U.S. teens had made an online friend through a shared game.", "Socializing over video games section, findings paragraphs.", "self-reported"),
  fact("play-friendship-travels", 2, "ofcom-children-media-lives-2025", "Ofcom's case studies observed children carrying shared interests between games, messaging, video, and in-person friend groups.", "Summary report, friendships and communication findings section.", "qualitative"),
  fact("play-avatars-identity", 1, "roblox-search-style-trends-2025", "Platform search and style patterns showed avatar appearance moving with named aesthetics and cultural trends inside Roblox experiences.", "Avatar style trends section, platform findings.", "platform-wide metric"),
  fact("play-avatars-identity", 2, "razorfish-alpha-industries", "Eighty percent of Alpha girls had used a filter or retouching app, while 63% wanted more inclusive representation in media.", "Industry findings section, beauty and representation paragraph.", "self-reported"),
  fact("play-small-crews", 1, "pew-teens-video-games-2024", "Ninety-eight percent of self-identified teen gamers played with others, and 68% had made a friend online through a game.", "Socializing over video games section, gamer comparison paragraph.", "self-reported"),
  fact("play-small-crews", 2, "ofcom-children-media-lives-2025", "Ofcom's longitudinal cases showed small friend groups using games and private messages as recurring places to coordinate and stay connected.", "Summary report, friend-group routines findings section.", "qualitative"),
  fact("play-competition-performance", 1, "pew-teens-video-games-2024", "About four in ten U.S. teens played video games daily, including 23% who played several times a day.", "Who plays video games section, frequency paragraph.", "self-reported"),
  fact("play-competition-performance", 2, "ap-sports-alpha-2026", "The NBA and NHL partnered directly with young creators to reach younger fans, and the NBA used AI to identify potential partners.", "Article opening paragraphs on league creator partnerships.", "observed"),
  fact("play-status-contribution", 1, "roblox-search-style-trends-2025", "Roblox's platform findings treated avatar style and search fluency as visible participation patterns inside user-created experiences.", "Search and avatar style findings section.", "editorial inference"),
  fact("play-status-contribution", 2, "walton-creation-gaming-2024", "Players named creativity and problem-solving among the skills they actively learn while building in Roblox and Minecraft.", "Key Findings section, cognitive development paragraph.", "self-reported"),
  fact("play-family-coplay", 1, "common-sense-census-2025", "Forty percent of children had a tablet by age two and nearly one in four had a personal cellphone by age eight, showing that early access is household-enabled.", "Key findings paragraph, device ownership metrics.", "self-reported"),
  fact("play-family-coplay", 2, "pwc-alpha-2026", "Sixty percent of children said an adult pays when they buy something, even as children exercise growing choice over digital and physical purchases.", "Following the money section, payment-method findings.", "self-reported"),
  fact("play-offline-rebound", 1, "project-play-state-of-play-2025", "Organized-sport participation among U.S. youth ages 6-17 increased from 53.8% in 2022 to 55.4% in 2023, followed by a separate 6% one-year participation uptick in 2024; this is a directional inference that one form of offline play rebounded.", "Introduction, Government Data and Industry Data paragraphs.", "editorial inference"),
  fact("play-offline-rebound", 2, "outdoor-participation-trends-2026", "Outdoor participation among U.S. children ages 6-12 grew 5% to 22.6 million in the 2025 annual wave; this is a directional inference that another form of offline recreation gained participants.", "Executive summary, key trends list, children ages 6 to 12 finding.", "editorial inference"),
  fact("play-safety-boundaries", 1, "unicef-online-gaming", "UNICEF concludes that child safety, privacy, and rights protections must be built into online-game design rather than left only to parental monitoring.", "Report recommendations section on safety by design.", "qualitative"),
  fact("play-safety-boundaries", 2, "ftc-coppa-2025", "The revised COPPA rule requires separate parental opt-in before children's data can be disclosed for targeted advertising and limits indefinite data retention.", "FTC release, final-rule changes paragraphs.", "observed"),
  fact("media-video-default", 1, "common-sense-census-2025", "Children zero to eight averaged about 2.5 hours of screen media a day while short-form services including YouTube Shorts grew.", "Key findings paragraph, daily time and short-form video findings.", "self-reported"),
  fact("media-video-default", 2, "pwc-alpha-2026", "Sixty-eight percent of children ages seven to fourteen said they use YouTube regularly, ahead of gaming platforms at 54% and streaming services at 49%.", "Digital influence section, platform-use findings paragraph.", "self-reported"),
  fact("media-short-form-shape", 1, "common-sense-census-2025", "Total daily screen time held near 2.5 hours while traditional TV declined and TikTok and YouTube Shorts rose, indicating a format shift within stable time.", "Key findings paragraph, changing media mix.", "self-reported"),
  fact("media-short-form-shape", 2, "pew-teens-social-2024", "About six in ten U.S. teens ages 13 to 17 said they visited TikTok daily, including 16% who reported being on it almost constantly.", "How often do teens visit online platforms section, TikTok frequency paragraphs.", "self-reported"),
  fact("media-creators-templates", 1, "ap-sports-alpha-2026", "Major leagues partnered with young creators to translate sports into the formats and language younger audiences already follow.", "Article opening paragraphs on NBA and NHL creator partnerships.", "observed"),
  fact("media-creators-templates", 2, "pwc-alpha-2026", "Sixty-one percent of Gen Alpha respondents said social media makes them want to buy something, exceeding reported peer influence at 56%.", "Digital influence section, purchase-motivation findings.", "self-reported"),
  fact("media-household-negotiation", 1, "pwc-alpha-2026", "Children reported more independent ordering than parents recognized: 25% cited food-delivery apps versus 14% of parents, an 11-point gap.", "Independence gap section, child-parent comparison paragraph.", "self-reported"),
  fact("media-household-negotiation", 2, "razorfish-alpha-industries", "Sixty-one percent of parents said their child strongly influences family food choices, and 61% said children have final say on the family car.", "Industry findings section, household influence paragraph.", "self-reported"),
  fact("media-discovery-commerce", 1, "pwc-alpha-2026", "Sixty-one percent of children pointed to social media as a purchase trigger, while 68% used YouTube regularly and 54% used gaming platforms.", "Digital influence section, discovery and platform findings.", "self-reported"),
  fact("media-discovery-commerce", 2, "razorfish-alpha-industries", "Seventy-five percent were interested in beauty content on social media and 38% already made their own content.", "Industry findings section, social beauty paragraph.", "self-reported"),
  fact("media-repeatable-formats", 1, "ap-sports-alpha-2026", "Sports leagues used recurring creator partnerships, AI-assisted partner discovery, and youth-native meme formats to maintain relevance.", "Article body section on league youth-engagement formats.", "observed"),
  fact("media-repeatable-formats", 2, "razorfish-alpha-industries", "Thirty-eight percent of Alphas interested in beauty content said they already create content themselves, showing formats travel through imitation and making.", "Industry findings section, social beauty paragraph.", "self-reported"),
  fact("media-properties-travel", 1, "ap-sports-alpha-2026", "The NBA and NHL extended league culture through creators and social formats rather than relying only on live games and broadcasts.", "Article opening and league examples section.", "observed"),
  fact("media-properties-travel", 2, "pwc-alpha-2026", "Regular use crossed YouTube (68%), gaming platforms (54%), and streaming services (49%), giving entertainment properties multiple routes into children's attention.", "Digital influence section, platform-use findings.", "editorial inference"),
  fact("media-coviewing", 1, "pwc-alpha-2026", "Fifty-two percent of children added products to shared online carts for parental review before checkout.", "Independence gap section, shared-cart finding.", "self-reported"),
  fact("media-coviewing", 2, "common-sense-census-2025", "Young children's daily media time stayed near 2.5 hours as parents navigated a mix shifting toward games and short-form video.", "Key findings and family-guidance paragraphs.", "editorial inference"),
  fact("media-ai-recommendation", 1, "nielsen-ai-discovery-2026", "Forty-nine percent of Gen Alpha respondents chose AI chatbots as the best source for TV and movie recommendations, versus 41% for service guides and 11% for search results.", "News release, entertainment recommendation findings paragraph.", "self-reported"),
  fact("media-ai-recommendation", 2, "razorfish-alpha-ai", "Twenty-two percent of Alphas used AI daily and 12% used it several times a day, with fun and hobbies among the leading uses.", "AI day-to-day tool findings paragraph.", "self-reported"),
  fact("media-reach-risk", 1, "arxiv-young-user-safety-2025", "Fifteen percent of YouTube recommendations to age-13 accounts were rated harmful versus 8.17% for adult accounts, appearing after an average 3:06 of passive scrolling.", "Abstract, harmful recommendation findings.", "observed"),
  fact("media-reach-risk", 2, "ftc-coppa-2025", "The FTC barred covered services from conditioning participation on unnecessary data collection and required opt-in consent for targeted-advertising disclosures.", "FTC release, final-rule protections paragraphs.", "observed"),
  fact("time-screen-purpose", 1, "common-sense-census-2025", "Screen time remained near 2.5 hours daily while gaming rose 65% in four years, traditional TV declined, and short-form video grew.", "Key findings paragraph, time-use changes.", "self-reported"),
  fact("time-screen-purpose", 2, "screen-socioemotional-review-2025", "Longitudinal effects ran both ways and were small overall; the authors recommended emphasizing content quality and social interaction, not minutes alone.", "Abstract, bidirectional results and guidance conclusion.", "observed"),
  fact("time-device-access", 1, "common-sense-census-2025", "Forty percent of children had a tablet by age two, and nearly one in four had a personal cellphone by age eight.", "Key findings paragraph, device-access metrics.", "self-reported"),
  fact("time-device-access", 2, "pwc-alpha-2026", "Seventy percent owned a tablet and 72% used smartphones regularly; smartphone ownership rose from 46% at ages seven to nine to 89% at ages thirteen to fourteen.", "Digital world section, device ownership findings.", "self-reported"),
  fact("time-youtube-rhythm", 1, "common-sense-census-2025", "Children averaged about 2.5 hours of screen media every day as YouTube Shorts and other short-form video became a growing part of that routine.", "Key findings paragraph, daily media time and YouTube Shorts trend.", "self-reported"),
  fact("time-youtube-rhythm", 2, "pew-teens-social-2024", "Seventy-three percent of U.S. teens visited YouTube daily, including 15% who said their use was almost constant.", "How often teens visit platforms section, YouTube frequency paragraph.", "self-reported"),
  fact("time-parent-context", 1, "common-sense-ai-2026", "More than four in ten children said no parent or guardian had ever discussed AI safety with them.", "Opening findings paragraph, parent-guidance metric.", "self-reported"),
  fact("time-parent-context", 2, "ftc-coppa-2025", "COPPA's revised rule requires parents to opt in before covered services disclose children's data for targeted advertising.", "FTC release, parental consent paragraph.", "observed"),
  fact("time-family-needs", 1, "common-sense-census-2025", "Tablet access reached 40% by age two while average daily media use held near 2.5 hours, showing screens are integrated into early household routines.", "Key findings paragraph, device and daily-use metrics.", "editorial inference"),
  fact("time-family-needs", 2, "pwc-alpha-2026", "Sixty percent of children said an adult pays when they make purchases, illustrating that growing digital independence still relies on family infrastructure.", "Following the money section, payment findings.", "editorial inference"),
  fact("time-age-change", 1, "common-sense-census-2025", "Tablet ownership reached 40% by age two, while nearly one in four children had a personal cellphone by age eight.", "Key findings paragraph, age-based access metrics.", "self-reported"),
  fact("time-age-change", 2, "pwc-alpha-2026", "Smartphone ownership increased from 46% among seven- to nine-year-olds to 89% among thirteen- to fourteen-year-olds.", "Digital world section, age comparison paragraph.", "self-reported"),
  fact("time-nighttime-use", 1, "bedtime-screen-early-adolescents-2024", "Early adolescents who left their phone ringer activated overnight had greater odds of sleep disturbance and shorter sleep one year later than peers who turned phones off at bedtime; bedtime social media, texting, and music use showed the same direction.", "Abstract, Results paragraph.", "self-reported"),
  fact("time-nighttime-use", 2, "prebed-screen-young-children-2021", "Among 30-month-olds, greater screen use before bedtime or during the nightly bedtime routine was associated with more sleep problems; more frequent routine use was also associated with later, shorter, and more variable sleep by actigraphy.", "Abstract, findings paragraph.", "observed"),
  fact("time-coexistence", 1, "screen-socioemotional-review-2025", "The meta-analysis found small reciprocal associations between screen use and socioemotional problems and urged attention to content and social context.", "Abstract, bidirectional results and conclusion.", "observed"),
  fact("time-coexistence", 2, "razorfish-alpha-industries", "Sixty-six percent would pay more for something usable only in real life, twice the share preferring something solely online.", "Industry findings section, real-world experience paragraph.", "self-reported"),
  fact("time-private-day", 1, "pew-teens-social-2024", "Ninety-five percent of teens had smartphone access and 46% described being online almost constantly.", "Device access and internet frequency sections.", "self-reported"),
  fact("time-private-day", 2, "pwc-alpha-2026", "Seventy-two percent used smartphones regularly, and smartphone ownership reached 89% among thirteen- to fourteen-year-olds.", "Digital world section, device findings.", "self-reported"),
  fact("time-household-context", 1, "pew-teens-video-games-2024", "Daily gaming varied by household income: 53% below $30,000, 42% from $30,000 to $74,999, and 39% at $75,000 or more.", "Who plays video games section, household-income paragraph.", "self-reported"),
  fact("time-household-context", 2, "pwc-alpha-2026", "Adults paid for children's purchases in 60% of cases, while access and ownership rose sharply with age.", "Following the money and digital world sections.", "editorial inference"),
  fact("learning-assembled", 1, "generation-alpha-education-review-2024", "Across 83 studies, no digital educational tool or online strategy emerged as dominant, despite many approaches being tested.", "Abstract, synthesis findings paragraph.", "observed"),
  fact("learning-assembled", 2, "walton-creation-gaming-2024", "Expert interviews observed children seeking explanations across YouTube, TikTok, and Minecraft when school instruction left gaps.", "Report analysis section, expert interview paragraph on self-directed learning.", "qualitative"),
  fact("learning-creation-skills", 1, "walton-creation-gaming-2024", "Children identified creativity and problem-solving as skills learned through Roblox and Minecraft, and at least seven in ten wanted curriculum subjects taught there.", "Key Findings section, skills and formal education findings.", "self-reported"),
  fact("learning-creation-skills", 2, "razorfish-alpha-industries", "Thirty-eight percent of Alphas interested in beauty content said they already create their own content.", "Industry findings section, social beauty paragraph.", "self-reported"),
  fact("learning-ai-homework", 1, "common-sense-ai-2026", "More than eight in ten AI users used it for entertainment and homework help; over half of children struggling to focus used AI for schoolwork weekly.", "Opening findings and key findings section, schoolwork paragraphs.", "self-reported"),
  fact("learning-ai-homework", 2, "razorfish-alpha-ai", "Homework was the leading reported AI use at 53%, followed by fun or hobbies at 43% and use at school at 36%.", "AI day-to-day tool findings paragraph.", "self-reported"),
  fact("learning-ai-discovery", 1, "razorfish-alpha-ai", "Twenty-two percent used AI daily, with homework, hobbies, and school spanning instrumental and creative use.", "AI day-to-day tool findings paragraph.", "self-reported"),
  fact("learning-ai-discovery", 2, "nielsen-ai-discovery-2026", "Eighty percent of Gen Alpha respondents increased chatbot use in the prior 12 to 18 months, and more than half used chatbots daily.", "News release, chatbot adoption findings paragraph.", "self-reported"),
  fact("learning-safety-guidance", 1, "common-sense-ai-2026", "More than four in ten had never discussed AI safety with a parent, and only just over half had been taught safe AI use at school.", "Opening findings and key findings section, safety-guidance paragraphs.", "self-reported"),
  fact("learning-safety-guidance", 2, "razorfish-alpha-ai", "Parents' leading AI concerns included age-inappropriate content at 57%, reduced critical thinking at 56%, and misinformation at 53%.", "Parents and AI findings paragraph.", "self-reported"),
  fact("learning-verification", 1, "nielsen-ai-discovery-2026", "Three in four respondents verified chatbot answers, while traditional search led AI on trustworthiness by 50% to 27%.", "News release, trust and verification findings paragraphs.", "self-reported"),
  fact("learning-verification", 2, "common-sense-ai-2026", "Only one-third of children knew that AI cannot reliably distinguish fact from fiction.", "Key findings section, AI capability literacy paragraph.", "self-reported"),
  fact("learning-enablement", 1, "generation-alpha-education-review-2024", "The systematic review found many digital tools and online strategies under development, but no dominant approach and little evidence of true cohort differences.", "Abstract, synthesis findings and limitations paragraph.", "observed"),
  fact("learning-enablement", 2, "walton-creation-gaming-2024", "At least seven in ten children wanted to learn coding, art, or design through Roblox or Minecraft, tying value to enabled activity rather than hardware.", "Key Findings section, formal education finding.", "editorial inference"),
  fact("learning-remix", 1, "walton-creation-gaming-2024", "Children said building in Roblox and Minecraft develops creativity and problem-solving through active making.", "Key Findings section, cognitive development paragraph.", "self-reported"),
  fact("learning-remix", 2, "razorfish-alpha-industries", "Thirty-eight percent of Alphas interested in beauty media made content themselves, turning consumption into iterative self-presentation.", "Industry findings section, social beauty paragraph.", "editorial inference"),
  fact("learning-commercial-fluency", 1, "pwc-alpha-2026", "Ninety-seven percent said they make purchase decisions independently at least sometimes, and 61% used wish lists to plan requests.", "Opening findings and pint-sized negotiators section.", "self-reported"),
  fact("learning-commercial-fluency", 2, "razorfish-alpha-industries", "Children influenced household categories from food to cars, while two in three valued physical-only experiences over digital-only ones.", "Industry findings section, household influence and in-person experience paragraphs.", "self-reported"),
  fact("learning-multimodal", 1, "pwc-alpha-2026", "Children moved among touch, typing, and voice: 58% tapped or swiped, 50% typed, and 48% used voice commands.", "Digital world section, interaction-mode findings.", "self-reported"),
  fact("learning-multimodal", 2, "walton-creation-gaming-2024", "Children sought knowledge through YouTube, TikTok, and Minecraft and reported learning creativity and problem-solving through creation games.", "Report analysis section, expert interview and key findings paragraphs.", "qualitative"),
];

const claimKindByEvidenceType: Record<EvidenceType, EvidenceClaimKind> = {
  observed: "observed claim",
  "self-reported": "finding",
  qualitative: "finding",
  forecast: "finding",
  "platform-wide metric": "metric",
  "editorial inference": "editorial inference",
};

const factsForInsight = (insightId: string) => extractedFacts.filter((item) => item.insightId === insightId);

type InsightEditorial = Pick<
  Insight,
  | "interpretation"
  | "confidence"
  | "confidenceReason"
  | "nuance"
  | "genZComparison"
  | "agencyImplication"
  | "relatedCreatorIds"
  | "relatedSpaceIds"
>;

const editorialByInsightId: Record<string, InsightEditorial> = {
  "play-social-infrastructure": {
    interpretation: "Gaming matters here as a recurring place to maintain friendship, not simply as entertainment consumed alone.", confidence: "medium", confidenceReason: "A national teen survey and child-focused creation-gaming research converge on friendship and social learning, but cover different age groups.", nuance: "The evidence shows social value for many players; it does not mean every game, server, or friendship is supportive.", genZComparison: "Gen Z normalized multiplayer friendship; Gen Alpha meets social play earlier and inside more creator-built worlds.", agencyImplication: "Give a group something useful to do together repeatedly, with private-by-default social choices.", relatedCreatorIds: ["aphmau"], relatedSpaceIds: ["roblox"],
  },
  "play-making-interface": {
    interpretation: "For many children, the same world can be a game, a studio, and an informal classroom.", confidence: "medium", confidenceReason: "Child survey findings on desired learning are reinforced by first-party behavior signals from a major creation platform.", nuance: "Interest in learning through a game is not evidence that every in-game lesson works or transfers beyond the platform.", genZComparison: "Gen Z often moved from playing to separate creator tools; Gen Alpha increasingly encounters both in one environment.", agencyImplication: "Offer flexible materials, prompts, or mechanics that reward making rather than a finished branded object.", relatedCreatorIds: ["aphmau"], relatedSpaceIds: ["minecraft"],
  },
  "play-friendship-travels": {
    interpretation: "The relationship is the stable layer; games, messages, video, and in-person time are interchangeable settings around it.", confidence: "medium", confidenceReason: "Large-scale teen self-report and longitudinal qualitative cases both document friendship moving through connected activities.", nuance: "Cross-platform friendship also creates moderation, privacy, and age-assurance challenges when context changes.", genZComparison: "Gen Z built cross-platform social lives; Gen Alpha is inheriting that pattern before platform boundaries feel distinct.", agencyImplication: "Design for continuity across sessions without requiring children to expose a public identity.", relatedCreatorIds: ["itsfunneh"], relatedSpaceIds: ["discord"],
  },
  "play-avatars-identity": {
    interpretation: "Avatar choices provide a low-stakes way to test aesthetics, affiliations, and how one appears to peers.", confidence: "medium", confidenceReason: "Platform style patterns and girls' self-reported image practices point in the same direction, though neither measures identity development directly.", nuance: "Expression can be playful and empowering while still carrying appearance pressure, exclusion, or purchase pressure.", genZComparison: "Gen Z curated profiles; Gen Alpha increasingly rehearses identity through persistent characters inside playable worlds.", agencyImplication: "Make self-expression broad, inclusive, reversible, and useful without tying belonging to paid scarcity.", relatedCreatorIds: ["barbie"], relatedSpaceIds: ["roblox"],
  },
  "play-small-crews": {
    interpretation: "Repeated play with a known group can create stronger belonging than visibility to a large anonymous audience.", confidence: "medium", confidenceReason: "Survey and case-study evidence both support small-group gaming and messaging as recurring social settings.", nuance: "Small groups can offer intimacy, but they can also intensify exclusion and make conflict harder to escape.", genZComparison: "Gen Z's social status was often narrated through followers; Gen Alpha's meaningful status can be legible inside a crew.", agencyImplication: "Reward collaboration and return visits by a small group instead of public popularity metrics.", relatedCreatorIds: ["kai-cenat"], relatedSpaceIds: ["discord"],
  },
  "play-competition-performance": {
    interpretation: "Competition becomes culture when play is narrated, clipped, watched, and connected to recognizable personalities.", confidence: "medium", confidenceReason: "Frequent gaming is well measured, while creator-led sports translation provides observed but narrower evidence of performance culture.", nuance: "Daily play and creator partnerships do not prove that all competition is watched or performed socially.", genZComparison: "Gen Z helped turn esports into media; Gen Alpha sees creator performance woven into mainstream sports and games.", agencyImplication: "Create simple stakes and a story spectators can follow without making humiliation the entertainment.", relatedCreatorIds: ["jesser"], relatedSpaceIds: ["youtube"],
  },
  "play-status-contribution": {
    interpretation: "Knowing the references, making something useful, and showing fluency can all function as status inside shared worlds.", confidence: "medium", confidenceReason: "The conclusion combines platform behavior with children's self-reported making skills and is best treated as an interpretation, not a measured hierarchy.", nuance: "Contribution-based status can broaden participation, while item scarcity and insider language can still exclude newcomers.", genZComparison: "Gen Z signaled taste through posts and follows; Gen Alpha can signal it through builds, skins, and in-world competence.", agencyImplication: "Let status come from contribution, mastery, or generosity rather than purchase alone.", relatedCreatorIds: ["kreekcraft"], relatedSpaceIds: ["roblox"],
  },
  "play-family-coplay": {
    interpretation: "Even when children choose the activity, adults often shape access, payment, permissions, and the practical limits around it.", confidence: "medium", confidenceReason: "National device-access findings and international child purchase data directly support household enablement, not the frequency of literal co-play.", nuance: "Adult involvement varies sharply by age, household resources, platform, and whether participation requires spending.", genZComparison: "Gen Z gained personal access during adolescence; much of Gen Alpha encounters connected play while still dependent on household infrastructure.", agencyImplication: "Make the child value clear and give adults a plain account of cost, data, safety, and stopping points.", relatedCreatorIds: ["bluey"], relatedSpaceIds: ["home-family-routines"],
  },
  "play-offline-rebound": {
    interpretation: "Recent gains in organized sport and outdoor participation challenge the idea that digital play simply replaces physical activity.", confidence: "low", confidenceReason: "This is a directional inference from two narrower U.S. participation categories rather than a measure of all offline play.", nuance: "Sport and outdoor participation are not all offline play, and participant counts do not reveal frequency, quality, affordability, or access.", genZComparison: "Both cohorts blend online and offline life; current Alpha signals make the coexistence easier to see than a simple substitution story.", agencyImplication: "Connect digital invitation to a worthwhile physical action without implying that every child has equal offline access.", relatedCreatorIds: ["danny-go"], relatedSpaceIds: ["after-school-sports-clubs"],
  },
  "play-safety-boundaries": {
    interpretation: "Safety settings, data rules, and adult controls are part of the play product rather than an external compliance layer.", confidence: "high", confidenceReason: "UNICEF design guidance and the revised COPPA rule independently establish concrete child-safety and privacy responsibilities.", nuance: "Compliance is a floor; it does not by itself resolve harmful contact, manipulative design, or uneven enforcement.", genZComparison: "Gen Z often entered systems retrofitted for safety; Gen Alpha is raising expectations that protection is present from first use.", agencyImplication: "Treat age assurance, privacy, reporting, spending, and parental visibility as core experience design.", relatedCreatorIds: ["pokemon"], relatedSpaceIds: ["nintendo-switch"],
  },
  "media-video-default": {
    interpretation: "Video is both a leisure format and an everyday interface for discovering, explaining, and demonstrating things.", confidence: "high", confidenceReason: "National media-use data and longitudinal child-media cases both show video embedded across entertainment and explanation.", nuance: "Video's prevalence differs by age and platform, and a high-use format is not automatically a trusted one.", genZComparison: "Gen Z used video alongside text search; Gen Alpha more often begins with video as the explanation itself.", agencyImplication: "Lead with a visible demonstration and a clear premise, then make deeper evidence easy to inspect.", relatedCreatorIds: ["mrbeast"], relatedSpaceIds: ["youtube"],
  },
  "media-short-form-shape": {
    interpretation: "Short-form changes discovery into a rapid sequence of complete mini-formats, not merely a shorter version of long video.", confidence: "medium", confidenceReason: "Child media-mix data and teen frequency data establish growth and routine use, while effects on attention remain contextual.", nuance: "Frequency does not diagnose attention capacity; content, purpose, pacing, and the option to stop all matter.", genZComparison: "Gen Z watched short-form become mainstream; Gen Alpha encounters its visual grammar as a default from childhood.", agencyImplication: "Make each unit understandable on its own and resist mechanics that depend on compulsive continuation.", relatedCreatorIds: ["alan-chikin-chow"], relatedSpaceIds: ["youtube-shorts"],
  },
  "media-creators-templates": {
    interpretation: "Creators make behavior legible by showing a repeatable way to speak, play, dress, react, or participate.", confidence: "medium", confidenceReason: "Observed league partnerships and child purchase-influence reporting show practical creator relevance, though imitation itself is not directly measured.", nuance: "Visibility does not equal trust, and influence varies by age, category, relationship, and adult mediation.", genZComparison: "Gen Z made creators celebrities; Gen Alpha also uses them as templates for participation inside other culture.", agencyImplication: "Choose a creator for the behavior they can credibly invite, not reach alone.", relatedCreatorIds: ["salish-matter"], relatedSpaceIds: ["youtube"],
  },
  "media-household-negotiation": {
    interpretation: "Children can initiate and shape a decision while adults retain payment, permission, or final approval.", confidence: "medium", confidenceReason: "Two child-and-parent studies identify concrete influence and independence gaps across multiple purchase categories.", nuance: "Influence is not purchasing power, and household authority changes with age, income, category, and culture.", genZComparison: "Gen Z's influence grew through social media; Gen Alpha is exercising it earlier inside shared digital purchasing flows.", agencyImplication: "Create separate, honest reasons for the child to care and the adult to approve.", relatedCreatorIds: ["ryans-world"], relatedSpaceIds: ["home-family-routines"],
  },
  "media-discovery-commerce": {
    interpretation: "The same feed can generate interest, demonstrate a product, normalize it socially, and hand the request into a family decision.", confidence: "medium", confidenceReason: "Two industry studies report linked social discovery, content creation, and purchase motivation among Alpha respondents.", nuance: "Self-reported purchase triggers do not prove conversion, and commercial literacy differs considerably by age.", genZComparison: "Gen Z saw social commerce emerge; Gen Alpha is meeting discovery and shopping as a more continuous experience.", agencyImplication: "Separate inspiration from transaction and make sponsorship, price, data use, and adult review unmistakable.", relatedCreatorIds: ["mrbeast"], relatedSpaceIds: ["tiktok"],
  },
  "media-repeatable-formats": {
    interpretation: "A recognizable challenge, sound, character, or ritual can travel farther than a one-off channel placement.", confidence: "medium", confidenceReason: "Observed sports partnerships and self-reported content making support format travel, but not a universal law of culture.", nuance: "Repeatability can invite participation or become empty imitation; community meaning depends on who can adapt the format.", genZComparison: "Gen Z spread memes across networks; Gen Alpha encounters more formats designed to move between creators, games, and properties.", agencyImplication: "Build a format with a stable rule and room for people to change the outcome.", relatedCreatorIds: ["kpop-demon-hunters"], relatedSpaceIds: ["youtube-shorts"],
  },
  "media-properties-travel": {
    interpretation: "A property stays culturally present by moving among viewing, music, play, products, and creator conversation.", confidence: "medium", confidenceReason: "Observed league extensions and multi-platform use support cross-environment reach, though title-level movement is an editorial synthesis.", nuance: "More touchpoints do not guarantee deeper affinity and can produce fatigue when every extension asks for a purchase.", genZComparison: "Gen Z followed franchises across screens; Gen Alpha expects worlds to be playable, remixable, and socially visible too.", agencyImplication: "Give each extension a distinct job instead of duplicating the same message everywhere.", relatedCreatorIds: ["pokemon"], relatedSpaceIds: ["netflix"],
  },
  "media-coviewing": {
    interpretation: "Media interests enter a household system where routines, shared carts, and adult review shape what happens next.", confidence: "medium", confidenceReason: "Shared-cart behavior and family media-routine evidence support negotiation at household scale, not a measured co-viewing rate.", nuance: "The evidence does not establish that families watched the same content together or agreed on its meaning.", genZComparison: "Gen Z's media influence was often framed as peer-led; Gen Alpha's younger ages keep household mediation visibly central.", agencyImplication: "Create an easy handoff from child interest to adult context without turning the child into a sales channel.", relatedCreatorIds: ["cocomelon"], relatedSpaceIds: ["home-family-routines"],
  },
  "media-ai-recommendation": {
    interpretation: "Conversational systems are becoming another front door to entertainment discovery alongside feeds, guides, and search.", confidence: "medium", confidenceReason: "Recent self-report studies show substantial chatbot recommendation preference and frequent AI use, but the behavior is changing quickly.", nuance: "Stated preference is not observed recommendation quality, and chatbot answers may be inaccurate, sponsored, or opaque.", genZComparison: "Gen Z learned algorithmic feeds; Gen Alpha is also learning to ask an algorithm directly and continue the conversation.", agencyImplication: "Make authoritative facts machine-readable and give young users a visible path to verify recommendations.", relatedCreatorIds: ["kpop-demon-hunters"], relatedSpaceIds: ["chatgpt"],
  },
  "media-reach-risk": {
    interpretation: "The systems that deliver scale can also deliver harmful recommendations and collect sensitive child data.", confidence: "medium", confidenceReason: "A large experimental preprint and binding U.S. policy changes identify concrete recommendation and privacy risks.", nuance: "The audit is a preprint and platform behavior can change; regulation also varies outside the United States.", genZComparison: "Gen Z exposed feed harms after adoption; Gen Alpha is growing up amid stronger evidence and regulation from the outset.", agencyImplication: "Audit adjacency, targeting, data collection, age treatment, and escalation paths before optimizing reach.", relatedCreatorIds: ["sssniperwolf"], relatedSpaceIds: ["youtube-shorts"],
  },
  "time-screen-purpose": {
    interpretation: "A single duration number collapses very different activities: talking, making, gaming, learning, and passive viewing.", confidence: "high", confidenceReason: "National time-use shifts and a longitudinal meta-analysis both support examining content and social context alongside duration.", nuance: "Purpose does not erase dose, sleep, displacement, or developmental concerns; it makes those questions more precise.", genZComparison: "Gen Z's debate centered hours online; Gen Alpha's mixed screen activities make that total less explanatory on its own.", agencyImplication: "Define the specific value of the screen moment and measure whether it displaces something important.", relatedCreatorIds: ["cocomelon"], relatedSpaceIds: ["youtube-kids"],
  },
  "time-device-access": {
    interpretation: "Personal devices arrive while children still depend on adults for rules, payments, transport, and developmental support.", confidence: "high", confidenceReason: "Two large child-media studies report early tablet and phone access with clear age gradients.", nuance: "Ownership, regular use, private access, and independent judgment are different conditions.", genZComparison: "Gen Z often received a first smartphone near adolescence; Gen Alpha's device pathway can begin with a personal tablet in toddlerhood.", agencyImplication: "Design onboarding for a child-and-caregiver system, not an assumed independent adult user.", relatedCreatorIds: ["like-nastya"], relatedSpaceIds: ["home-family-routines"],
  },
  "time-youtube-rhythm": {
    interpretation: "YouTube functions as a recurring household utility for entertainment, explanation, music, and filling small gaps in the day.", confidence: "high", confidenceReason: "National child and teen datasets both show sustained daily video use across adjacent Alpha ages.", nuance: "YouTube use spans distinct products and purposes; daily presence does not describe what was watched or with whom.", genZComparison: "Gen Z visited YouTube as a destination; Gen Alpha often experiences it as background infrastructure across routines.", agencyImplication: "Design for a recognizable recurring moment and give caregivers context before playback begins.", relatedCreatorIds: ["ms-rachel"], relatedSpaceIds: ["youtube"],
  },
  "time-parent-context": {
    interpretation: "Parenting the media day involves content, privacy, timing, permissions, and conversation, not only a timer.", confidence: "high", confidenceReason: "Child self-report reveals a guidance gap while COPPA defines a concrete parental-consent responsibility.", nuance: "More controls do not automatically create better guidance, especially when settings are complex or families have limited time.", genZComparison: "Gen Z's parents managed a smaller platform set; Gen Alpha families face AI and data decisions alongside screen limits.", agencyImplication: "Give adults concise controls and conversation prompts at the moment a decision is needed.", relatedCreatorIds: ["bluey"], relatedSpaceIds: ["home-family-routines"],
  },
  "time-family-needs": {
    interpretation: "Screens can occupy practical roles in care, transition, learning, and household coordination as well as leisure.", confidence: "medium", confidenceReason: "Device, daily-use, and adult-payment data show integration into family infrastructure; the specific needs are an editorial interpretation.", nuance: "A practical role does not make every use beneficial, and families have unequal access to alternatives and support.", genZComparison: "Gen Z's devices became personal social tools; Gen Alpha's earliest devices are often shared solutions inside caregiving routines.", agencyImplication: "Solve a real family task and be honest about duration, supervision, and what the experience cannot replace.", relatedCreatorIds: ["cocomelon"], relatedSpaceIds: ["youtube-kids"],
  },
  "time-age-change": {
    interpretation: "Averages across the full generation hide steep changes in device ownership, autonomy, platforms, and social context.", confidence: "high", confidenceReason: "Two studies report direct age-based access differences from early childhood through young adolescence.", nuance: "Chronological age is only one variable; development, family rules, and prior experience also shape readiness.", genZComparison: "Generational labels flattened Gen Z too; Alpha's current 0-to-16 span makes age segmentation especially non-negotiable.", agencyImplication: "State the intended age and redesign access, language, social features, and adult involvement for it.", relatedCreatorIds: ["salish-matter"], relatedSpaceIds: ["youtube"],
  },
  "time-nighttime-use": {
    interpretation: "The media day extends into bedtime through active phones, social communication, music, and routine viewing.", confidence: "high", confidenceReason: "Prospective early-adolescent data and objective toddler sleep measurement both associate specific bedtime screen patterns with sleep outcomes.", nuance: "Associations differ by behavior and age and do not prove that every nighttime screen causes poor sleep.", genZComparison: "Gen Z brought social media to bed; Gen Alpha's nighttime exposure begins earlier and includes a wider range of devices and routines.", agencyImplication: "Support quiet defaults, clear stopping cues, notification controls, and caregiver-visible bedtime settings.", relatedCreatorIds: ["nicole-laeno"], relatedSpaceIds: ["snapchat"],
  },
  "time-coexistence": {
    interpretation: "Digital and physical activity can sit in the same life; one does not provide a reliable proxy for the absence of the other.", confidence: "medium", confidenceReason: "Longitudinal screen evidence and stated preference for physical-only experiences challenge a simple online-versus-offline binary.", nuance: "Coexistence does not reveal balance, access, intensity, or whether one activity displaced sleep or relationships.", genZComparison: "Gen Z was often described as moving online; Gen Alpha data makes hybrid routines a more useful starting assumption.", agencyImplication: "Design digital participation to prompt, document, or enrich a worthwhile offline action.", relatedCreatorIds: ["danny-go"], relatedSpaceIds: ["after-school-sports-clubs"],
  },
  "time-private-day": {
    interpretation: "Personal phone access creates unsupervised moments and locations that shared household screens did not.", confidence: "high", confidenceReason: "National teen and Alpha surveys both document extensive smartphone access and high-frequency use among older children.", nuance: "Access does not prove secrecy or harm; privacy can also support identity, support-seeking, and independence.", genZComparison: "Gen Z pioneered the private smartphone day; older Gen Alpha reaches it after years of prior connected-device experience.", agencyImplication: "Assume use can happen alone and build discreet safety, exit, reporting, and notification controls.", relatedCreatorIds: ["charli-damelio"], relatedSpaceIds: ["snapchat"],
  },
  "time-household-context": {
    interpretation: "Access, gaming frequency, payment, and autonomy vary with household resources and cannot be treated as a universal Alpha baseline.", confidence: "medium", confidenceReason: "Income-stratified gaming data and child payment reporting establish meaningful household differences, though they measure different populations.", nuance: "Income is not the same as culture, parenting style, connectivity, disability, or local opportunity.", genZComparison: "The digital divide shaped Gen Z access; for Gen Alpha it also shapes quality of devices, subscriptions, supervision, and creative opportunity.", agencyImplication: "Test the experience under lower-bandwidth, shared-device, no-purchase, and limited-adult-time conditions.", relatedCreatorIds: ["ryans-world"], relatedSpaceIds: ["home-family-routines"],
  },
  "learning-assembled": {
    interpretation: "A child may combine school, video, a game, search, and another person to answer one learning need.", confidence: "medium", confidenceReason: "A systematic review and qualitative child-media research both support a distributed learning environment without naming one dominant tool.", nuance: "Self-assembled learning can be resourceful but leaves quality, curriculum fit, and verification uneven.", genZComparison: "Gen Z learned to search across the web; Gen Alpha assembles answers across more interactive and conversational environments.", agencyImplication: "Make a useful explanation modular, attributable, and easy to carry into the next learning context.", relatedCreatorIds: ["ms-rachel"], relatedSpaceIds: ["youtube"],
  },
  "learning-creation-skills": {
    interpretation: "Children perceive building in game worlds as practice in creativity, problem-solving, coding, art, and design.", confidence: "medium", confidenceReason: "Direct child survey findings support perceived skill value; the second source shows adjacent youth making but not measured transfer.", nuance: "Perceived learning is not a skills assessment, and access to constructive modes, mentors, and time is uneven.", genZComparison: "Gen Z learned creator tools around games; Gen Alpha can encounter skill-building as an ordinary mode within play.", agencyImplication: "Set an open-ended challenge and make the learned technique visible after the child builds.", relatedCreatorIds: ["aphmau"], relatedSpaceIds: ["minecraft"],
  },
  "learning-ai-homework": {
    interpretation: "AI has already joined the practical toolkit children use for explanations, homework support, and school tasks.", confidence: "medium", confidenceReason: "Two recent youth studies independently rank homework among the most common reported AI uses.", nuance: "Use does not show learning quality, independent understanding, school permission, or whether answers were checked.", genZComparison: "Gen Z searched for homework help; Gen Alpha can request a tailored answer and follow-up in the same interface.", agencyImplication: "Support hints, reasoning, citations, and checking rather than delivering an opaque final answer.", relatedCreatorIds: ["ms-rachel"], relatedSpaceIds: ["chatgpt"],
  },
  "learning-ai-discovery": {
    interpretation: "Children are using AI beyond assignments to explore interests, create, get recommendations, and seek everyday support.", confidence: "medium", confidenceReason: "Two recent studies report frequent chatbot use across hobbies, entertainment, school, and discovery, but rely on self-report.", nuance: "Broad use categories conceal quality, risk, privacy, and large differences between products and ages.", genZComparison: "Gen Z adopted generative AI after formative habits were set; Gen Alpha is incorporating it while those habits are still forming.", agencyImplication: "Design bounded exploration with source visibility, privacy protection, and routes to human help.", relatedCreatorIds: ["moriah-elizabeth"], relatedSpaceIds: ["chatgpt"],
  },
  "learning-safety-guidance": {
    interpretation: "Children's AI use is expanding faster than consistent family conversations and school instruction about safe use.", confidence: "medium", confidenceReason: "Child reports of missing guidance align with parent concerns about content, thinking, and misinformation.", nuance: "Concern is not measured harm, and guidance quality matters more than whether a conversation happened once.", genZComparison: "Gen Z received social-media literacy after adoption; Gen Alpha risks repeating that lag with conversational AI.", agencyImplication: "Put age-appropriate guidance, privacy explanations, and escalation paths inside the interaction itself.", relatedCreatorIds: ["bluey"], relatedSpaceIds: ["home-family-routines"],
  },
  "learning-verification": {
    interpretation: "Knowing when and how to check an answer is becoming as important as knowing how to ask for one.", confidence: "medium", confidenceReason: "Youth self-report shows both active verification and a substantial misunderstanding of AI reliability.", nuance: "Saying one verifies does not reveal the method, and children may compare one weak source with another.", genZComparison: "Gen Z learned source evaluation for search results; Gen Alpha must also evaluate fluent answers that hide their sources.", agencyImplication: "Expose citations, uncertainty, alternative views, and a simple verification step at the point of answer.", relatedCreatorIds: ["moriah-elizabeth"], relatedSpaceIds: ["khan-academy"],
  },
  "learning-enablement": {
    interpretation: "Educational value comes from the activity, support, and setting a tool enables, not the novelty of the device.", confidence: "high", confidenceReason: "A systematic review finds no dominant technology while child research ties interest to specific enabled activities.", nuance: "A promising activity still depends on pedagogy, accessibility, teacher or caregiver support, and implementation quality.", genZComparison: "Gen Z classrooms often led with device access; Alpha's crowded tool landscape makes purpose a stronger filter than hardware.", agencyImplication: "Name the capability first, then choose the lightest technology that reliably enables it.", relatedCreatorIds: ["ms-rachel"], relatedSpaceIds: ["google-classroom"],
  },
  "learning-remix": {
    interpretation: "Making identity develops through cycles of trying, revising, borrowing a format, and making it recognizably one's own.", confidence: "medium", confidenceReason: "Child creation-gaming findings and youth content-making signals both support iterative production, though identity outcomes are inferred.", nuance: "Remix can build confidence and skill while raising authorship, comparison, moderation, and copyright questions.", genZComparison: "Gen Z remixed posts and memes; Gen Alpha can remix playable systems, avatars, edits, and generated material.", agencyImplication: "Provide editable building blocks, creditable sources, and room for visible personal variation.", relatedCreatorIds: ["moriah-elizabeth"], relatedSpaceIds: ["capcut"],
  },
  "learning-commercial-fluency": {
    interpretation: "Wish lists, shared carts, requests, and category influence give children practical experience navigating household commerce.", confidence: "medium", confidenceReason: "Two industry studies document child decision participation and influence across products and experiences.", nuance: "Commercial fluency is not consumer protection; younger children may recognize a transaction without understanding persuasion or data use.", genZComparison: "Gen Z learned influencer commerce in adolescence; Gen Alpha practices negotiation and digital purchase requests earlier.", agencyImplication: "Make value, price, sponsorship, scarcity, and adult approval legible without manufacturing urgency.", relatedCreatorIds: ["salish-matter"], relatedSpaceIds: ["instagram"],
  },
  "learning-multimodal": {
    interpretation: "Learning and self-expression move among voice, touch, typing, video, play, making, and social coaching.", confidence: "medium", confidenceReason: "Interaction-mode survey data and qualitative learning observations both document movement across modalities and settings.", nuance: "Multimodal does not mean every mode is equally accessible, effective, or appropriate for every learner.", genZComparison: "Gen Z became mobile-first; Gen Alpha is growing up expecting to speak, tap, watch, build, and converse with systems interchangeably.", agencyImplication: "Offer more than one path into the idea while keeping the underlying concept consistent and accessible.", relatedCreatorIds: ["aphmau"], relatedSpaceIds: ["youtube"],
  },
};

export const insights: Insight[] = insightSeeds.map((seed) => ({
  ...seed,
  evidenceIds: factsForInsight(seed.id).map((item) => `evidence-${item.insightId}-${item.slot}`),
  ageRange: "Varies by supporting evidence",
  geography: "Varies by supporting evidence",
  ...editorialByInsightId[seed.id],
}));

export const evidenceItems: EvidenceItem[] = extractedFacts.map((item) => {
    const source = sourceById.get(item.sourceId);
    const insight = insightSeeds.find((candidate) => candidate.id === item.insightId);
    if (!source) {
      throw new Error(`Unknown source ${item.sourceId} in ${item.insightId}`);
    }
    if (!insight) {
      throw new Error(`Unknown insight ${item.insightId}`);
    }

    return {
      id: `evidence-${item.insightId}-${item.slot}`,
      sourceId: item.sourceId,
      claim: item.claim,
      claimKind: claimKindByEvidenceType[item.evidenceType],
      supportRationale: `Contributes ${item.evidenceType} evidence to the scoped interpretation "${insight.title}." Read it with the paired evidence item and the stated limitations.`,
      locator: item.locator,
      evidenceType: item.evidenceType,
      population: source.population,
      ageRange: source.ageRange,
      geography: source.geography,
      period: source.fieldworkPeriod,
      methodology: source.methodology,
      limitations: source.limitations,
      insightIds: [item.insightId],
    };
  });
