import { sources } from "./sources";
import type { EvidenceClaimKind, EvidenceItem, EvidenceType, Insight, Theme } from "./types";

export const themes: Theme[] = [
  { id: "play-belonging", title: "Play & Belonging", description: "Social play, identity, family participation, and safety." },
  { id: "media-influence", title: "Media & Influence", description: "Video, creators, culture, household influence, and discovery." },
  { id: "time-routines", title: "Time & Routines", description: "Daily media rhythms, device access, and household context." },
  { id: "learning-becoming", title: "Learning & Becoming", description: "Learning, creativity, AI, literacy, and self-directed growth." },
];

type InsightSeed = Pick<Insight, "id" | "themeId" | "sequence" | "title" | "thesis" | "tags"> & {
  sourceIds: [string, string];
};

const insightSeeds: InsightSeed[] = [
  { id: "play-social-infrastructure", themeId: "play-belonging", sequence: 1, title: "Play is social infrastructure.", thesis: "Shared activity gives friendship a durable place to happen.", tags: ["play", "belonging"], sourceIds: ["walton-creation-gaming-2024", "ofcom-children-media-lives-2025"] },
  { id: "play-making-interface", themeId: "play-belonging", sequence: 2, title: "Playing and making increasingly share the same interface.", thesis: "Creation tools make participation part of play.", tags: ["play", "creation"], sourceIds: ["walton-creation-gaming-2024", "roblox-search-style-trends-2025"] },
  { id: "play-friendship-travels", themeId: "play-belonging", sequence: 3, title: "Friendship travels between games, chat, video, and real life.", thesis: "Relationships move across connected activities.", tags: ["friendship", "spaces"], sourceIds: ["ofcom-children-media-lives-2025", "pew-teens-video-games-2024"] },
  { id: "play-avatars-identity", themeId: "play-belonging", sequence: 4, title: "Avatar style is a visible identity signal.", thesis: "Digital expression lets young people try style and social signals.", tags: ["identity", "avatars"], sourceIds: ["roblox-search-style-trends-2025", "razorfish-alpha-industries"] },
  { id: "play-small-crews", themeId: "play-belonging", sequence: 5, title: "Small crews sustain recurring connection.", thesis: "Repeated shared activity gives friend groups a dependable place to meet.", tags: ["friendship", "groups"], sourceIds: ["ofcom-children-media-lives-2025", "pew-teens-video-games-2024"] },
  { id: "play-competition-performance", themeId: "play-belonging", sequence: 6, title: "Gaming culture extends beyond the game.", thesis: "Frequent play and creator translation connect games and sports to wider media culture.", tags: ["competition", "media"], sourceIds: ["pew-teens-video-games-2024", "ap-sports-alpha-2026"] },
  { id: "play-status-contribution", themeId: "play-belonging", sequence: 7, title: "Fluency and contribution are visible inside shared worlds.", thesis: "Style knowledge and active building give participation a visible form.", tags: ["identity", "participation"], sourceIds: ["roblox-search-style-trends-2025", "walton-creation-gaming-2024"] },
  { id: "play-family-coplay", themeId: "play-belonging", sequence: 8, title: "Households set the conditions around play.", thesis: "Access, permission, and payment keep play embedded in family systems.", tags: ["family", "play"], sourceIds: ["common-sense-census-2025", "pwc-alpha-2026"] },
  { id: "play-offline-rebound", themeId: "play-belonging", sequence: 9, title: "Offline play is rebounding rather than disappearing.", thesis: "Digital and offline activity should be studied together.", tags: ["offline", "play"], sourceIds: ["project-play-state-of-play-2025", "outdoor-participation-trends-2026"] },
  { id: "play-safety-boundaries", themeId: "play-belonging", sequence: 10, title: "Safety boundaries are part of the play experience.", thesis: "Child-centered game participation requires safety by design.", tags: ["safety", "play"], sourceIds: ["unicef-online-gaming", "ftc-coppa-2025"] },
  { id: "media-video-default", themeId: "media-influence", sequence: 1, title: "Video is a primary route through the media day.", thesis: "Video sits alongside gaming and streaming as a regular part of children's media use.", tags: ["video", "media"], sourceIds: ["common-sense-census-2025", "pwc-alpha-2026"] },
  { id: "media-short-form-shape", themeId: "media-influence", sequence: 2, title: "Short-form is becoming a larger part of the media mix.", thesis: "Short-form use is growing and recurring across younger children and teens.", tags: ["short-form", "media"], sourceIds: ["common-sense-census-2025", "pew-teens-social-2024"] },
  { id: "media-creators-templates", themeId: "media-influence", sequence: 3, title: "Creators translate culture into familiar formats.", thesis: "Organizations use creators to reach young audiences, while social media can prompt purchase interest.", tags: ["creators", "influence"], sourceIds: ["ap-sports-alpha-2026", "pwc-alpha-2026"] },
  { id: "media-household-negotiation", themeId: "media-influence", sequence: 4, title: "Influence is negotiated inside the household.", thesis: "Interest, permission, and purchase often involve adults.", tags: ["family", "commerce"], sourceIds: ["pwc-alpha-2026", "gwi-alpha-unfiltered"] },
  { id: "media-discovery-commerce", themeId: "media-influence", sequence: 5, title: "Discovery and commerce increasingly share the same surface.", thesis: "Discovery formats can connect interest with household decisions.", tags: ["discovery", "commerce"], sourceIds: ["pwc-alpha-2026", "emarketer-alpha-faq-2026"] },
  { id: "media-repeatable-formats", themeId: "media-influence", sequence: 6, title: "Culture moves through repeatable formats more than fixed channels.", thesis: "Cultural participation can travel across platforms and formats.", tags: ["culture", "formats"], sourceIds: ["ap-sports-alpha-2026", "ofcom-children-media-lives-2025"] },
  { id: "media-properties-travel", themeId: "media-influence", sequence: 7, title: "Entertainment reaches them through multiple routes.", thesis: "Creators, video, games, and streaming give properties more than one path into attention.", tags: ["culture", "franchises"], sourceIds: ["ap-sports-alpha-2026", "pwc-alpha-2026"] },
  { id: "media-coviewing", themeId: "media-influence", sequence: 8, title: "Media influence is negotiated at household scale.", thesis: "Children's media interests move through family routines and adult review.", tags: ["family", "video"], sourceIds: ["common-sense-census-2025", "pwc-alpha-2026"] },
  { id: "media-ai-recommendation", themeId: "media-influence", sequence: 9, title: "AI is entering entertainment search and recommendation.", thesis: "Conversational discovery changes how entertainment can be found and evaluated.", tags: ["ai", "discovery"], sourceIds: ["nielsen-ai-discovery-2026", "razorfish-alpha-ai"] },
  { id: "media-reach-risk", themeId: "media-influence", sequence: 10, title: "Reach, persuasion, and safety risk coexist in the same feeds.", thesis: "Participation environments need responsible safeguards alongside reach planning.", tags: ["safety", "media"], sourceIds: ["arxiv-young-user-safety-2025", "ftc-coppa-2025"] },
  { id: "time-screen-purpose", themeId: "time-routines", sequence: 1, title: "Total screen time hides a major shift in what screens are for.", thesis: "Context and activity matter alongside duration.", tags: ["time", "context"], sourceIds: ["digital-wellbeing-review-2025", "common-sense-census-2025"] },
  { id: "time-device-access", themeId: "time-routines", sequence: 2, title: "Personal device access begins before personal independence.", thesis: "Device access occurs inside family rules and developmental context.", tags: ["devices", "family"], sourceIds: ["common-sense-census-2025", "pew-teens-social-2024"] },
  { id: "time-youtube-rhythm", themeId: "time-routines", sequence: 3, title: "YouTube is embedded in the daily household rhythm.", thesis: "Video is a recurring part of young children's media environments.", tags: ["youtube", "routines"], sourceIds: ["common-sense-census-2025", "pew-teens-social-2024"] },
  { id: "time-parent-context", themeId: "time-routines", sequence: 4, title: "Parents manage context and rules, not only minutes.", thesis: "Household management includes content, setting, and permission.", tags: ["parents", "safety"], sourceIds: ["common-sense-census-2025", "unicef-online-gaming"] },
  { id: "time-family-needs", themeId: "time-routines", sequence: 5, title: "Screens fill practical family needs as well as entertainment needs.", thesis: "Media can be woven into routines, care, and learning.", tags: ["family", "media"], sourceIds: ["common-sense-census-2025", "aecf-generation-alpha"] },
  { id: "time-age-change", themeId: "time-routines", sequence: 6, title: "Digital routines change quickly with age.", thesis: "Age should remain explicit when interpreting media patterns.", tags: ["age", "routines"], sourceIds: ["common-sense-census-2025", "pew-teens-social-2024"] },
  { id: "time-nighttime-use", themeId: "time-routines", sequence: 7, title: "Nighttime use is part of the real media day.", thesis: "The daily media environment extends beyond a single daytime measure.", tags: ["routines", "time"], sourceIds: ["bedtime-screen-early-adolescents-2024", "prebed-screen-young-children-2021"] },
  { id: "time-coexistence", themeId: "time-routines", sequence: 8, title: "Online time does not erase demand for offline experience.", thesis: "Digital activity needs to be considered with, not apart from, offline preference and context.", tags: ["offline", "context"], sourceIds: ["screen-socioemotional-review-2025", "razorfish-alpha-industries"] },
  { id: "time-private-day", themeId: "time-routines", sequence: 9, title: "Personal devices make private media access possible.", thesis: "Portable personal access changes where media can be used and who can see the moment.", tags: ["devices", "privacy"], sourceIds: ["pew-teens-social-2024", "pwc-alpha-2026"] },
  { id: "time-household-context", themeId: "time-routines", sequence: 10, title: "Income and household context shape access and use.", thesis: "Access and use should not be treated as uniform across families.", tags: ["equity", "family"], sourceIds: ["aecf-generation-alpha", "common-sense-census-2025"] },
  { id: "learning-assembled", themeId: "learning-becoming", sequence: 1, title: "Learning is assembled on demand across multiple environments.", thesis: "Learning can span school, video, play, search, and family support.", tags: ["learning", "spaces"], sourceIds: ["generation-alpha-education-review-2024", "ofcom-children-media-lives-2025"] },
  { id: "learning-creation-skills", themeId: "learning-becoming", sequence: 2, title: "Creation games are perceived as places to learn real skills.", thesis: "Creation-gaming environments can support making and social learning.", tags: ["learning", "games"], sourceIds: ["walton-creation-gaming-2024", "generation-alpha-education-review-2024"] },
  { id: "learning-ai-homework", themeId: "learning-becoming", sequence: 3, title: "AI is already part of homework and explanation.", thesis: "AI is appearing in youth learning and explanation contexts.", tags: ["ai", "learning"], sourceIds: ["common-sense-ai-2026", "common-sense-chatgpt-video"] },
  { id: "learning-ai-discovery", themeId: "learning-becoming", sequence: 4, title: "AI use extends beyond schoolwork into discovery, creativity, and support.", thesis: "AI use spans discovery, creativity, and everyday support contexts.", tags: ["ai", "creativity"], sourceIds: ["razorfish-alpha-ai", "nielsen-ai-discovery-2026"] },
  { id: "learning-safety-guidance", themeId: "learning-becoming", sequence: 5, title: "Safety guidance is lagging behind AI adoption.", thesis: "Family guidance and privacy safeguards remain necessary around AI use.", tags: ["ai", "safety"], sourceIds: ["common-sense-ai-2026", "ftc-coppa-2025"] },
  { id: "learning-verification", themeId: "learning-becoming", sequence: 6, title: "Verification is becoming a core literacy.", thesis: "Trust and checking matter when systems recommend and answer.", tags: ["ai", "literacy"], sourceIds: ["nielsen-ai-discovery-2026", "common-sense-chatgpt-video"] },
  { id: "learning-enablement", themeId: "learning-becoming", sequence: 7, title: "Technology matters for what it enables, not for the hardware itself.", thesis: "The learning value of technology depends on activity and setting.", tags: ["learning", "technology"], sourceIds: ["generation-alpha-education-review-2024", "digital-wellbeing-review-2025"] },
  { id: "learning-remix", themeId: "learning-becoming", sequence: 8, title: "Creation happens through iteration and remix.", thesis: "Creation environments give young people opportunities to make, adapt, and revise.", tags: ["creation", "identity"], sourceIds: ["walton-creation-gaming-2024", "razorfish-alpha-industries"] },
  { id: "learning-commercial-fluency", themeId: "learning-becoming", sequence: 9, title: "Commercial fluency begins as a form of practical learning.", thesis: "Household influence and brands are part of young people's practical media environment.", tags: ["commerce", "learning"], sourceIds: ["pwc-alpha-2026", "razorfish-alpha-industries"] },
  { id: "learning-multimodal", themeId: "learning-becoming", sequence: 10, title: "Children move among multiple interaction and learning modes.", thesis: "Touch, typing, voice, video, play, and making all appear in the learning environment.", tags: ["learning", "identity"], sourceIds: ["pwc-alpha-2026", "walton-creation-gaming-2024"] },
];

const sourceById = new Map(sources.map((item) => [item.id, item]));

type ExtractedFact = {
  insightId: string;
  slot: 1 | 2;
  sourceId: string;
  claim: string;
  locator: string;
  evidenceType: EvidenceType;
};

const fact = (
  insightId: string,
  slot: 1 | 2,
  sourceId: string,
  claim: string,
  locator: string,
  evidenceType: EvidenceType,
): ExtractedFact => ({ insightId, slot, sourceId, claim, locator, evidenceType });

const extractedFacts: ExtractedFact[] = [
  fact("play-social-infrastructure", 1, "pew-teens-video-games-2024", "Forty-seven percent of teen video-game players said gaming helped their friendships, and 47% had made an online friend through a game.", "Socializing over video games section, findings paragraphs.", "self-reported"),
  fact("play-social-infrastructure", 2, "walton-creation-gaming-2024", "Children said Roblox and Minecraft help them practice creativity and problem-solving, while expert interviews emphasized team-based social learning.", "Key Findings section, cognitive development finding and expert interview paragraph.", "self-reported"),
  fact("play-making-interface", 1, "walton-creation-gaming-2024", "At least seven in ten children wanted to learn subjects such as coding, art, or design inside Roblox or Minecraft.", "Key Findings section, formal education finding.", "self-reported"),
  fact("play-making-interface", 2, "roblox-search-style-trends-2025", "Roblox's first-party trend data linked what users searched for with the avatar styles they adopted inside experiences, making discovery part of creation and play.", "Search and style trends section, platform findings.", "editorial inference"),
  fact("play-friendship-travels", 1, "pew-teens-video-games-2024", "Most teen players gamed with other people, and 40% of all U.S. teens had made an online friend through a shared game.", "Socializing over video games section, findings paragraphs.", "self-reported"),
  fact("play-friendship-travels", 2, "ofcom-children-media-lives-2025", "Ofcom's case studies observed children carrying shared interests between games, messaging, video, and in-person friend groups.", "Summary report, friendships and communication findings section.", "qualitative"),
  fact("play-avatars-identity", 1, "roblox-search-style-trends-2025", "Platform search and style patterns showed avatar appearance moving with named aesthetics and cultural trends inside Roblox experiences.", "Avatar style trends section, platform findings.", "platform-wide metric"),
  fact("play-avatars-identity", 2, "razorfish-alpha-industries", "Eighty percent of Alpha girls had used a filter or retouching app, while 63% wanted more inclusive representation in media.", "Industry findings section, beauty and representation paragraph.", "self-reported"),
  fact("play-small-crews", 1, "pew-teens-video-games-2024", "Ninety-eight percent of self-identified teen gamers played with others, and 68% had made a friend online through a game.", "Socializing over video games section, gamer comparison paragraph.", "self-reported"),
  fact("play-small-crews", 2, "ofcom-children-media-lives-2025", "Ofcom's longitudinal cases showed small friend groups using games and private messages as recurring places to coordinate and stay connected.", "Summary report, friend-group routines findings section.", "qualitative"),
  fact("play-competition-performance", 1, "pew-teens-video-games-2024", "About four in ten U.S. teens played video games daily, including 23% who played several times a day.", "Who plays video games section, frequency paragraph.", "self-reported"),
  fact("play-competition-performance", 2, "ap-sports-alpha-2026", "The NBA and NHL partnered directly with young creators to reach younger fans, and the NBA used AI to identify potential partners.", "Article opening paragraphs on league creator partnerships.", "observed"),
  fact("play-status-contribution", 1, "roblox-search-style-trends-2025", "Roblox's platform findings treated avatar style and search fluency as visible participation patterns inside user-created experiences.", "Search and avatar style findings section.", "editorial inference"),
  fact("play-status-contribution", 2, "walton-creation-gaming-2024", "Players named creativity and problem-solving among the skills they actively learn while building in Roblox and Minecraft.", "Key Findings section, cognitive development paragraph.", "self-reported"),
  fact("play-family-coplay", 1, "common-sense-census-2025", "Forty percent of children had a tablet by age two and nearly one in four had a personal cellphone by age eight, showing that early access is household-enabled.", "Key findings paragraph, device ownership metrics.", "self-reported"),
  fact("play-family-coplay", 2, "pwc-alpha-2026", "Sixty percent of children said an adult pays when they buy something, even as children exercise growing choice over digital and physical purchases.", "Following the money section, payment-method findings.", "self-reported"),
  fact("play-offline-rebound", 1, "project-play-state-of-play-2025", "Organized-sport participation among U.S. youth ages 6-17 increased from 53.8% in 2022 to 55.4% in 2023, followed by a separate 6% one-year participation uptick in 2024; this is a directional inference that one form of offline play rebounded.", "Introduction, Government Data and Industry Data paragraphs.", "editorial inference"),
  fact("play-offline-rebound", 2, "outdoor-participation-trends-2026", "Outdoor participation among U.S. children ages 6-12 grew 5% to 22.6 million in the 2025 annual wave; this is a directional inference that another form of offline recreation gained participants.", "Executive summary, key trends list, children ages 6 to 12 finding.", "editorial inference"),
  fact("play-safety-boundaries", 1, "unicef-online-gaming", "UNICEF concludes that child safety, privacy, and rights protections must be built into online-game design rather than left only to parental monitoring.", "Report recommendations section on safety by design.", "qualitative"),
  fact("play-safety-boundaries", 2, "ftc-coppa-2025", "The revised COPPA rule requires separate parental opt-in before children's data can be disclosed for targeted advertising and limits indefinite data retention.", "FTC release, final-rule changes paragraphs.", "observed"),
  fact("media-video-default", 1, "common-sense-census-2025", "Children zero to eight averaged about 2.5 hours of screen media a day while short-form services including YouTube Shorts grew.", "Key findings paragraph, daily time and short-form video findings.", "self-reported"),
  fact("media-video-default", 2, "pwc-alpha-2026", "Sixty-eight percent of children ages seven to fourteen said they use YouTube regularly, ahead of gaming platforms at 54% and streaming services at 49%.", "Digital influence section, platform-use findings paragraph.", "self-reported"),
  fact("media-short-form-shape", 1, "common-sense-census-2025", "Total daily screen time held near 2.5 hours while traditional TV declined and TikTok and YouTube Shorts rose, indicating a format shift within stable time.", "Key findings paragraph, changing media mix.", "self-reported"),
  fact("media-short-form-shape", 2, "pew-teens-social-2024", "About six in ten U.S. teens ages 13 to 17 said they visited TikTok daily, including 16% who reported being on it almost constantly.", "How often do teens visit online platforms section, TikTok frequency paragraphs.", "self-reported"),
  fact("media-creators-templates", 1, "ap-sports-alpha-2026", "Major leagues partnered with young creators to translate sports into the formats and language younger audiences already follow.", "Article opening paragraphs on NBA and NHL creator partnerships.", "observed"),
  fact("media-creators-templates", 2, "pwc-alpha-2026", "Sixty-one percent of Gen Alpha respondents said social media makes them want to buy something, exceeding reported peer influence at 56%.", "Digital influence section, purchase-motivation findings.", "self-reported"),
  fact("media-household-negotiation", 1, "pwc-alpha-2026", "Children reported more independent ordering than parents recognized: 25% cited food-delivery apps versus 14% of parents, an 11-point gap.", "Independence gap section, child-parent comparison paragraph.", "self-reported"),
  fact("media-household-negotiation", 2, "razorfish-alpha-industries", "Sixty-one percent of parents said their child strongly influences family food choices, and 61% said children have final say on the family car.", "Industry findings section, household influence paragraph.", "self-reported"),
  fact("media-discovery-commerce", 1, "pwc-alpha-2026", "Sixty-one percent of children pointed to social media as a purchase trigger, while 68% used YouTube regularly and 54% used gaming platforms.", "Digital influence section, discovery and platform findings.", "self-reported"),
  fact("media-discovery-commerce", 2, "razorfish-alpha-industries", "Seventy-five percent were interested in beauty content on social media and 38% already made their own content.", "Industry findings section, social beauty paragraph.", "self-reported"),
  fact("media-repeatable-formats", 1, "ap-sports-alpha-2026", "Sports leagues used recurring creator partnerships, AI-assisted partner discovery, and youth-native meme formats to maintain relevance.", "Article body section on league youth-engagement formats.", "observed"),
  fact("media-repeatable-formats", 2, "razorfish-alpha-industries", "Thirty-eight percent of Alphas interested in beauty content said they already create content themselves, showing formats travel through imitation and making.", "Industry findings section, social beauty paragraph.", "self-reported"),
  fact("media-properties-travel", 1, "ap-sports-alpha-2026", "The NBA and NHL extended league culture through creators and social formats rather than relying only on live games and broadcasts.", "Article opening and league examples section.", "observed"),
  fact("media-properties-travel", 2, "pwc-alpha-2026", "Regular use crossed YouTube (68%), gaming platforms (54%), and streaming services (49%), giving entertainment properties multiple routes into children's attention.", "Digital influence section, platform-use findings.", "editorial inference"),
  fact("media-coviewing", 1, "pwc-alpha-2026", "Fifty-two percent of children added products to shared online carts for parental review before checkout.", "Independence gap section, shared-cart finding.", "self-reported"),
  fact("media-coviewing", 2, "common-sense-census-2025", "Young children's daily media time stayed near 2.5 hours as parents navigated a mix shifting toward games and short-form video.", "Key findings and family-guidance paragraphs.", "editorial inference"),
  fact("media-ai-recommendation", 1, "nielsen-ai-discovery-2026", "Forty-nine percent of Gen Alpha respondents chose AI chatbots as the best source for TV and movie recommendations, versus 41% for service guides and 11% for search results.", "News release, entertainment recommendation findings paragraph.", "self-reported"),
  fact("media-ai-recommendation", 2, "razorfish-alpha-ai", "Twenty-two percent of Alphas used AI daily and 12% used it several times a day, with fun and hobbies among the leading uses.", "AI day-to-day tool findings paragraph.", "self-reported"),
  fact("media-reach-risk", 1, "arxiv-young-user-safety-2025", "Fifteen percent of YouTube recommendations to age-13 accounts were rated harmful versus 8.17% for adult accounts, appearing after an average 3:06 of passive scrolling.", "Abstract, harmful recommendation findings.", "observed"),
  fact("media-reach-risk", 2, "ftc-coppa-2025", "The FTC barred covered services from conditioning participation on unnecessary data collection and required opt-in consent for targeted-advertising disclosures.", "FTC release, final-rule protections paragraphs.", "observed"),
  fact("time-screen-purpose", 1, "common-sense-census-2025", "Screen time remained near 2.5 hours daily while gaming rose 65% in four years, traditional TV declined, and short-form video grew.", "Key findings paragraph, time-use changes.", "self-reported"),
  fact("time-screen-purpose", 2, "screen-socioemotional-review-2025", "Longitudinal effects ran both ways and were small overall; the authors recommended emphasizing content quality and social interaction, not minutes alone.", "Abstract, bidirectional results and guidance conclusion.", "observed"),
  fact("time-device-access", 1, "common-sense-census-2025", "Forty percent of children had a tablet by age two, and nearly one in four had a personal cellphone by age eight.", "Key findings paragraph, device-access metrics.", "self-reported"),
  fact("time-device-access", 2, "pwc-alpha-2026", "Seventy percent owned a tablet and 72% used smartphones regularly; smartphone ownership rose from 46% at ages seven to nine to 89% at ages thirteen to fourteen.", "Digital world section, device ownership findings.", "self-reported"),
  fact("time-youtube-rhythm", 1, "common-sense-census-2025", "Children averaged about 2.5 hours of screen media every day as YouTube Shorts and other short-form video became a growing part of that routine.", "Key findings paragraph, daily media time and YouTube Shorts trend.", "self-reported"),
  fact("time-youtube-rhythm", 2, "pew-teens-social-2024", "Seventy-three percent of U.S. teens visited YouTube daily, including 15% who said their use was almost constant.", "How often teens visit platforms section, YouTube frequency paragraph.", "self-reported"),
  fact("time-parent-context", 1, "common-sense-ai-2026", "More than four in ten children said no parent or guardian had ever discussed AI safety with them.", "Opening findings paragraph, parent-guidance metric.", "self-reported"),
  fact("time-parent-context", 2, "ftc-coppa-2025", "COPPA's revised rule requires parents to opt in before covered services disclose children's data for targeted advertising.", "FTC release, parental consent paragraph.", "observed"),
  fact("time-family-needs", 1, "common-sense-census-2025", "Tablet access reached 40% by age two while average daily media use held near 2.5 hours, showing screens are integrated into early household routines.", "Key findings paragraph, device and daily-use metrics.", "editorial inference"),
  fact("time-family-needs", 2, "pwc-alpha-2026", "Sixty percent of children said an adult pays when they make purchases, illustrating that growing digital independence still relies on family infrastructure.", "Following the money section, payment findings.", "editorial inference"),
  fact("time-age-change", 1, "common-sense-census-2025", "Tablet ownership reached 40% by age two, while nearly one in four children had a personal cellphone by age eight.", "Key findings paragraph, age-based access metrics.", "self-reported"),
  fact("time-age-change", 2, "pwc-alpha-2026", "Smartphone ownership increased from 46% among seven- to nine-year-olds to 89% among thirteen- to fourteen-year-olds.", "Digital world section, age comparison paragraph.", "self-reported"),
  fact("time-nighttime-use", 1, "bedtime-screen-early-adolescents-2024", "Early adolescents who left their phone ringer activated overnight had greater odds of sleep disturbance and shorter sleep one year later than peers who turned phones off at bedtime; bedtime social media, texting, and music use showed the same direction.", "Abstract, Results paragraph.", "self-reported"),
  fact("time-nighttime-use", 2, "prebed-screen-young-children-2021", "Among 30-month-olds, greater screen use before bedtime or during the nightly bedtime routine was associated with more sleep problems; more frequent routine use was also associated with later, shorter, and more variable sleep by actigraphy.", "Abstract, findings paragraph.", "observed"),
  fact("time-coexistence", 1, "screen-socioemotional-review-2025", "The meta-analysis found small reciprocal associations between screen use and socioemotional problems and urged attention to content and social context.", "Abstract, bidirectional results and conclusion.", "observed"),
  fact("time-coexistence", 2, "razorfish-alpha-industries", "Sixty-six percent would pay more for something usable only in real life, twice the share preferring something solely online.", "Industry findings section, real-world experience paragraph.", "self-reported"),
  fact("time-private-day", 1, "pew-teens-social-2024", "Ninety-five percent of teens had smartphone access and 46% described being online almost constantly.", "Device access and internet frequency sections.", "self-reported"),
  fact("time-private-day", 2, "pwc-alpha-2026", "Seventy-two percent used smartphones regularly, and smartphone ownership reached 89% among thirteen- to fourteen-year-olds.", "Digital world section, device findings.", "self-reported"),
  fact("time-household-context", 1, "pew-teens-video-games-2024", "Daily gaming varied by household income: 53% below $30,000, 42% from $30,000 to $74,999, and 39% at $75,000 or more.", "Who plays video games section, household-income paragraph.", "self-reported"),
  fact("time-household-context", 2, "pwc-alpha-2026", "Adults paid for children's purchases in 60% of cases, while access and ownership rose sharply with age.", "Following the money and digital world sections.", "editorial inference"),
  fact("learning-assembled", 1, "generation-alpha-education-review-2024", "Across 83 studies, no digital educational tool or online strategy emerged as dominant, despite many approaches being tested.", "Abstract, synthesis findings paragraph.", "observed"),
  fact("learning-assembled", 2, "walton-creation-gaming-2024", "Expert interviews observed children seeking explanations across YouTube, TikTok, and Minecraft when school instruction left gaps.", "Report analysis section, expert interview paragraph on self-directed learning.", "qualitative"),
  fact("learning-creation-skills", 1, "walton-creation-gaming-2024", "Children identified creativity and problem-solving as skills learned through Roblox and Minecraft, and at least seven in ten wanted curriculum subjects taught there.", "Key Findings section, skills and formal education findings.", "self-reported"),
  fact("learning-creation-skills", 2, "razorfish-alpha-industries", "Thirty-eight percent of Alphas interested in beauty content said they already create their own content.", "Industry findings section, social beauty paragraph.", "self-reported"),
  fact("learning-ai-homework", 1, "common-sense-ai-2026", "More than eight in ten AI users used it for entertainment and homework help; over half of children struggling to focus used AI for schoolwork weekly.", "Opening findings and key findings section, schoolwork paragraphs.", "self-reported"),
  fact("learning-ai-homework", 2, "razorfish-alpha-ai", "Homework was the leading reported AI use at 53%, followed by fun or hobbies at 43% and use at school at 36%.", "AI day-to-day tool findings paragraph.", "self-reported"),
  fact("learning-ai-discovery", 1, "razorfish-alpha-ai", "Twenty-two percent used AI daily, with homework, hobbies, and school spanning instrumental and creative use.", "AI day-to-day tool findings paragraph.", "self-reported"),
  fact("learning-ai-discovery", 2, "nielsen-ai-discovery-2026", "Eighty percent of Gen Alpha respondents increased chatbot use in the prior 12 to 18 months, and more than half used chatbots daily.", "News release, chatbot adoption findings paragraph.", "self-reported"),
  fact("learning-safety-guidance", 1, "common-sense-ai-2026", "More than four in ten had never discussed AI safety with a parent, and only just over half had been taught safe AI use at school.", "Opening findings and key findings section, safety-guidance paragraphs.", "self-reported"),
  fact("learning-safety-guidance", 2, "razorfish-alpha-ai", "Parents' leading AI concerns included age-inappropriate content at 57%, reduced critical thinking at 56%, and misinformation at 53%.", "Parents and AI findings paragraph.", "self-reported"),
  fact("learning-verification", 1, "nielsen-ai-discovery-2026", "Three in four respondents verified chatbot answers, while traditional search led AI on trustworthiness by 50% to 27%.", "News release, trust and verification findings paragraphs.", "self-reported"),
  fact("learning-verification", 2, "common-sense-ai-2026", "Only one-third of children knew that AI cannot reliably distinguish fact from fiction.", "Key findings section, AI capability literacy paragraph.", "self-reported"),
  fact("learning-enablement", 1, "generation-alpha-education-review-2024", "The systematic review found many digital tools and online strategies under development, but no dominant approach and little evidence of true cohort differences.", "Abstract, synthesis findings and limitations paragraph.", "observed"),
  fact("learning-enablement", 2, "walton-creation-gaming-2024", "At least seven in ten children wanted to learn coding, art, or design through Roblox or Minecraft, tying value to enabled activity rather than hardware.", "Key Findings section, formal education finding.", "editorial inference"),
  fact("learning-remix", 1, "walton-creation-gaming-2024", "Children said building in Roblox and Minecraft develops creativity and problem-solving through active making.", "Key Findings section, cognitive development paragraph.", "self-reported"),
  fact("learning-remix", 2, "razorfish-alpha-industries", "Thirty-eight percent of Alphas interested in beauty media made content themselves, turning consumption into iterative self-presentation.", "Industry findings section, social beauty paragraph.", "editorial inference"),
  fact("learning-commercial-fluency", 1, "pwc-alpha-2026", "Ninety-seven percent said they make purchase decisions independently at least sometimes, and 61% used wish lists to plan requests.", "Opening findings and pint-sized negotiators section.", "self-reported"),
  fact("learning-commercial-fluency", 2, "razorfish-alpha-industries", "Children influenced household categories from food to cars, while two in three valued physical-only experiences over digital-only ones.", "Industry findings section, household influence and in-person experience paragraphs.", "self-reported"),
  fact("learning-multimodal", 1, "pwc-alpha-2026", "Children moved among touch, typing, and voice: 58% tapped or swiped, 50% typed, and 48% used voice commands.", "Digital world section, interaction-mode findings.", "self-reported"),
  fact("learning-multimodal", 2, "walton-creation-gaming-2024", "Children sought knowledge through YouTube, TikTok, and Minecraft and reported learning creativity and problem-solving through creation games.", "Report analysis section, expert interview and key findings paragraphs.", "qualitative"),
];

const claimKindByEvidenceType: Record<EvidenceType, EvidenceClaimKind> = {
  observed: "observed claim",
  "self-reported": "finding",
  qualitative: "finding",
  forecast: "finding",
  "platform-wide metric": "metric",
  "editorial inference": "editorial inference",
};

const supportRoleByInsightId: Record<string, [string, string]> = {
  "play-social-infrastructure": ["Quantifies friendship benefits and game-originated friendships, establishing play as a recurring social setting.", "Adds child-reported creativity, problem-solving, and team learning, showing that shared creation can carry social value."],
  "play-making-interface": ["Shows direct child interest in learning coding, art, and design inside creation games, linking play with making.", "Connects search and avatar-style behavior inside Roblox, illustrating how discovery, expression, and play share one environment."],
  "play-friendship-travels": ["Establishes that multiplayer activity and game-originated friendships are common among the surveyed teens.", "Documents the same interests moving through games, messaging, video, and in-person groups in longitudinal cases."],
  "play-avatars-identity": ["Shows avatar styles responding to named aesthetics and cultural trends, supporting identity expression inside play.", "Adds girls' reported filter use and demand for representation, supplying adjacent evidence about mediated self-presentation."],
  "play-small-crews": ["Shows that nearly all self-identified gamers played with others and many formed online friendships through games.", "Observes small groups repeatedly using private messages and games to coordinate, supporting the recurring-crew interpretation."],
  "play-competition-performance": ["Establishes high-frequency gaming as a substantial routine, supporting the scale of the underlying play culture.", "Documents leagues using young creators to translate sports for younger audiences, connecting competition with creator media."],
  "play-status-contribution": ["Shows style and search fluency as visible participation patterns, supporting cultural competence as one status signal.", "Adds player-reported creativity and problem-solving through building, supporting contribution and mastery as another signal."],
  "play-family-coplay": ["Measures very early personal-device access, establishing that household provision enables connected play and media.", "Shows adults paying for most child purchases, establishing continued household control over commercial participation."],
  "play-offline-rebound": ["Documents recent growth in organized youth-sport participation, supporting one narrow indicator of offline rebound.", "Documents recent growth in children's outdoor participation, adding a second narrow indicator rather than proof about all play."],
  "play-safety-boundaries": ["Provides child-rights guidance that safety and privacy protections belong in game design itself.", "Adds binding consent and data-retention requirements, showing that participation boundaries include enforceable privacy rules."],
  "media-video-default": ["Measures daily young-child media time and a shift toward video formats, establishing video's routine presence.", "Shows regular YouTube use alongside gaming and streaming, supporting video as a major route to entertainment and explanation."],
  "media-short-form-shape": ["Documents growth in short-form video inside a changing media mix, establishing that the format is becoming more prominent.", "Quantifies daily and near-constant TikTok use among teens, supplying adjacent evidence of the format's recurring rhythm."],
  "media-creators-templates": ["Documents leagues choosing young creators to translate sports into familiar formats, showing creators modeling participation.", "Measures social media as a reported purchase prompt, establishing that modeled interests can travel into commercial desire."],
  "media-household-negotiation": ["Shows a child-parent gap in reported ordering independence, establishing that autonomy is actively negotiated.", "Measures children's reported influence across family categories, adding evidence that adults and children share decision power."],
  "media-discovery-commerce": ["Links reported social purchase triggers with regular video and gaming use, establishing a plausible discovery-to-request path.", "Shows beauty interest and self-creation occurring together, supporting a surface where inspiration, participation, and commerce meet."],
  "media-repeatable-formats": ["Documents recurring creator partnerships and youth-native meme formats, showing organizations using portable cultural forms.", "Measures young people making versions of beauty content themselves, demonstrating that a format can travel through imitation."],
  "media-properties-travel": ["Shows sports properties extending through creators and social formats instead of relying only on broadcasts.", "Measures regular use across YouTube, games, and streaming, establishing multiple available routes into children's attention."],
  "media-coviewing": ["Shows children placing products into shared carts for adult review, directly supporting household-scale negotiation.", "Situates a changing media mix inside parent-managed young-child routines, adding context without claiming a co-viewing rate."],
  "media-ai-recommendation": ["Measures Gen Alpha respondents preferring chatbots for TV and movie recommendations, directly establishing conversational discovery.", "Shows frequent AI use for hobbies and fun, adding behavioral context for entertainment-oriented chatbot adoption."],
  "media-reach-risk": ["Experimental recommendation data shows younger accounts receiving more harmful content, establishing an age-linked feed risk.", "Adds current limits on unnecessary collection and targeted-ad disclosure, establishing privacy risk alongside media reach."],
  "time-screen-purpose": ["Shows stable total time alongside major changes in gaming, television, and short-form use, proving totals can hide purpose shifts.", "Finds small bidirectional effects and recommends attention to content and social context, reinforcing a purpose-aware interpretation."],
  "time-device-access": ["Measures tablet ownership by age two and cellphone ownership by age eight, directly establishing early access.", "Adds a steep seven-to-fourteen smartphone ownership gradient, showing that access develops before full independence."],
  "time-youtube-rhythm": ["Places YouTube Shorts growth inside roughly 2.5 daily hours of young-child media, supporting a recurring household rhythm.", "Measures high daily teen YouTube use, providing adjacent evidence that the rhythm persists into older Alpha ages."],
  "time-parent-context": ["Measures a substantial gap in parent-child AI safety conversations, showing that guidance is not automatic.", "Defines a parental opt-in requirement for targeted-ad disclosures, establishing permission as part of media management."],
  "time-family-needs": ["Combines early tablet access with stable daily use, supporting screens as integrated household infrastructure.", "Shows adult payment underpinning children's choices, adding a second practical way family systems enable digital activity."],
  "time-age-change": ["Directly compares device access at ages two and eight, showing meaningful change within the cohort.", "Directly compares smartphone ownership at ages seven to nine and thirteen to fourteen, confirming a steep age gradient."],
  "time-nighttime-use": ["Prospectively links specific overnight phone and bedtime media behaviors with later sleep outcomes in early adolescents.", "Links toddler bedtime screen routines with actigraphic and parent-reported sleep outcomes, extending the issue to younger ages."],
  "time-coexistence": ["Finds small reciprocal screen associations and emphasizes context, cautioning against a simple digital-displacement story.", "Shows a stated preference for physical-only value over digital-only value, adding evidence that offline experience remains desirable."],
  "time-private-day": ["Measures near-universal teen smartphone access and frequent connectivity, establishing the scale of portable private use.", "Adds high smartphone use and ownership among older Alpha respondents, showing the pattern reaching the cohort's oldest members."],
  "time-household-context": ["Shows daily gaming varying by household income, directly establishing that routines are not economically uniform.", "Shows adult payment and age-linked ownership, adding household infrastructure and development to the access picture."],
  "learning-assembled": ["A systematic review finds no dominant digital approach, supporting a learning environment assembled from multiple tools.", "Observes children seeking explanations across video, social, and game environments when school instruction leaves gaps."],
  "learning-creation-skills": ["Measures children naming creativity and problem-solving as learned skills and wanting curriculum inside creation games.", "Shows youth already making their own interest-based content, adding adjacent evidence of active rather than passive participation."],
  "learning-ai-homework": ["Measures entertainment and homework help among the leading youth AI uses, directly supporting school-related adoption.", "Independently ranks homework as the leading reported AI use, reinforcing the conclusion with a second study."],
  "learning-ai-discovery": ["Shows daily AI use spanning homework, hobbies, and school, establishing use beyond one formal task.", "Measures rapid growth and daily chatbot use, adding scale to AI's role in discovery and everyday support."],
  "learning-safety-guidance": ["Measures missing family conversations and incomplete school instruction, directly establishing a guidance gap.", "Measures parent concerns about content, critical thinking, and misinformation, showing what that guidance needs to address."],
  "learning-verification": ["Shows many respondents checking chatbot answers while trusting search more, establishing verification as an active behavior.", "Shows only one-third understood AI's fact-fiction limitation, establishing a concrete literacy gap."],
  "learning-enablement": ["Finds many tools but no dominant approach or clear cohort effect, supporting evaluation by enabled activity rather than novelty.", "Shows children wanting specific creative subjects inside games, tying perceived value to what technology lets them do."],
  "learning-remix": ["Shows children learning through active building, supporting iteration and making as part of creative development.", "Shows young people turning viewed beauty content into their own creations, providing a concrete consumption-to-remix pathway."],
  "learning-commercial-fluency": ["Measures independent decisions and wish-list planning, directly establishing practical participation in commerce.", "Shows influence across household categories and preference for physical experiences, broadening the practical decision context."],
  "learning-multimodal": ["Measures children moving among touch, typing, and voice, directly establishing multiple interaction modes.", "Observes knowledge-seeking across video, social, and games alongside creation skills, adding multiple learning environments."],
};

const factsForInsight = (insightId: string) => extractedFacts.filter((item) => item.insightId === insightId);

type InsightEditorial = Pick<
  Insight,
  | "interpretation"
  | "confidence"
  | "confidenceReason"
  | "nuance"
  | "genZComparison"
  | "agencyImplication"
  | "relatedCreatorIds"
  | "relatedSpaceIds"
>;

const editorialByInsightId: Record<string, InsightEditorial> = {
  "play-social-infrastructure": {
    interpretation: "Gaming matters here as a recurring place to maintain friendship, not simply as entertainment consumed alone.", confidence: "medium", confidenceReason: "A national teen survey and child-focused creation-gaming research converge on friendship and social learning, but cover different age groups.", nuance: "The evidence shows social value for many players; it does not mean every game, server, or friendship is supportive.", genZComparison: "Gen Z normalized multiplayer friendship; Gen Alpha meets social play earlier and inside more creator-built worlds.", agencyImplication: "Give a group something useful to do together repeatedly, with private-by-default social choices.", relatedCreatorIds: ["aphmau"], relatedSpaceIds: ["roblox"],
  },
  "play-making-interface": {
    interpretation: "For many children, the same world can be a game, a studio, and an informal classroom.", confidence: "medium", confidenceReason: "Child survey findings on desired learning are reinforced by first-party behavior signals from a major creation platform.", nuance: "Interest in learning through a game is not evidence that every in-game lesson works or transfers beyond the platform.", genZComparison: "Gen Z often moved from playing to separate creator tools; Gen Alpha increasingly encounters both in one environment.", agencyImplication: "Offer flexible materials, prompts, or mechanics that reward making rather than a finished branded object.", relatedCreatorIds: ["aphmau"], relatedSpaceIds: ["minecraft"],
  },
  "play-friendship-travels": {
    interpretation: "The relationship is the stable layer; games, messages, video, and in-person time are interchangeable settings around it.", confidence: "medium", confidenceReason: "Large-scale teen self-report and longitudinal qualitative cases both document friendship moving through connected activities.", nuance: "Cross-platform friendship also creates moderation, privacy, and age-assurance challenges when context changes.", genZComparison: "Gen Z built cross-platform social lives; Gen Alpha is inheriting that pattern before platform boundaries feel distinct.", agencyImplication: "Design for continuity across sessions without requiring children to expose a public identity.", relatedCreatorIds: ["itsfunneh"], relatedSpaceIds: ["discord"],
  },
  "play-avatars-identity": {
    interpretation: "Avatar choices make aesthetics and affiliations visible to peers inside a playable environment.", confidence: "medium", confidenceReason: "Platform style patterns and girls' self-reported image practices support visible self-presentation, though neither measures identity development directly.", nuance: "Expression can be playful and empowering while still carrying appearance pressure, exclusion, or purchase pressure.", genZComparison: "Gen Z curated profiles; Gen Alpha can also make style visible through persistent characters inside playable worlds.", agencyImplication: "Make self-expression broad, inclusive, reversible, and useful without tying belonging to paid scarcity.", relatedCreatorIds: ["barbie"], relatedSpaceIds: ["roblox"],
  },
  "play-small-crews": {
    interpretation: "Repeated play and private messaging give a known friend group recurring places to coordinate and stay connected.", confidence: "medium", confidenceReason: "Survey and case-study evidence both support small-group gaming and messaging as recurring social settings.", nuance: "Small groups can offer intimacy, but they can also intensify exclusion and make conflict harder to escape.", genZComparison: "Gen Z made private group chats central to friendship; Alpha cases show that games can be another recurring room for the crew.", agencyImplication: "Reward collaboration and return visits by a small group instead of public popularity metrics.", relatedCreatorIds: ["kai-cenat"], relatedSpaceIds: ["discord"],
  },
  "play-competition-performance": {
    interpretation: "High-frequency gaming sits beside creator-led sports coverage, linking play with a broader stream of youth media.", confidence: "medium", confidenceReason: "Teen gaming frequency is directly measured, while league creator partnerships provide observed examples of sports translation rather than audience-wide proof.", nuance: "The evidence does not establish that all competition is watched, narrated, or shared, only that play and creator media occupy connected cultural territory.", genZComparison: "Gen Z helped turn esports into media; Gen Alpha also encounters mainstream sports translated through creator formats.", agencyImplication: "Connect a participatory challenge to a creator or story format without assuming every player wants to perform publicly.", relatedCreatorIds: ["jesser"], relatedSpaceIds: ["youtube"],
  },
  "play-status-contribution": {
    interpretation: "Search fluency, avatar style, and active building are all observable forms of participation inside shared worlds.", confidence: "medium", confidenceReason: "Platform behavior and children's self-reported making skills establish visible participation, not a measured status hierarchy.", nuance: "Visible contribution can broaden participation, while item scarcity and insider language can still exclude newcomers.", genZComparison: "Gen Z signaled taste through posts and follows; Alpha participation can also be visible through builds, skins, and in-world competence.", agencyImplication: "Let recognition come from contribution, mastery, or generosity rather than purchase alone.", relatedCreatorIds: ["kreekcraft"], relatedSpaceIds: ["roblox"],
  },
  "play-family-coplay": {
    interpretation: "Even when children choose the activity, adults often shape access, payment, permissions, and the practical limits around it.", confidence: "medium", confidenceReason: "National device-access findings and international child purchase data directly support household enablement, not the frequency of literal co-play.", nuance: "Adult involvement varies sharply by age, household resources, platform, and whether participation requires spending.", genZComparison: "Gen Z gained personal access during adolescence; much of Gen Alpha encounters connected play while still dependent on household infrastructure.", agencyImplication: "Make the child value clear and give adults a plain account of cost, data, safety, and stopping points.", relatedCreatorIds: ["bluey"], relatedSpaceIds: ["home-family-routines"],
  },
  "play-offline-rebound": {
    interpretation: "Recent gains in organized sport and outdoor participation challenge the idea that digital play simply replaces physical activity.", confidence: "low", confidenceReason: "This is a directional inference from two narrower U.S. participation categories rather than a measure of all offline play.", nuance: "Sport and outdoor participation are not all offline play, and participant counts do not reveal frequency, quality, affordability, or access.", genZComparison: "Both cohorts blend online and offline life; current Alpha signals make the coexistence easier to see than a simple substitution story.", agencyImplication: "Connect digital invitation to a worthwhile physical action without implying that every child has equal offline access.", relatedCreatorIds: ["danny-go"], relatedSpaceIds: ["after-school-sports-clubs"],
  },
  "play-safety-boundaries": {
    interpretation: "Safety settings, data rules, and adult controls are part of the play product rather than an external compliance layer.", confidence: "high", confidenceReason: "UNICEF design guidance and the revised COPPA rule independently establish concrete child-safety and privacy responsibilities.", nuance: "Compliance is a floor; it does not by itself resolve harmful contact, manipulative design, or uneven enforcement.", genZComparison: "Gen Z often entered systems retrofitted for safety; Gen Alpha is raising expectations that protection is present from first use.", agencyImplication: "Treat age assurance, privacy, reporting, spending, and parental visibility as core experience design.", relatedCreatorIds: ["pokemon"], relatedSpaceIds: ["nintendo-switch"],
  },
  "media-video-default": {
    interpretation: "Young children's daily media mix and older Alpha platform use both place video among the cohort's regular media routes.", confidence: "high", confidenceReason: "National young-child media-use data and a survey of ages seven to fourteen both show video embedded in the media mix.", nuance: "Video's prevalence differs by age and platform, and a high-use format is not automatically a trusted one.", genZComparison: "YouTube is highly present for both cohorts; the available studies do not establish that Alpha relies on it more.", agencyImplication: "Use video when the idea benefits from showing, while keeping the premise and source clear before playback.", relatedCreatorIds: ["mrbeast"], relatedSpaceIds: ["youtube"],
  },
  "media-short-form-shape": {
    interpretation: "Short-form video is growing among young children and appears as a frequent routine among adjacent teen audiences.", confidence: "medium", confidenceReason: "Child media-mix data and teen frequency data establish growth and routine use; they do not measure a resulting change in attention.", nuance: "Frequency does not diagnose attention capacity; content, purpose, pacing, and the option to stop all matter.", genZComparison: "Gen Z watched short-form become mainstream; Gen Alpha's youngest members are encountering it earlier in the media mix.", agencyImplication: "Make each unit understandable on its own and resist mechanics that depend on compulsive continuation.", relatedCreatorIds: ["alan-chikin-chow"], relatedSpaceIds: ["youtube-shorts"],
  },
  "media-creators-templates": {
    interpretation: "Sports organizations use young creators to translate established culture into formats younger audiences already follow.", confidence: "medium", confidenceReason: "Observed league partnerships and reported social-media purchase prompts establish creator relevance without measuring imitation.", nuance: "Visibility does not equal trust, and influence varies by age, category, relationship, and adult mediation.", genZComparison: "Creators matter across both cohorts; the Alpha evidence here shows organizational use and purchase prompting, not a higher level of influence.", agencyImplication: "Choose a creator for the subject and format they can credibly translate, not reach alone.", relatedCreatorIds: ["salish-matter"], relatedSpaceIds: ["youtube"],
  },
  "media-household-negotiation": {
    interpretation: "Children can initiate and shape a decision while adults retain payment, permission, or final approval.", confidence: "medium", confidenceReason: "Two child-and-parent studies identify concrete influence and independence gaps across multiple purchase categories.", nuance: "Influence is not purchasing power, and household authority changes with age, income, category, and culture.", genZComparison: "Gen Z's influence grew through social media; Gen Alpha is exercising it earlier inside shared digital purchasing flows.", agencyImplication: "Create separate, honest reasons for the child to care and the adult to approve.", relatedCreatorIds: ["ryans-world"], relatedSpaceIds: ["home-family-routines"],
  },
  "media-discovery-commerce": {
    interpretation: "The same feed can generate interest, demonstrate a product, normalize it socially, and hand the request into a family decision.", confidence: "medium", confidenceReason: "Two industry studies report linked social discovery, content creation, and purchase motivation among Alpha respondents.", nuance: "Self-reported purchase triggers do not prove conversion, and commercial literacy differs considerably by age.", genZComparison: "Gen Z saw social commerce emerge; Gen Alpha is meeting discovery and shopping as a more continuous experience.", agencyImplication: "Separate inspiration from transaction and make sponsorship, price, data use, and adult review unmistakable.", relatedCreatorIds: ["mrbeast"], relatedSpaceIds: ["tiktok"],
  },
  "media-repeatable-formats": {
    interpretation: "A recognizable challenge, sound, character, or ritual can travel farther than a one-off channel placement.", confidence: "medium", confidenceReason: "Observed sports partnerships and self-reported content making support format travel, but not a universal law of culture.", nuance: "Repeatability can invite participation or become empty imitation; community meaning depends on who can adapt the format.", genZComparison: "Gen Z spread memes across networks; Gen Alpha encounters more formats designed to move between creators, games, and properties.", agencyImplication: "Build a format with a stable rule and room for people to change the outcome.", relatedCreatorIds: ["kpop-demon-hunters"], relatedSpaceIds: ["youtube-shorts"],
  },
  "media-properties-travel": {
    interpretation: "Properties can enter attention through creator coverage, YouTube, gaming platforms, and streaming rather than one dominant channel.", confidence: "medium", confidenceReason: "Observed sports extensions and reported multi-platform use establish multiple routes, but do not measure how one title travels among them.", nuance: "Multiple available routes do not prove cross-platform movement, deeper affinity, or equal reach for every property.", genZComparison: "Gen Z followed properties across screens; Gen Alpha's current media mix gives those properties more participatory routes to try.", agencyImplication: "Choose the route that adds a distinct use or behavior instead of duplicating the same message everywhere.", relatedCreatorIds: ["pokemon"], relatedSpaceIds: ["netflix"],
  },
  "media-coviewing": {
    interpretation: "Media interests enter a household system where routines, shared carts, and adult review shape what happens next.", confidence: "medium", confidenceReason: "Shared-cart behavior and family media-routine evidence support negotiation at household scale, not a measured co-viewing rate.", nuance: "The evidence does not establish that families watched the same content together or agreed on its meaning.", genZComparison: "Gen Z's media influence was often framed as peer-led; Gen Alpha's younger ages keep household mediation visibly central.", agencyImplication: "Create an easy handoff from child interest to adult context without turning the child into a sales channel.", relatedCreatorIds: ["cocomelon"], relatedSpaceIds: ["home-family-routines"],
  },
  "media-ai-recommendation": {
    interpretation: "Conversational systems are becoming another front door to entertainment discovery alongside feeds, guides, and search.", confidence: "medium", confidenceReason: "Recent self-report studies show substantial chatbot recommendation preference and frequent AI use, but the behavior is changing quickly.", nuance: "Stated preference is not observed recommendation quality, and chatbot answers may be inaccurate, sponsored, or opaque.", genZComparison: "Gen Z learned algorithmic feeds; Gen Alpha is also learning to ask an algorithm directly and continue the conversation.", agencyImplication: "Make authoritative facts machine-readable and give young users a visible path to verify recommendations.", relatedCreatorIds: ["kpop-demon-hunters"], relatedSpaceIds: ["chatgpt"],
  },
  "media-reach-risk": {
    interpretation: "The systems that deliver scale can also deliver harmful recommendations and collect sensitive child data.", confidence: "medium", confidenceReason: "A large experimental preprint and binding U.S. policy changes identify concrete recommendation and privacy risks.", nuance: "The audit is a preprint and platform behavior can change; regulation also varies outside the United States.", genZComparison: "Gen Z exposed feed harms after adoption; Gen Alpha is growing up amid stronger evidence and regulation from the outset.", agencyImplication: "Audit adjacency, targeting, data collection, age treatment, and escalation paths before optimizing reach.", relatedCreatorIds: ["sssniperwolf"], relatedSpaceIds: ["youtube-shorts"],
  },
  "time-screen-purpose": {
    interpretation: "A single duration number collapses very different activities: talking, making, gaming, learning, and passive viewing.", confidence: "high", confidenceReason: "National time-use shifts and a longitudinal meta-analysis both support examining content and social context alongside duration.", nuance: "Purpose does not erase dose, sleep, displacement, or developmental concerns; it makes those questions more precise.", genZComparison: "Gen Z's debate centered hours online; Gen Alpha's mixed screen activities make that total less explanatory on its own.", agencyImplication: "Define the specific value of the screen moment and measure whether it displaces something important.", relatedCreatorIds: ["cocomelon"], relatedSpaceIds: ["youtube-kids"],
  },
  "time-device-access": {
    interpretation: "Personal devices arrive while children still depend on adults for rules, payments, transport, and developmental support.", confidence: "high", confidenceReason: "Two large child-media studies report early tablet and phone access with clear age gradients.", nuance: "Ownership, regular use, private access, and independent judgment are different conditions.", genZComparison: "Gen Z often received a first smartphone near adolescence; Gen Alpha's device pathway can begin with a personal tablet in toddlerhood.", agencyImplication: "Design onboarding for a child-and-caregiver system, not an assumed independent adult user.", relatedCreatorIds: ["like-nastya"], relatedSpaceIds: ["home-family-routines"],
  },
  "time-youtube-rhythm": {
    interpretation: "YouTube functions as a recurring household utility for entertainment, explanation, music, and filling small gaps in the day.", confidence: "high", confidenceReason: "National child and teen datasets both show sustained daily video use across adjacent Alpha ages.", nuance: "YouTube use spans distinct products and purposes; daily presence does not describe what was watched or with whom.", genZComparison: "Gen Z visited YouTube as a destination; Gen Alpha often experiences it as background infrastructure across routines.", agencyImplication: "Design for a recognizable recurring moment and give caregivers context before playback begins.", relatedCreatorIds: ["ms-rachel"], relatedSpaceIds: ["youtube"],
  },
  "time-parent-context": {
    interpretation: "Parenting the media day involves content, privacy, timing, permissions, and conversation, not only a timer.", confidence: "high", confidenceReason: "Child self-report reveals a guidance gap while COPPA defines a concrete parental-consent responsibility.", nuance: "More controls do not automatically create better guidance, especially when settings are complex or families have limited time.", genZComparison: "Gen Z's parents managed a smaller platform set; Gen Alpha families face AI and data decisions alongside screen limits.", agencyImplication: "Give adults concise controls and conversation prompts at the moment a decision is needed.", relatedCreatorIds: ["bluey"], relatedSpaceIds: ["home-family-routines"],
  },
  "time-family-needs": {
    interpretation: "Screens can occupy practical roles in care, transition, learning, and household coordination as well as leisure.", confidence: "medium", confidenceReason: "Device, daily-use, and adult-payment data show integration into family infrastructure; the specific needs are an editorial interpretation.", nuance: "A practical role does not make every use beneficial, and families have unequal access to alternatives and support.", genZComparison: "Gen Z's devices became personal social tools; Gen Alpha's earliest devices are often shared solutions inside caregiving routines.", agencyImplication: "Solve a real family task and be honest about duration, supervision, and what the experience cannot replace.", relatedCreatorIds: ["cocomelon"], relatedSpaceIds: ["youtube-kids"],
  },
  "time-age-change": {
    interpretation: "Averages across the full generation hide steep changes in device ownership, autonomy, platforms, and social context.", confidence: "high", confidenceReason: "Two studies report direct age-based access differences from early childhood through young adolescence.", nuance: "Chronological age is only one variable; development, family rules, and prior experience also shape readiness.", genZComparison: "Generational labels flattened Gen Z too; Alpha's current 0-to-16 span makes age segmentation especially non-negotiable.", agencyImplication: "State the intended age and redesign access, language, social features, and adult involvement for it.", relatedCreatorIds: ["salish-matter"], relatedSpaceIds: ["youtube"],
  },
  "time-nighttime-use": {
    interpretation: "The media day extends into bedtime through active phones, social communication, music, and routine viewing.", confidence: "high", confidenceReason: "Prospective early-adolescent data and objective toddler sleep measurement both associate specific bedtime screen patterns with sleep outcomes.", nuance: "Associations differ by behavior and age and do not prove that every nighttime screen causes poor sleep.", genZComparison: "Gen Z brought social media to bed; Gen Alpha's nighttime exposure begins earlier and includes a wider range of devices and routines.", agencyImplication: "Support quiet defaults, clear stopping cues, notification controls, and caregiver-visible bedtime settings.", relatedCreatorIds: ["nicole-laeno"], relatedSpaceIds: ["snapchat"],
  },
  "time-coexistence": {
    interpretation: "Screen use needs contextual interpretation, while many Alpha respondents still place a premium on physical-only experience.", confidence: "medium", confidenceReason: "Longitudinal screen evidence and stated preference for physical-only experiences both challenge a simple online-versus-offline binary.", nuance: "The sources do not measure a daily balance or prove that the same children increased both kinds of activity.", genZComparison: "Both cohorts combine digital and physical life; the Alpha evidence here establishes offline demand rather than a generation-level rebound.", agencyImplication: "Design digital participation to prompt, document, or enrich a worthwhile offline action.", relatedCreatorIds: ["danny-go"], relatedSpaceIds: ["after-school-sports-clubs"],
  },
  "time-private-day": {
    interpretation: "Portable personal access creates the technical possibility of media use outside a shared household screen.", confidence: "high", confidenceReason: "National teen and Alpha surveys both document extensive smartphone access and high-frequency use among older children.", nuance: "Access does not prove secrecy, unsupervised use, or harm; it only changes what use is possible.", genZComparison: "Near-universal teen access provides the Gen Z context; older Gen Alpha is now reaching similarly high ownership in a separate study.", agencyImplication: "Assume use can happen alone and build discreet safety, exit, reporting, and notification controls.", relatedCreatorIds: ["charli-damelio"], relatedSpaceIds: ["snapchat"],
  },
  "time-household-context": {
    interpretation: "Access, gaming frequency, payment, and autonomy vary with household resources and cannot be treated as a universal Alpha baseline.", confidence: "medium", confidenceReason: "Income-stratified gaming data and child payment reporting establish meaningful household differences, though they measure different populations.", nuance: "Income is not the same as culture, parenting style, connectivity, disability, or local opportunity.", genZComparison: "The digital divide shaped Gen Z access; for Gen Alpha it also shapes quality of devices, subscriptions, supervision, and creative opportunity.", agencyImplication: "Test the experience under lower-bandwidth, shared-device, no-purchase, and limited-adult-time conditions.", relatedCreatorIds: ["ryans-world"], relatedSpaceIds: ["home-family-routines"],
  },
  "learning-assembled": {
    interpretation: "A child may combine school, video, a game, search, and another person to answer one learning need.", confidence: "medium", confidenceReason: "A systematic review and qualitative child-media research both support a distributed learning environment without naming one dominant tool.", nuance: "Self-assembled learning can be resourceful but leaves quality, curriculum fit, and verification uneven.", genZComparison: "Gen Z learned to search across the web; Gen Alpha assembles answers across more interactive and conversational environments.", agencyImplication: "Make a useful explanation modular, attributable, and easy to carry into the next learning context.", relatedCreatorIds: ["ms-rachel"], relatedSpaceIds: ["youtube"],
  },
  "learning-creation-skills": {
    interpretation: "Children perceive building in game worlds as practice in creativity, problem-solving, coding, art, and design.", confidence: "medium", confidenceReason: "Direct child survey findings support perceived skill value; the second source shows adjacent youth making but not measured transfer.", nuance: "Perceived learning is not a skills assessment, and access to constructive modes, mentors, and time is uneven.", genZComparison: "Gen Z learned creator tools around games; Gen Alpha can encounter skill-building as an ordinary mode within play.", agencyImplication: "Set an open-ended challenge and make the learned technique visible after the child builds.", relatedCreatorIds: ["aphmau"], relatedSpaceIds: ["minecraft"],
  },
  "learning-ai-homework": {
    interpretation: "AI has already joined the practical toolkit children use for explanations, homework support, and school tasks.", confidence: "medium", confidenceReason: "Two recent youth studies independently rank homework among the most common reported AI uses.", nuance: "Use does not show learning quality, independent understanding, school permission, or whether answers were checked.", genZComparison: "Gen Z searched for homework help; Gen Alpha can request a tailored answer and follow-up in the same interface.", agencyImplication: "Support hints, reasoning, citations, and checking rather than delivering an opaque final answer.", relatedCreatorIds: ["ms-rachel"], relatedSpaceIds: ["chatgpt"],
  },
  "learning-ai-discovery": {
    interpretation: "Children are using AI beyond assignments to explore interests, create, get recommendations, and seek everyday support.", confidence: "medium", confidenceReason: "Two recent studies report frequent chatbot use across hobbies, entertainment, school, and discovery, but rely on self-report.", nuance: "Broad use categories conceal quality, risk, privacy, and large differences between products and ages.", genZComparison: "Gen Z adopted generative AI after formative habits were set; Gen Alpha is incorporating it while those habits are still forming.", agencyImplication: "Design bounded exploration with source visibility, privacy protection, and routes to human help.", relatedCreatorIds: ["moriah-elizabeth"], relatedSpaceIds: ["chatgpt"],
  },
  "learning-safety-guidance": {
    interpretation: "Children's AI use is expanding faster than consistent family conversations and school instruction about safe use.", confidence: "medium", confidenceReason: "Child reports of missing guidance align with parent concerns about content, thinking, and misinformation.", nuance: "Concern is not measured harm, and guidance quality matters more than whether a conversation happened once.", genZComparison: "Gen Z received social-media literacy after adoption; Gen Alpha risks repeating that lag with conversational AI.", agencyImplication: "Put age-appropriate guidance, privacy explanations, and escalation paths inside the interaction itself.", relatedCreatorIds: ["bluey"], relatedSpaceIds: ["home-family-routines"],
  },
  "learning-verification": {
    interpretation: "Knowing when and how to check an answer is becoming as important as knowing how to ask for one.", confidence: "medium", confidenceReason: "Youth self-report shows both active verification and a substantial misunderstanding of AI reliability.", nuance: "Saying one verifies does not reveal the method, and children may compare one weak source with another.", genZComparison: "Gen Z learned source evaluation for search results; Gen Alpha must also evaluate fluent answers that hide their sources.", agencyImplication: "Expose citations, uncertainty, alternative views, and a simple verification step at the point of answer.", relatedCreatorIds: ["moriah-elizabeth"], relatedSpaceIds: ["khan-academy"],
  },
  "learning-enablement": {
    interpretation: "Educational value comes from the activity, support, and setting a tool enables, not the novelty of the device.", confidence: "high", confidenceReason: "A systematic review finds no dominant technology while child research ties interest to specific enabled activities.", nuance: "A promising activity still depends on pedagogy, accessibility, teacher or caregiver support, and implementation quality.", genZComparison: "Gen Z classrooms often led with device access; Alpha's crowded tool landscape makes purpose a stronger filter than hardware.", agencyImplication: "Name the capability first, then choose the lightest technology that reliably enables it.", relatedCreatorIds: ["ms-rachel"], relatedSpaceIds: ["google-classroom"],
  },
  "learning-remix": {
    interpretation: "Children report active building in games, while some interest-based viewers also report making their own content.", confidence: "medium", confidenceReason: "Child creation-gaming findings and youth content-making signals both establish active production, while iteration remains an editorial interpretation.", nuance: "The evidence does not measure revision frequency, skill transfer, or identity outcomes from remixing.", genZComparison: "Both cohorts remix media; Alpha's creation environments include playable systems alongside posts and video edits.", agencyImplication: "Provide editable building blocks, creditable sources, and room for visible personal variation.", relatedCreatorIds: ["moriah-elizabeth"], relatedSpaceIds: ["capcut"],
  },
  "learning-commercial-fluency": {
    interpretation: "Wish lists, shared carts, requests, and category influence give children practical experience navigating household commerce.", confidence: "medium", confidenceReason: "Two industry studies document child decision participation and influence across products and experiences.", nuance: "Commercial fluency is not consumer protection; younger children may recognize a transaction without understanding persuasion or data use.", genZComparison: "Gen Z learned influencer commerce in adolescence; Gen Alpha practices negotiation and digital purchase requests earlier.", agencyImplication: "Make value, price, sponsorship, scarcity, and adult approval legible without manufacturing urgency.", relatedCreatorIds: ["salish-matter"], relatedSpaceIds: ["instagram"],
  },
  "learning-multimodal": {
    interpretation: "Children report using touch, typing, and voice and are observed seeking knowledge across video, social, and game environments.", confidence: "medium", confidenceReason: "Interaction-mode survey data and qualitative learning observations both document multiple modalities and settings.", nuance: "Multiple available modes do not mean every child uses them interchangeably or learns equally well through each one.", genZComparison: "Gen Z became mobile-first; Alpha evidence adds routine voice interaction and conversational systems to the available modes.", agencyImplication: "Offer more than one path into the idea while keeping the underlying concept consistent and accessible.", relatedCreatorIds: ["aphmau"], relatedSpaceIds: ["youtube"],
  },
};

export const insights: Insight[] = insightSeeds.map((seed) => ({
  ...seed,
  evidenceIds: factsForInsight(seed.id).map((item) => `evidence-${item.insightId}-${item.slot}`),
  ageRange: "Varies by supporting evidence",
  geography: "Varies by supporting evidence",
  ...editorialByInsightId[seed.id],
}));

export const evidenceItems: EvidenceItem[] = extractedFacts.map((item) => {
    const source = sourceById.get(item.sourceId);
    const insight = insightSeeds.find((candidate) => candidate.id === item.insightId);
    if (!source) {
      throw new Error(`Unknown source ${item.sourceId} in ${item.insightId}`);
    }
    if (!insight) {
      throw new Error(`Unknown insight ${item.insightId}`);
    }

    return {
      id: `evidence-${item.insightId}-${item.slot}`,
      sourceId: item.sourceId,
      claim: item.claim,
      claimKind: claimKindByEvidenceType[item.evidenceType],
      supportRationale: supportRoleByInsightId[item.insightId][item.slot - 1],
      locator: item.locator,
      evidenceType: item.evidenceType,
      population: source.population,
      ageRange: source.ageRange,
      geography: source.geography,
      period: source.fieldworkPeriod,
      methodology: source.methodology,
      limitations: source.limitations,
      insightIds: [item.insightId],
    };
  });
