import type { StrategyPlay } from "./types";

export const strategyPlays: StrategyPlay[] = [
  {
    id: "make-or-shape",
    title: "Give them something to make or shape.",
    whenAppropriate: "Use this when the idea can leave a child with an artifact, a practiced skill, a meaningful choice, or a changed outcome. Participation should alter the experience, not decorate a finished campaign.",
    ageContext: "Ages 5-13, with guided tools and short sessions for ages 5-8, flexible systems for ages 9-12, and more authorship and peer collaboration for early teens.",
    directChildValue: "A useful prompt, tool, material, or rule set that lets a child build, remix, solve, perform, or teach something in more than one valid way.",
    adultDecisionContext: "Adults still decide access, account setup, time, spending, transport, and whether public sharing is appropriate. Show them the learning or play value before asking for permission or payment.",
    evidenceRationale: "Research with ages 5-13 connects creation gaming in Roblox and Minecraft with creativity, problem-solving, and interest in learning skills. The evidence supports open-ended making, not a claim that any branded build is educational.",
    formats: ["Modular build challenge", "Remixable template or starter kit", "Guided making session", "Create-then-explain prompt"],
    failureModes: ["A single pre-scripted result disguised as choice", "A branded world with nothing consequential to do", "A public contest that rewards polish, spending, or popularity over participation"],
    ethicalConstraints: ["Keep the core making experience free of pay-to-win mechanics", "Do not require a public profile, face, voice, or real name to participate", "Use age-appropriate moderation and obtain adult permission before public sharing"],
    insightIds: ["play-making-interface", "learning-creation-skills"],
    sourceIds: ["walton-creation-gaming-2024"],
    relatedSpaceIds: ["roblox", "minecraft", "scratch", "canva"],
    relatedCultureShaperIds: ["minecraft", "aphmau", "barbie"],
  },
  {
    id: "repeatable-format",
    title: "Build a repeatable format, not a one-off message.",
    whenAppropriate: "Use this when the audience can learn the premise quickly and return because the role, rhythm, or challenge stays recognizable while the content changes.",
    ageContext: "Ages 8-17, with concrete rules and visible progress for younger participants and more room for interpretation, collaboration, and authorship for teens.",
    directChildValue: "A dependable rhythm: they know what happens, what part is theirs, and what new variation makes the next installment worth joining.",
    adultDecisionContext: "Adults need a legible cadence, a clear endpoint, and confidence that return behavior is voluntary rather than driven by streak pressure, scarcity, or escalating spend.",
    evidenceRationale: "The evidence graph shows culture traveling through recurring formats across creators, sports, video, and play. This supports a durable participation grammar, not automatic replication of whichever trend is currently visible.",
    formats: ["Episodic challenge with a stable rule", "Weekly prompt with a finite season", "Recurring character and problem", "Repeatable classroom or club activity"],
    failureModes: ["A one-off stunt with no role beyond watching", "Copying a trend after its community meaning has passed", "An always-on cadence that turns return into obligation"],
    ethicalConstraints: ["Disclose sponsorship clearly in every installment", "Avoid streaks, countdown pressure, and artificial scarcity for children", "Offer a complete experience without requiring continuous data collection"],
    insightIds: ["media-repeatable-formats", "media-creators-templates"],
    sourceIds: ["ap-sports-alpha-2026"],
    relatedSpaceIds: ["youtube", "youtube-shorts", "after-school-sports-clubs"],
    relatedCultureShaperIds: ["cocomelon", "bluey", "cristiano-ronaldo"],
  },
  {
    id: "child-and-enabling-adult",
    title: "Design for the child and the enabling adult.",
    whenAppropriate: "Use this whenever a child can want the experience but an adult controls access, purchase, transport, account permission, time, or risk.",
    ageContext: "Most important from ages 3-14. Adult mediation is strongest in early childhood and remains material as older children gain personal devices and spending influence without full independence.",
    directChildValue: "A child-facing promise they can understand: what they get to do, learn, watch, collect, or share, and what the limits are.",
    adultDecisionContext: "A separate adult-facing case should state cost, setup, duration, supervision, data use, age fit, cancellation, and what happens when a child asks to spend or share.",
    evidenceRationale: "PwC reports that child influence and adult payment coexist, while Common Sense documents early device access inside the household. The work therefore needs two honest value propositions rather than child excitement doing the adult persuasion for it.",
    formats: ["Child preview plus adult explainer", "Co-view or co-play guide", "Family challenge with separate roles", "Transparent permission and purchase flow"],
    failureModes: ["Designing the excitement and leaving adults to decode the conditions", "Writing adult reassurance in a falsely childlike voice", "Hiding recurring cost, public sharing, or account requirements until setup"],
    ethicalConstraints: ["Never use a child's pressure on an adult as the conversion mechanism", "Separate child-directed content from adult purchase and consent decisions", "Make price, renewals, data use, and exit paths plain before commitment"],
    insightIds: ["media-household-negotiation", "play-family-coplay", "time-parent-context"],
    sourceIds: ["pwc-alpha-2026", "common-sense-census-2025", "ftc-coppa-2025"],
    relatedSpaceIds: ["home-family-routines", "youtube-kids", "nintendo-switch"],
    relatedCultureShaperIds: ["bluey", "ms-rachel"],
  },
  {
    id: "useful-ritual",
    title: "Enter an existing ritual with useful value.",
    whenAppropriate: "Use this when the idea can help with a routine that already exists - getting ready, winding down, traveling, practicing, gathering after school, or making sense of a topic.",
    ageContext: "Ages 3-12, with adult-led household rituals for younger children and increasingly self-directed school, hobby, and friendship routines for older children.",
    directChildValue: "A small, repeatable benefit inside the moment: a song that guides a transition, a prompt that starts play, a tool that reduces friction, or a trusted explanation.",
    adultDecisionContext: "The experience must fit the household's time, noise, device, accessibility, and supervision realities. Adults should be able to understand when it starts, when it ends, and what need it serves.",
    evidenceRationale: "Common Sense and Ofcom show video, devices, and shared interests embedded in ordinary household and friendship routines. That supports useful participation in an existing moment, not inventing a new habit simply to increase exposure.",
    formats: ["Three-minute routine prompt", "Co-viewed explanation", "After-school club kit", "Downloadable activity with a clear stopping point"],
    failureModes: ["Interrupting a ritual without solving a real problem", "Adding another daily obligation to a crowded family schedule", "Treating every repeated moment as inventory for a message"],
    ethicalConstraints: ["Do not manufacture anxiety about missing a day", "Design a clear ending and an offline alternative", "Respect accessibility, family structure, language, and uneven access to devices or time"],
    insightIds: ["time-youtube-rhythm", "time-family-needs", "learning-assembled"],
    sourceIds: ["common-sense-census-2025", "walton-creation-gaming-2024"],
    relatedSpaceIds: ["home-family-routines", "school", "youtube-kids", "after-school-sports-clubs"],
    relatedCultureShaperIds: ["cocomelon", "bluey"],
  },
  {
    id: "physical-digital-loop",
    title: "Create a physical-digital loop.",
    whenAppropriate: "Use this when a digital prompt can lead to movement, making, collecting, visiting, or face-to-face play - and the physical activity can deepen the digital story without being tracked.",
    ageContext: "Ages 6-14, with nearby adult-supported activities for younger children and more independent team, event, and hobby participation as children get older.",
    directChildValue: "A reason to leave the feed and do something tangible: move, build, trade, observe, practice, meet, or bring an object back into the story.",
    adultDecisionContext: "Adults determine transport, cost, location safety, equipment, accessibility, and whether an event or exchange is appropriate. A useful loop must work without precise location data or expensive gear.",
    evidenceRationale: "The evidence shows online and offline activities coexisting, with recent directional growth in organized sport and outdoor participation. It supports connected modes of participation while explicitly not proving that screens cause offline activity.",
    formats: ["Screen-to-play activity card", "Build offline, document privately", "Event companion with no location tracking", "Collecting or practice prompt that works with common materials"],
    failureModes: ["Calling product purchase an offline activity", "Requiring travel, equipment, or paid entry without an equivalent low-cost path", "Using a scavenger mechanic to collect precise child location"],
    ethicalConstraints: ["Do not collect or expose a child's precise location", "Provide accessible, low-cost, and no-device participation routes", "Use adult permission for events, exchanges, public uploads, or contact with others"],
    insightIds: ["time-coexistence", "play-offline-rebound", "media-properties-travel"],
    sourceIds: ["project-play-state-of-play-2025", "outdoor-participation-trends-2026", "screen-socioemotional-review-2025", "ap-sports-alpha-2026"],
    relatedSpaceIds: ["pokemon", "after-school-sports-clubs", "cinemas-live-entertainment", "minecraft"],
    relatedCultureShaperIds: ["pokemon", "caitlin-clark"],
  },
  {
    id: "creator-format-fluency",
    title: "Use creators for format fluency, not borrowed fame alone.",
    whenAppropriate: "Use a creator when their way of teaching, reacting, building, hosting, or involving an audience makes the idea better - not when the plan only needs their follower count.",
    ageContext: "Ages 8-17, with stronger adult oversight and simpler participation for under-13 audiences; live, chat-led, and public response formats belong at the older end and still require moderation.",
    directChildValue: "The creator makes the premise legible, demonstrates how to join, and contributes a format the audience already understands rather than delivering a detached endorsement.",
    adultDecisionContext: "Adults and agency teams must assess age fit, disclosure, moderation, brand and creator history, usage rights, and whether the collaboration creates pressure through trust or parasocial closeness.",
    evidenceRationale: "The evidence describes creators as behavioral templates and documents sports organizations adapting through creator-led formats. This supports co-design around recognizable participation behavior, not fame as a proxy for relevance or safety.",
    formats: ["Creator-led tutorial", "Co-designed recurring challenge", "Behind-the-format explanation", "Moderated workshop or recorded demonstration"],
    failureModes: ["A celebrity cameo pasted onto an unchanged message", "A rigid script that removes the creator's actual format fluency", "Selecting by aggregate followers without audience-age or safety evidence"],
    ethicalConstraints: ["Make paid relationships unmistakable to children and adults", "Do not use parasocial trust to pressure purchase, disclosure, or contact", "Moderate participation and protect any child contributor's consent, labor, identity, and compensation"],
    insightIds: ["media-creators-templates", "media-repeatable-formats", "media-reach-risk"],
    sourceIds: ["ap-sports-alpha-2026", "arxiv-young-user-safety-2025"],
    relatedSpaceIds: ["youtube", "youtube-shorts", "twitch"],
    relatedCultureShaperIds: ["aphmau", "ishowspeed"],
  },
  {
    id: "visible-safety",
    title: "Make safety, privacy, and transparency visible product qualities.",
    whenAppropriate: "Always. Treat these as observable parts of the child and adult experience, especially when the idea includes accounts, chat, AI, personalization, purchases, location, public sharing, or user-generated content.",
    ageContext: "Across ages 3-17. Under-13 design should default to minimal data and adult-mediated consent; older children still need plain controls, age-appropriate explanations, and protection from manipulative defaults.",
    directChildValue: "Simple language, predictable boundaries, private defaults, clear reporting and exit controls, and an explanation of what the system knows and why.",
    adultDecisionContext: "Adults need visible data practices, moderation rules, spending controls, contact settings, retention periods, escalation paths, and honest limits before enabling access.",
    evidenceRationale: "UNICEF calls for safety and privacy by design in online games, the FTC's revised COPPA rule strengthens consent and data limits, and the evidence graph shows safety risk sharing the same feeds as reach. Safety cannot remain a legal footer.",
    formats: ["Plain-language safety walkthrough", "Just-in-time permission moment", "Private-by-default profile", "Visible report, block, reset, and delete controls"],
    failureModes: ["A long policy standing in for usable controls", "Collecting first and offering an opt-out later", "Safety settings that are hard to find, understand, or reverse"],
    ethicalConstraints: ["Minimize collection and prohibit behavioral targeting of children", "Do not sell, repurpose, or retain child data beyond the stated need", "Use age assurance proportionately without creating a new identity or surveillance risk", "Test reporting and moderation with child-safety expertise before launch"],
    insightIds: ["play-safety-boundaries", "media-reach-risk", "learning-safety-guidance"],
    sourceIds: ["unicef-online-gaming", "ftc-coppa-2025", "arxiv-young-user-safety-2025", "common-sense-ai-2026"],
    relatedSpaceIds: ["roblox", "messenger-kids", "chatgpt"],
    relatedCultureShaperIds: ["minecraft", "bluey"],
  },
  {
    id: "measure-usefulness",
    title: "Measure participation and usefulness, not reach alone.",
    whenAppropriate: "Use this as the measurement frame for every child-facing initiative. Define the useful action and the stop condition before choosing distribution metrics.",
    ageContext: "Segment outcomes by developmental band and context rather than reporting one Gen Alpha total. What counts as useful for a six-year-old, a tween, and a sixteen-year-old will differ.",
    directChildValue: "Success should show up in what a child could make, understand, practice, complete, or choose to return to - not only whether content crossed their screen.",
    adultDecisionContext: "Adults can judge whether the experience was worth the time, cost, setup, and data exchange. Their view is context, not permission to profile the child more deeply.",
    evidenceRationale: "Creation-gaming research measures perceived skills and desired learning, while wellbeing evidence warns that duration alone hides content and context. The strategy implication is to pair reach with observable usefulness and voluntary participation.",
    formats: ["Artifact or skill rubric", "Finite completion measure", "Voluntary child and adult feedback", "Return-with-purpose measure tied to a specific activity"],
    failureModes: ["Treating impressions or watch time as proof of value", "Engineering repeat use solely to improve a retention chart", "Public leaderboards that turn participation into status pressure"],
    ethicalConstraints: ["Use aggregate, age-banded measurement with the least data possible", "Do not infer emotion, vulnerability, identity, or household status for optimization", "Do not rank or retarget individual children", "Publish stop conditions for harm, low value, or disproportionate burden"],
    insightIds: ["play-status-contribution", "learning-enablement", "time-screen-purpose"],
    sourceIds: ["walton-creation-gaming-2024", "screen-socioemotional-review-2025"],
    relatedSpaceIds: ["scratch", "canva", "school", "after-school-sports-clubs"],
    relatedCultureShaperIds: ["minecraft", "pokemon"],
  },
];
