import type { ConnectorStatus, Story } from "./types";

const observedAt = "2026-07-22T12:00:00.000Z";

export const connectorSeeds: ConnectorStatus[] = [
  { id: "news", label: "News", status: "updated", message: "Curated publication feeds", refreshedAt: observedAt },
  { id: "reddit", label: "Reddit", status: "needs-credentials", message: "Official API access required" },
  { id: "podcasts", label: "Podcasts", status: "updated", message: "Episode feeds and show notes", refreshedAt: observedAt },
  { id: "studies", label: "Studies", status: "updated", message: "Crossref research metadata", refreshedAt: observedAt },
  { id: "events", label: "Events", status: "updated", message: "Culture and event feeds", refreshedAt: observedAt },
  { id: "x", label: "X", status: "needs-credentials", message: "Official X API access required" }
];

export const seedStories: Story[] = [
  story("knicks-brands", "Knicks win, brands win", "Michelob Ultra, Nike, and ESPN centered New York's celebration instead of interrupting it.", "LBBOnline", "https://lbbonline.com/news/new-york-knicks-win-nba-finals-michelob-ultra-bbdo", "publication", "sport", ["basketball", "city culture", "real-time"], "Brands responded to the Knicks championship through distinct executions built around the city's emotional moment.", "The strongest work added to a shared celebration rather than treating fandom as borrowed attention.", "Build for what the moment means to people before deciding what Gatorade needs to say."),
  story("world-cup-absurdity", "Absurdity plays in the World Cup", "Miller Lite turned the tournament into a product joke with a limited-edition Matchball.", "PR Newswire", "https://www.prnewswire.com/news-releases/miller-lite-scores-big-with-new-limited-edition-matchball-for-the-true-mvps-the-fans-302770147.html", "publication", "sport", ["football", "humor", "product"], "Miller Lite rejected category solemnity and introduced a soccer-ball-shaped package for fans.", "When every sponsor reaches for emotion, a brand-truthful left turn can become the more culturally fluent move."),
  story("levis-coverup", "Stadium sponsors get off the sideline", "Levi's turned a covered stadium logo into the creative idea rather than accepting invisibility.", "Fast Company", "https://www.fastcompany.com/91559785/levis-logo-coverup-fifa-world-cup-stadium-brand-win", "publication", "sport", ["sponsorship", "constraint", "agility"], "Stadium restrictions became the premise of Levi's World Cup response instead of a reason to stay quiet.", "Constraints can create a more ownable cultural entrance than formal sponsorship inventory."),
  story("oura-invisibility", "Oura leads with invisibility", "The ring's newest story is how little technology interrupts daily life.", "The Drum", "https://www.thedrum.com/news/ad-of-the-day-oura-talks-up-the-invisibility-of-tech-in-subtle-power-series", "publication", "wellness", ["wearables", "digital fatigue", "recovery"], "Oura framed its product around subtle presence and low interruption.", "As digital fatigue grows, invisible utility can signal progress more powerfully than added features.", "Hydration technology should reduce effort and friction rather than demand more attention."),
  story("ordinary-bus", "The Ordinary ran a free bus in Brooklyn", "A beauty brand solved a 50-minute transit problem by acting on accessibility and function.", "Fast Company", "https://www.fastcompany.com/91545723/the-ordinary-skincare-brand-marketing-bus-rides", "publication", "community", ["access", "New York", "brand action"], "The Ordinary offered free transport during a major subway disruption.", "The activation made the brand's belief useful in a moment that had nothing to do with skincare.", "New hydration occasions should extend a real brand belief, not just the product footprint."),
  story("etsy-jeffs", "Etsy fights Prime Day with real Jeffs", "Etsy gave the spotlight to sellers who share a first name with Amazon's founder.", "Retail Dive", "https://www.retaildive.com/news/etsy-marketing-campaign-amazon-prime-day-shop-other-jeffs/823118/", "publication", "culture", ["retail", "human stories", "platform"], "Etsy used Prime Day to elevate small sellers named Jeff instead of competing on scale.", "Platforms build emotional distinction when the people inside them become the story."),
  story("tim-payne", "The internet chose Tim Payne", "A Twitch shoutout moved an underknown player from thousands to millions of followers.", "Yahoo Sports", "https://sports.yahoo.com/articles/tim-payne-meet-zealands-viral-193613371.html", "community", "culture", ["Twitch", "fandom", "relatability"], "A streamer singled out Tim Payne as a lesser-known World Cup player and the audience rapidly rallied around him.", "Cultural influence is increasingly sparked by participatory internet dynamics rather than planned celebrity machinery."),
  story("creator-recovery", "Recovery is becoming creator content", "Athletes and creators increasingly narrate sleep, readiness, and recovery as part of performance identity.", "Apple Podcasts", "https://podcasts.apple.com/us/genre/podcasts-health-fitness/id1512", "podcast", "wellness", ["recovery", "creator", "performance"], "Health and performance shows are turning private recovery routines into public, repeatable media formats.", "The category is shifting from expert instruction toward lived rituals audiences can compare, remix, and adopt.", "Gatorade can treat recovery knowledge as culture and storytelling, not only education."),
  story("hydration-study", "Hydration research is widening beyond elite performance", "Recent research discovery increasingly connects hydration with cognition, heat, sleep, and everyday movement.", "Crossref", "https://search.crossref.org/?q=hydration%20cognition%20exercise", "study", "wellness", ["research", "cognition", "heat"], "Academic discovery shows hydration studied across physical performance and daily wellbeing contexts.", "A wider evidence base can help the category enter occasions without pretending every person is training for competition."),
  story("festival-rituals", "Festivals are laboratories for shared ritual", "Music festivals concentrate fashion, fandom, recovery, food, weather, and identity in one place.", "Lollapalooza", "https://www.lollapalooza.com/", "event", "entertainment", ["music", "festival", "ritual"], "Large festivals combine intense physical conditions with highly visible community behaviors.", "They reveal how people prepare, signal belonging, care for friends, and sustain energy in public."),
  story("gaming-sport", "Sport fandom keeps moving into game worlds", "Sports identity now travels between broadcasts, creator streams, competitive games, and social play.", "YouTube Culture & Trends", "https://www.youtube.com/trends/", "publication", "technology", ["gaming", "fandom", "creators"], "Digital play and sports conversation increasingly overlap across video and creator communities.", "The fan journey is no longer a sequence from game to recap; it is a continuous social layer."),
  story("cooling-cities", "Heat is changing the culture of public space", "Cities, leagues, and communities are adapting movement, gathering, and events around hotter conditions.", "Google News", "https://news.google.com/search?q=heat%20cities%20sports%20culture", "event", "behavior", ["heat", "cities", "public space"], "Extreme heat is altering when and how people exercise, gather, commute, and attend events.", "Climate adaptation is becoming a daily behavior and design question, not a distant sustainability story.", "Hydration can participate through useful infrastructure and care, not only heat-warning messaging.")
];

function story(id: string, headline: string, dek: string, sourceName: string, sourceUrl: string, sourceKind: Story["sourceKind"], domain: Story["domain"], tags: string[], whatHappened: string, whyItMatters: string, gatoradeImplication?: string): Story {
  return { id, headline, dek, sourceName, sourceUrl, sourceKind, publishedAt: "2026-07-15T12:00:00.000Z", observedAt, domain, tags, whatHappened, whyItMatters, gatoradeImplication };
}
